packages:
  - "customer-portal"
  - "customer-portal/frontend"
  - "customer-portal/frontend/shared"
  - "customer-portal/frontend/portal"
  - "customer-portal/frontend/admin"
  - "openai-gateway"
  - "vtuber-gateway"
  - "vtuber-gateway/src/frontend/portal"
  - "vtuber-runner/avatar-renderer"
