packages:
  - "customer-portal"
  - "customer-portal/frontend"
  - "customer-portal/frontend/shared"
  - "customer-portal/frontend/portal"
  - "customer-portal/frontend/admin"
  - "openai-gateway"
  - "video-gateway"
  - "video-gateway/src/frontend"
