package middleware

import (
	"encoding/base64"
	"errors"
	"math/big"
	"net/http"
	"strconv"

	"github.com/Cloud-SPE/livepeer-network-rewrite/capability-broker/internal/livepeerheader"
	"github.com/Cloud-SPE/livepeer-network-rewrite/capability-broker/internal/payment"
)

// CapabilitySpec is what the payment middleware needs to pass to the
// daemon's OpenSession: the work-unit identifier and the wei price per
// work unit. Both come from the broker's host-config capabilities
// list.
type CapabilitySpec struct {
	WorkUnit            string
	PricePerWorkUnitWei *big.Int
}

// CapabilityLookup resolves a (capability_id, offering_id) pair to its
// pricing metadata. The broker wires `s.lookup` into this; the
// middleware uses it without depending on internal/config.
type CapabilityLookup func(capability, offering string) (CapabilitySpec, bool)

// Payment is the payment-lifecycle middleware:
//
//	OpenSession(work_id, capability, offering, price, work_unit)
//	  → ProcessPayment(payment_bytes, work_id)
//	  → handler.Serve
//	  → DebitBalance(sender, work_id, work_units, debit_seq=1)
//	  → CloseSession(sender, work_id)
//
// The work_id is the inbound `Livepeer-Request-Id` (or generated by
// the RequestID middleware if absent). One work_id per request in
// v0.2; plan 0015 introduces interim debits that reuse a long-lived
// work_id across multiple debit calls.
//
// Decode/cross-check failures map to:
//   - missing/malformed Livepeer-Payment header → 401 + payment_invalid
//   - capability not found in host-config       → 404 + capability_not_served
//   - offering not found under capability       → 404 + offering_not_served
//   - daemon rejects (mismatch / bad sender)    → 401 + payment_invalid
func Payment(client payment.Client, lookup CapabilityLookup) Middleware {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			paymentHeader := r.Header.Get(livepeerheader.Payment)
			if paymentHeader == "" {
				livepeerheader.WriteError(w, http.StatusUnauthorized, livepeerheader.ErrPaymentInvalid,
					"missing Livepeer-Payment header")
				return
			}
			paymentBytes, err := base64.StdEncoding.DecodeString(paymentHeader)
			if err != nil {
				livepeerheader.WriteError(w, http.StatusUnauthorized, livepeerheader.ErrPaymentInvalid,
					"Livepeer-Payment is not valid base64: "+err.Error())
				return
			}

			capability := r.Header.Get(livepeerheader.Capability)
			offering := r.Header.Get(livepeerheader.Offering)
			spec, ok := lookup(capability, offering)
			if !ok {
				livepeerheader.WriteError(w, http.StatusNotFound, livepeerheader.ErrCapabilityNotServed,
					"capability "+capability+"/"+offering+" is not served by this broker")
				return
			}

			workID := RequestIDFromContext(r.Context())
			if workID == "" {
				// RequestID middleware always sets one; defense in depth.
				livepeerheader.WriteError(w, http.StatusInternalServerError, livepeerheader.ErrInternalError,
					"missing request id (RequestID middleware not wired)")
				return
			}

			ctx := r.Context()

			// 1. OpenSession. Idempotent: a retry with the same work_id
			//    returns OUTCOME_ALREADY_OPEN.
			if _, err := client.OpenSession(ctx, payment.OpenSessionRequest{
				WorkID:              workID,
				Capability:          capability,
				Offering:            offering,
				PricePerWorkUnitWei: spec.PricePerWorkUnitWei,
				WorkUnit:            spec.WorkUnit,
			}); err != nil {
				livepeerheader.WriteError(w, http.StatusInternalServerError, livepeerheader.ErrInternalError,
					"open session: "+err.Error())
				return
			}

			// 2. ProcessPayment. Daemon decodes wire bytes, seals
			//    sender, credits EV.
			result, err := client.ProcessPayment(ctx, payment.ProcessPaymentRequest{
				WorkID:       workID,
				PaymentBytes: paymentBytes,
			})
			if err != nil {
				code, errCode := mapClientErr(err)
				livepeerheader.WriteError(w, code, errCode, "process payment: "+err.Error())
				return
			}

			// Always close the session, even on early-return paths below.
			defer func() { _ = client.CloseSession(ctx, result.Sender, workID) }()

			rec := &responseRecorder{ResponseWriter: w}
			next.ServeHTTP(rec, r)

			// Read actual work units. Same trailer-fallback logic as v0.1:
			// for http-stream@v0 the value lands in resp.Header() AFTER
			// the body, so we re-read post-handler.
			actual := rec.workUnits
			if actual == 0 {
				if h := rec.Header().Get(livepeerheader.WorkUnits); h != "" {
					if n, err := strconv.ParseUint(h, 10, 64); err == nil {
						actual = n
					}
				}
			}

			// 3. DebitBalance. v0.2 issues exactly one debit per session
			//    (debit_seq=1); plan 0015 will issue a sequence of
			//    debits for long-running modes.
			if actual > 0 {
				_, _ = client.DebitBalance(ctx, payment.DebitBalanceRequest{
					Sender:    result.Sender,
					WorkID:    workID,
					WorkUnits: int64(actual),
					DebitSeq:  1,
				})
			}
		})
	}
}

// mapClientErr translates daemon-side rejection into broker-facing
// error codes. v0.2: any RPC error from the daemon is treated as
// `payment_invalid`; defense-in-depth for bad inputs and chain
// failures alike.
func mapClientErr(err error) (int, string) {
	if errors.Is(err, errors.ErrUnsupported) {
		return http.StatusInternalServerError, livepeerheader.ErrInternalError
	}
	return http.StatusUnauthorized, livepeerheader.ErrPaymentInvalid
}
