package middleware

import (
	"context"
	"encoding/base64"
	"errors"
	"log"
	"math/big"
	"net/http"
	"strconv"
	"sync"
	"sync/atomic"
	"time"

	"github.com/Cloud-SPE/livepeer-network-rewrite/capability-broker/internal/extractors"
	"github.com/Cloud-SPE/livepeer-network-rewrite/capability-broker/internal/livepeerheader"
	"github.com/Cloud-SPE/livepeer-network-rewrite/capability-broker/internal/payment"
)

// CapabilitySpec is what the payment middleware needs to pass to the
// daemon's OpenSession: the work-unit identifier and the wei price per
// work unit. Both come from the broker's host-config capabilities
// list.
type CapabilitySpec struct {
	WorkUnit            string
	PricePerWorkUnitWei *big.Int
}

// CapabilityLookup resolves a (capability_id, offering_id) pair to its
// pricing metadata. The broker wires `s.lookup` into this; the
// middleware uses it without depending on internal/config.
type CapabilityLookup func(capability, offering string) (CapabilitySpec, bool)

// InterimDebitConfig governs the long-running session ticker per plan
// 0015 §7. Zero values are safe defaults: an empty config is equivalent
// to interim-debit disabled (v0.2 single-debit fall-through).
type InterimDebitConfig struct {
	// Interval is the tick cadence. 0 disables the ticker entirely.
	// Default 30s; recommended floor in production is 1s (the broker
	// logs WARN below 1s outside of test environments).
	Interval time.Duration
	// MinRunwayUnits is the minimum required runway passed to
	// SufficientBalance per tick. 60 is the recommended default for
	// `seconds-elapsed` workloads at the 30s tick cadence.
	MinRunwayUnits uint64
	// GraceOnInsufficient is the duration the middleware waits between
	// observing `sufficient=false` and terminating the handler. Zero
	// (the default) means hard-terminate immediately. Reserved for the
	// future mid-session ticket top-up plan; v0.1 ships with the flag
	// wired and the default zero (per plan 0015 §11 decision 3).
	GraceOnInsufficient time.Duration
}

// SessionState is the per-request handle the dispatch layer uses to
// publish a LiveCounter back to the payment middleware. The middleware
// creates one before invoking next.ServeHTTP and stuffs it into the
// request context; the dispatch layer reads it before invoking the
// driver and calls SetLiveCounter once the driver's Params are ready.
//
// SessionState is intentionally goroutine-safe: the ticker reads
// LiveCounter() concurrently with dispatch's SetLiveCounter call.
type SessionState struct {
	live atomic.Pointer[liveCounterHolder]
}

type liveCounterHolder struct {
	lc extractors.LiveCounter
}

// SetLiveCounter publishes a LiveCounter for the in-flight session.
// Called by the dispatch layer once the driver's Params are constructed.
// nil is a no-op (mode driver does not support interim debit).
func (s *SessionState) SetLiveCounter(lc extractors.LiveCounter) {
	if s == nil || lc == nil {
		return
	}
	s.live.Store(&liveCounterHolder{lc: lc})
}

// LiveCounter returns the current LiveCounter or nil. Safe for
// concurrent use.
func (s *SessionState) LiveCounter() extractors.LiveCounter {
	if s == nil {
		return nil
	}
	if h := s.live.Load(); h != nil {
		return h.lc
	}
	return nil
}

type sessionStateKey struct{}

// SessionStateFromContext returns the SessionState attached by the
// payment middleware, or nil if absent (e.g. unpaid routes).
func SessionStateFromContext(ctx context.Context) *SessionState {
	if v := ctx.Value(sessionStateKey{}); v != nil {
		if s, ok := v.(*SessionState); ok {
			return s
		}
	}
	return nil
}

// Payment is the payment-lifecycle middleware:
//
//	OpenSession(work_id, capability, offering, price, work_unit)
//	  → ProcessPayment(payment_bytes, work_id)
//	  → handler.Serve  (parallel: interim DebitBalance + SufficientBalance ticker)
//	  → final DebitBalance(sender, work_id, work_units, debit_seq=N+1)
//	  → CloseSession(sender, work_id)
//
// The work_id is the inbound `Livepeer-Request-Id` (or generated by
// the RequestID middleware if absent). One work_id per request; long-
// running modes reuse the same work_id across the interim-debit
// sequence.
//
// Decode/cross-check failures map to:
//   - missing/malformed Livepeer-Payment header → 401 + payment_invalid
//   - capability not found in host-config       → 404 + capability_not_served
//   - offering not found under capability       → 404 + offering_not_served
//   - daemon rejects (mismatch / bad sender)    → 401 + payment_invalid
func Payment(client payment.Client, lookup CapabilityLookup, idc InterimDebitConfig) Middleware {
	// Production-safety warning per plan 0015 §9.1: tick intervals
	// below 1s are intended for conformance fixtures only.
	if idc.Interval > 0 && idc.Interval < time.Second {
		log.Printf("warning: --interim-debit-interval=%s is below the 1s production floor; "+
			"this is intended for conformance / test environments only", idc.Interval)
	}
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			paymentHeader := r.Header.Get(livepeerheader.Payment)
			if paymentHeader == "" {
				livepeerheader.WriteError(w, http.StatusUnauthorized, livepeerheader.ErrPaymentInvalid,
					"missing Livepeer-Payment header")
				return
			}
			paymentBytes, err := base64.StdEncoding.DecodeString(paymentHeader)
			if err != nil {
				livepeerheader.WriteError(w, http.StatusUnauthorized, livepeerheader.ErrPaymentInvalid,
					"Livepeer-Payment is not valid base64: "+err.Error())
				return
			}

			capability := r.Header.Get(livepeerheader.Capability)
			offering := r.Header.Get(livepeerheader.Offering)
			spec, ok := lookup(capability, offering)
			if !ok {
				livepeerheader.WriteError(w, http.StatusNotFound, livepeerheader.ErrCapabilityNotServed,
					"capability "+capability+"/"+offering+" is not served by this broker")
				return
			}

			workID := RequestIDFromContext(r.Context())
			if workID == "" {
				// RequestID middleware always sets one; defense in depth.
				livepeerheader.WriteError(w, http.StatusInternalServerError, livepeerheader.ErrInternalError,
					"missing request id (RequestID middleware not wired)")
				return
			}

			ctx := r.Context()

			// 1. OpenSession. Idempotent: a retry with the same work_id
			//    returns OUTCOME_ALREADY_OPEN.
			if _, err := client.OpenSession(ctx, payment.OpenSessionRequest{
				WorkID:              workID,
				Capability:          capability,
				Offering:            offering,
				PricePerWorkUnitWei: spec.PricePerWorkUnitWei,
				WorkUnit:            spec.WorkUnit,
			}); err != nil {
				livepeerheader.WriteError(w, http.StatusInternalServerError, livepeerheader.ErrInternalError,
					"open session: "+err.Error())
				return
			}

			// 2. ProcessPayment. Daemon decodes wire bytes, seals
			//    sender, credits EV.
			result, err := client.ProcessPayment(ctx, payment.ProcessPaymentRequest{
				WorkID:       workID,
				PaymentBytes: paymentBytes,
			})
			if err != nil {
				code, errCode := mapClientErr(err)
				livepeerheader.WriteError(w, code, errCode, "process payment: "+err.Error())
				return
			}

			// Always close the session, even on early-return paths below.
			defer func() { _ = client.CloseSession(ctx, result.Sender, workID) }()

			// 3. Set up interim-debit ticker. The dispatch layer publishes
			//    the LiveCounter via the SessionState we attach to the
			//    request context; the ticker polls it on each tick.
			//
			//    When idc.Interval == 0 (locked decision #6) or the
			//    driver does not support interim debit (LiveCounter never
			//    set), the ticker is a no-op and the post-handler path
			//    falls through to the v0.2 single-debit flow.
			state := &SessionState{}
			ctx = context.WithValue(ctx, sessionStateKey{}, state)
			handlerCtx, cancelHandler := context.WithCancel(ctx)
			defer cancelHandler()

			rec := &responseRecorder{ResponseWriter: w}

			tickerDone := make(chan struct{})
			tickerStop := make(chan struct{})
			var (
				tickerSeq           atomic.Uint64 // last successfully-sent debit_seq; final flush uses N+1
				tickerLastTickTotal atomic.Uint64 // cumulative units already debited
				terminationReason   atomic.Pointer[string]
			)

			if idc.Interval > 0 {
				go runInterimDebitTicker(handlerCtx, tickerStop, tickerDone, interimDebitArgs{
					client:         client,
					sender:         result.Sender,
					workID:         workID,
					interval:       idc.Interval,
					minRunwayUnits: idc.MinRunwayUnits,
					graceOnInsuff:  idc.GraceOnInsufficient,
					state:          state,
					seq:            &tickerSeq,
					lastTickTotal:  &tickerLastTickTotal,
					cancelHandler:  cancelHandler,
					terminated:     &terminationReason,
				})
			} else {
				// Interim debit disabled — close immediately so the
				// final-flush path doesn't wait on a no-op channel.
				close(tickerDone)
				close(tickerStop)
			}

			next.ServeHTTP(rec, r.WithContext(handlerCtx))

			// 4. Stop the ticker (idempotent if already disabled), wait
			//    for it to drain, then perform the final flush. Plan
			//    0015 §3.3: the final DebitBalance is issued by the main
			//    middleware path, not the ticker, so there is no race
			//    between a late tick and the close.
			if idc.Interval > 0 {
				select {
				case <-tickerStop:
					// already closed (e.g. by the ticker on insufficient_balance)
				default:
					close(tickerStop)
				}
				<-tickerDone
			}

			// Read actual work units. Same trailer-fallback logic as v0.1:
			// for http-stream@v0 the value lands in resp.Header() AFTER
			// the body, so we re-read post-handler.
			actual := rec.workUnits
			if actual == 0 {
				if h := rec.Header().Get(livepeerheader.WorkUnits); h != "" {
					if n, err := strconv.ParseUint(h, 10, 64); err == nil {
						actual = n
					}
				}
			}

			// For long-running sessions the LiveCounter is the canonical
			// running view; prefer its end-of-session reading over the
			// (often absent) Livepeer-Work-Units header.
			if lc := state.LiveCounter(); lc != nil {
				if liveTotal := lc.CurrentUnits(); liveTotal > actual {
					actual = liveTotal
				}
			}

			// 5. Final DebitBalance.
			//    - Single-debit path (idc.Interval == 0 or no interim
			//      ticks fired): debit_seq=1, work_units=actual.
			//    - Interim-debit path: debit_seq=N+1,
			//      work_units = actual - lastTickTotal.
			lastTotal := tickerLastTickTotal.Load()
			lastSeq := tickerSeq.Load()
			var finalSeq uint64 = 1
			var finalUnits uint64 = actual
			if lastSeq > 0 {
				finalSeq = lastSeq + 1
				if actual > lastTotal {
					finalUnits = actual - lastTotal
				} else {
					finalUnits = 0
				}
			}
			if finalUnits > 0 {
				_, _ = client.DebitBalance(ctx, payment.DebitBalanceRequest{
					Sender:    result.Sender,
					WorkID:    workID,
					WorkUnits: int64(finalUnits),
					DebitSeq:  finalSeq,
				})
			}

			// 6. If the ticker terminated the session for insufficient
			//    balance, record the cause for any post-mortem
			//    observability. Trailer-style Livepeer-Error emission is
			//    a future plan-0015 follow-up; the v0.1 cut logs at WARN.
			if reason := terminationReason.Load(); reason != nil {
				log.Printf("warning: interim-debit terminated work_id=%s reason=%s", workID, *reason)
			}
		})
	}
}

// interimDebitArgs is the parameter bundle for the ticker goroutine.
type interimDebitArgs struct {
	client         payment.Client
	sender         []byte
	workID         string
	interval       time.Duration
	minRunwayUnits uint64
	graceOnInsuff  time.Duration
	state          *SessionState
	seq            *atomic.Uint64
	lastTickTotal  *atomic.Uint64
	cancelHandler  context.CancelFunc
	terminated     *atomic.Pointer[string]
}

// runInterimDebitTicker is the per-session goroutine that issues
// DebitBalance + SufficientBalance on each tick. Plan 0015 §3.
//
// Lifecycle:
//   - On every tick (post-LiveCounter publication): compute delta,
//     DebitBalance with the next debit_seq; SufficientBalance check.
//   - If SufficientBalance returns false: optionally wait
//     graceOnInsufficient, cancel the handler context, exit.
//   - On stop or ctx cancellation: exit immediately. The main
//     middleware path performs the final flush; the ticker does not.
func runInterimDebitTicker(ctx context.Context, stop <-chan struct{}, done chan<- struct{}, a interimDebitArgs) {
	defer close(done)
	t := time.NewTicker(a.interval)
	defer t.Stop()
	var pendingSeq uint64
	var pendingMu sync.Mutex
	for {
		select {
		case <-ctx.Done():
			return
		case <-stop:
			return
		case <-t.C:
		}

		// Skip ticks that fire before the dispatch layer publishes a
		// LiveCounter; happens when the driver has no interim view
		// (HTTP family) — the no-op tick keeps fixed cost trivial.
		lc := a.state.LiveCounter()
		if lc == nil {
			continue
		}

		current := lc.CurrentUnits()
		last := a.lastTickTotal.Load()
		delta := uint64(0)
		if current > last {
			delta = current - last
		}

		// Debit the delta if non-zero. Reuse the pending seq on retry;
		// move forward only on a non-error reply (plan 0015 §5.3).
		if delta > 0 {
			pendingMu.Lock()
			if pendingSeq == 0 {
				pendingSeq = a.seq.Load() + 1
			}
			seq := pendingSeq
			pendingMu.Unlock()
			if _, err := a.client.DebitBalance(ctx, payment.DebitBalanceRequest{
				Sender:    a.sender,
				WorkID:    a.workID,
				WorkUnits: int64(delta),
				DebitSeq:  seq,
			}); err != nil {
				// Retry with same seq next tick. Don't advance.
				log.Printf("warning: interim DebitBalance work_id=%s seq=%d delta=%d failed: %v (will retry)",
					a.workID, seq, delta, err)
				continue
			}
			pendingMu.Lock()
			a.seq.Store(seq)
			a.lastTickTotal.Store(last + delta)
			pendingSeq = 0
			pendingMu.Unlock()
		}

		// SufficientBalance runway check. Plan 0015 §6.3 ships with
		// "every tick" frequency for v0.1.
		if a.minRunwayUnits == 0 {
			continue
		}
		res, err := a.client.SufficientBalance(ctx, payment.SufficientBalanceRequest{
			Sender:       a.sender,
			WorkID:       a.workID,
			MinWorkUnits: int64(a.minRunwayUnits),
		})
		if err != nil {
			log.Printf("warning: SufficientBalance work_id=%s failed: %v (will retry)",
				a.workID, err)
			continue
		}
		if !res.Sufficient {
			if a.graceOnInsuff > 0 {
				select {
				case <-ctx.Done():
					return
				case <-stop:
					return
				case <-time.After(a.graceOnInsuff):
				}
				// Re-check after grace.
				res2, err := a.client.SufficientBalance(ctx, payment.SufficientBalanceRequest{
					Sender:       a.sender,
					WorkID:       a.workID,
					MinWorkUnits: int64(a.minRunwayUnits),
				})
				if err == nil && res2 != nil && res2.Sufficient {
					continue
				}
			}
			reason := livepeerheader.ErrInsufficientBalance
			a.terminated.Store(&reason)
			log.Printf("warning: terminating session work_id=%s reason=%s", a.workID, reason)
			a.cancelHandler()
			return
		}
	}
}

// mapClientErr translates daemon-side rejection into broker-facing
// error codes. v0.2: any RPC error from the daemon is treated as
// `payment_invalid`; defense-in-depth for bad inputs and chain
// failures alike.
func mapClientErr(err error) (int, string) {
	if errors.Is(err, errors.ErrUnsupported) {
		return http.StatusInternalServerError, livepeerheader.ErrInternalError
	}
	return http.StatusUnauthorized, livepeerheader.ErrPaymentInvalid
}
