package desiredstate

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// Runner is the side-effecting half — writing the compose file and
// driving docker. It is an interface so the reconcile logic can be
// tested without a docker daemon, and so a dry run is a real mode
// rather than a code path nobody exercises.
type Runner interface {
	WriteCompose(path, content string) error
	Pull(ctx context.Context, path string) error
	Up(ctx context.Context, path string) error
}

// ComposeRunner drives the real docker compose.
type ComposeRunner struct {
	// Binary and Args let a host that uses `docker-compose` or a
	// wrapper say so rather than being told what its docker is called.
	Binary string
	Args   []string
}

func (r ComposeRunner) binary() (string, []string) {
	if strings.TrimSpace(r.Binary) != "" {
		return r.Binary, r.Args
	}
	return "docker", []string{"compose"}
}

func (r ComposeRunner) WriteCompose(path, content string) error {
	if dir := filepath.Dir(path); dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}
	// Written whole and replaced atomically: a compose file caught
	// half-written by a concurrent `docker compose up` is a host that
	// stops serving for reasons nobody can reconstruct.
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

func (r ComposeRunner) Pull(ctx context.Context, path string) error {
	return r.run(ctx, path, "pull")
}

// Up removes orphans, so a service the pool withdrew and the agent has
// already drained actually stops rather than lingering.
func (r ComposeRunner) Up(ctx context.Context, path string) error {
	return r.run(ctx, path, "up", "-d", "--remove-orphans")
}

func (r ComposeRunner) run(ctx context.Context, path string, args ...string) error {
	binary, prefix := r.binary()
	full := append(append([]string{}, prefix...), "-f", path)
	full = append(full, args...)
	cmd := exec.CommandContext(ctx, binary, full...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s %s: %w: %s", binary, strings.Join(full, " "), err, strings.TrimSpace(string(out)))
	}
	return nil
}

// RenderCompose assembles the services into one compose file.
//
// A draining service is still rendered. The pool wants it gone, but the
// broker is still finishing work on it, so it stays up until the drain
// completes — dropping it here would kill it mid-request.
func RenderCompose(doc Document) string {
	var b strings.Builder
	b.WriteString("# Generated by pool-member-agent. Do not edit.\n")
	b.WriteString("# Revision: " + doc.Revision + "\n")
	b.WriteString("services:\n")
	services := append([]Service(nil), doc.Services...)
	sort.Slice(services, func(i, j int) bool { return services[i].Name < services[j].Name })
	for _, service := range services {
		fragment := service.ComposeFragment
		if !strings.HasSuffix(fragment, "\n") {
			fragment += "\n"
		}
		b.WriteString(fragment)
	}
	return b.String()
}

// Apply makes the host match the document and reports what happened.
//
// The report is built from what was attempted, not from what was asked
// for: a service the pool wants and this host could not start must come
// back as failed, because the pool's next decision depends on knowing
// the difference.
func Apply(ctx context.Context, runner Runner, composePath string, doc Document) StatusReport {
	report := StatusReport{Revision: doc.Revision}
	content := RenderCompose(doc)
	if err := runner.WriteCompose(composePath, content); err != nil {
		return allFailed(doc, "write compose: "+err.Error())
	}
	// Pull first and separately: an image that will not download is a
	// different failure from one that will not start, and rolling them
	// together would report the wrong one.
	if err := runner.Pull(ctx, composePath); err != nil {
		return allFailed(doc, "pull: "+err.Error())
	}
	if err := runner.Up(ctx, composePath); err != nil {
		return allFailed(doc, "compose up: "+err.Error())
	}
	for _, service := range doc.Services {
		status := StatusRunning
		detail := ""
		if service.Draining {
			// The container is up, but the pool has withdrawn it and
			// the broker has been told to stop dispatching. Reporting
			// it as running would keep the assignment alive forever.
			status = StatusStopped
			detail = "draining"
		}
		report.Services = append(report.Services, ServiceStatus{
			Name: service.Name, Status: status, Detail: detail,
		})
	}
	return report
}

func allFailed(doc Document, detail string) StatusReport {
	report := StatusReport{Revision: doc.Revision}
	for _, service := range doc.Services {
		report.Services = append(report.Services, ServiceStatus{
			Name: service.Name, Status: StatusFailed, Detail: detail,
		})
	}
	return report
}
