package desiredstate

import (
	"context"
	"crypto/sha256"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const HostAdmissionRoot = "/var/lib/livepeer-resource-admission/v1"

var (
	hostAdmissionDomainRE = regexp.MustCompile(`^[a-f0-9]{24}$`)
	hostAdmissionSuffixRE = regexp.MustCompile(`^\.[A-Za-z0-9][A-Za-z0-9._-]{0,31}$`)
)

// Runner is the side-effecting half — writing the compose file and
// driving docker. It is an interface so the reconcile logic can be
// tested without a docker daemon, and so a dry run is a real mode
// rather than a code path nobody exercises.
type Runner interface {
	WriteCompose(path, content string) error
	Pull(ctx context.Context, path string) error
	Up(ctx context.Context, path string) error
}

// ComposeRunner drives the real docker compose.
type ComposeRunner struct {
	// Binary and Args let a host that uses `docker-compose` or a
	// wrapper say so rather than being told what its docker is called.
	Binary string
	Args   []string
}

func (r ComposeRunner) binary() (string, []string) {
	if strings.TrimSpace(r.Binary) != "" {
		return r.Binary, r.Args
	}
	return "docker", []string{"compose"}
}

func (r ComposeRunner) WriteCompose(path, content string) error {
	if dir := filepath.Dir(path); dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}
	// Written whole and replaced atomically: a compose file caught
	// half-written by a concurrent `docker compose up` is a host that
	// stops serving for reasons nobody can reconstruct.
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

func (r ComposeRunner) Pull(ctx context.Context, path string) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if strings.Contains(string(raw), "\nservices: {}\n") {
		return nil
	}
	return r.run(ctx, path, "pull")
}

// Up removes orphans, so a service the pool withdrew and the agent has
// already drained actually stops rather than lingering.
func (r ComposeRunner) Up(ctx context.Context, path string) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if strings.Contains(string(raw), "\nservices: {}\n") {
		return r.run(ctx, path, "down", "--remove-orphans")
	}
	return r.run(ctx, path, "up", "-d", "--remove-orphans")
}

func (r ComposeRunner) run(ctx context.Context, path string, args ...string) error {
	binary, prefix := r.binary()
	full := append(append([]string{}, prefix...), "-f", path)
	full = append(full, args...)
	cmd := exec.CommandContext(ctx, binary, full...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s %s: %w: %s", binary, strings.Join(full, " "), err, strings.TrimSpace(string(out)))
	}
	return nil
}

// RenderCompose assembles the services into one compose file.
//
// A draining service is still rendered. The pool wants it gone, but the
// broker is still finishing work on it, so it stays up until the drain
// completes — dropping it here would kill it mid-request.
func RenderCompose(doc Document) string {
	var b strings.Builder
	b.WriteString("# Generated by pool-member-agent. Do not edit.\n")
	b.WriteString("# Revision: " + doc.Revision + "\n")
	if doc.EnrollmentID != "" {
		sum := sha256.Sum256([]byte(doc.EnrollmentID))
		id := fmt.Sprintf("%x", sum[:8])
		b.WriteString("name: livepeer-runners-" + id + "\n")
		b.WriteString("networks:\n  default:\n    external: true\n    name: livepeer-member-" + id + "\n")
	}
	if len(doc.Services) == 0 {
		b.WriteString("services: {}\n")
	} else {
		b.WriteString("services:\n")
	}
	services := append([]Service(nil), doc.Services...)
	sort.Slice(services, func(i, j int) bool { return services[i].Name < services[j].Name })
	for _, service := range services {
		fragment := service.ComposeFragment
		if !strings.HasSuffix(fragment, "\n") {
			fragment += "\n"
		}
		b.WriteString(fragment)
	}
	return b.String()
}

// Apply makes the host match the document and reports what happened.
//
// The report is built from what was attempted, not from what was asked
// for: a service the pool wants and this host could not start must come
// back as failed, because the pool's next decision depends on knowing
// the difference.
func Apply(ctx context.Context, runner Runner, composePath string, doc Document) StatusReport {
	return applyWithAdmissionRoot(ctx, runner, composePath, doc, HostAdmissionRoot)
}

func applyWithAdmissionRoot(ctx context.Context, runner Runner, composePath string, doc Document, admissionRoot string) StatusReport {
	report := StatusReport{Revision: doc.Revision}
	if err := prepareHostAdmissions(doc, admissionRoot); err != nil {
		return allFailed(doc, "prepare host admission: "+err.Error())
	}
	content := RenderCompose(doc)
	if err := runner.WriteCompose(composePath, content); err != nil {
		return allFailed(doc, "write compose: "+err.Error())
	}
	// Pull first and separately: an image that will not download is a
	// different failure from one that will not start, and rolling them
	// together would report the wrong one.
	if err := runner.Pull(ctx, composePath); err != nil {
		return allFailed(doc, "pull: "+err.Error())
	}
	if err := runner.Up(ctx, composePath); err != nil {
		return allFailed(doc, "compose up: "+err.Error())
	}
	for _, service := range doc.Services {
		status := StatusRunning
		detail := ""
		if service.Draining {
			// The container is up, but the pool has withdrawn it and
			// the broker has been told to stop dispatching. Reporting
			// it as running would keep the assignment alive forever.
			status = StatusStopped
			detail = "draining"
		}
		report.Services = append(report.Services, ServiceStatus{
			Name: service.Name, Status: status, Detail: detail,
		})
	}
	return report
}

// prepareHostAdmissions creates each declared lock file once and preserves
// its inode forever. The generated compose mounts the directory read-only and
// overlays the declared files read-write, so a runner can flock them but
// cannot replace the mount points or invent an unprotected alias.
func prepareHostAdmissions(doc Document, root string) error {
	hasAdmission := false
	for _, service := range doc.Services {
		if service.HostAdmission != nil {
			hasAdmission = true
			break
		}
	}
	if !hasAdmission {
		return nil
	}
	root = filepath.Clean(root)
	if !filepath.IsAbs(root) {
		return fmt.Errorf("admission root %q is not absolute", root)
	}
	if err := ensureDirectory(root, 0o755); err != nil {
		return fmt.Errorf("root: %w", err)
	}
	for _, service := range doc.Services {
		a := service.HostAdmission
		if a == nil {
			continue
		}
		if a.Mechanism != "flock-files/v1" || a.Scope != "hardware-unit" {
			return fmt.Errorf("service %s has unsupported admission %q/%q", service.Name, a.Mechanism, a.Scope)
		}
		if !hostAdmissionDomainRE.MatchString(a.DomainID) {
			return fmt.Errorf("service %s has unsafe admission domain %q", service.Name, a.DomainID)
		}
		dir := filepath.Join(root, a.DomainID)
		wantBase := filepath.Join(dir, "lock")
		if a.BasePath != wantBase {
			return fmt.Errorf("service %s admission base %q does not match domain %q", service.Name, a.BasePath, wantBase)
		}
		if len(a.FileSuffixes) == 0 || len(a.FileSuffixes) > 16 {
			return fmt.Errorf("service %s admission suffix count is invalid", service.Name)
		}
		if err := ensureDirectory(dir, 0o755); err != nil {
			return fmt.Errorf("service %s domain: %w", service.Name, err)
		}
		seen := make(map[string]bool, len(a.FileSuffixes))
		for _, suffix := range a.FileSuffixes {
			if !hostAdmissionSuffixRE.MatchString(suffix) || seen[suffix] {
				return fmt.Errorf("service %s has unsafe or duplicate admission suffix %q", service.Name, suffix)
			}
			seen[suffix] = true
			if err := ensureLockFile(wantBase + suffix); err != nil {
				return fmt.Errorf("service %s lock %s: %w", service.Name, suffix, err)
			}
		}
		if err := os.Chmod(dir, 0o555); err != nil {
			return fmt.Errorf("service %s protect domain: %w", service.Name, err)
		}
	}
	return nil
}

func ensureDirectory(path string, mode os.FileMode) error {
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		if err := os.MkdirAll(path, mode); err != nil {
			return err
		}
		info, err = os.Lstat(path)
	}
	if err != nil {
		return err
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
		return fmt.Errorf("%s is not a real directory", path)
	}
	return nil
}

func ensureLockFile(path string) error {
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		file, createErr := os.OpenFile(path, os.O_CREATE|os.O_EXCL|os.O_RDWR, 0o666)
		if createErr != nil {
			return createErr
		}
		if closeErr := file.Close(); closeErr != nil {
			return closeErr
		}
		info, err = os.Lstat(path)
	}
	if err != nil {
		return err
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
		return fmt.Errorf("%s is not a regular file", path)
	}
	return os.Chmod(path, 0o666)
}

func allFailed(doc Document, detail string) StatusReport {
	report := StatusReport{Revision: doc.Revision}
	for _, service := range doc.Services {
		report.Services = append(report.Services, ServiceStatus{
			Name: service.Name, Status: StatusFailed, Detail: detail,
		})
	}
	return report
}
