// Livepeer Payments v1 — PayeeAdmin service.
//
// Operator-only maintenance RPCs for the receiver-side payment daemon.
// Mounted only in receiver mode.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: livepeer/payments/v1/payee_admin.proto

package paymentsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PayeeAdmin_ResetSession_FullMethodName = "/livepeer.payments.v1.PayeeAdmin/ResetSession"
)

// PayeeAdminClient is the client API for PayeeAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PayeeAdminClient interface {
	// Reset the active GetTicketParams session keyed by the stable
	// sender/recipient/capability/offering identity. The current open
	// session is marked closed, its recipientRand nonce ledger is
	// dropped, and the next GetTicketParams call mints a fresh work_id.
	ResetSession(ctx context.Context, in *ResetSessionRequest, opts ...grpc.CallOption) (*ResetSessionResponse, error)
}

type payeeAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewPayeeAdminClient(cc grpc.ClientConnInterface) PayeeAdminClient {
	return &payeeAdminClient{cc}
}

func (c *payeeAdminClient) ResetSession(ctx context.Context, in *ResetSessionRequest, opts ...grpc.CallOption) (*ResetSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetSessionResponse)
	err := c.cc.Invoke(ctx, PayeeAdmin_ResetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayeeAdminServer is the server API for PayeeAdmin service.
// All implementations must embed UnimplementedPayeeAdminServer
// for forward compatibility.
type PayeeAdminServer interface {
	// Reset the active GetTicketParams session keyed by the stable
	// sender/recipient/capability/offering identity. The current open
	// session is marked closed, its recipientRand nonce ledger is
	// dropped, and the next GetTicketParams call mints a fresh work_id.
	ResetSession(context.Context, *ResetSessionRequest) (*ResetSessionResponse, error)
	mustEmbedUnimplementedPayeeAdminServer()
}

// UnimplementedPayeeAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPayeeAdminServer struct{}

func (UnimplementedPayeeAdminServer) ResetSession(context.Context, *ResetSessionRequest) (*ResetSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetSession not implemented")
}
func (UnimplementedPayeeAdminServer) mustEmbedUnimplementedPayeeAdminServer() {}
func (UnimplementedPayeeAdminServer) testEmbeddedByValue()                    {}

// UnsafePayeeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PayeeAdminServer will
// result in compilation errors.
type UnsafePayeeAdminServer interface {
	mustEmbedUnimplementedPayeeAdminServer()
}

func RegisterPayeeAdminServer(s grpc.ServiceRegistrar, srv PayeeAdminServer) {
	// If the following call panics, it indicates UnimplementedPayeeAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PayeeAdmin_ServiceDesc, srv)
}

func _PayeeAdmin_ResetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayeeAdminServer).ResetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayeeAdmin_ResetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayeeAdminServer).ResetSession(ctx, req.(*ResetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PayeeAdmin_ServiceDesc is the grpc.ServiceDesc for PayeeAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PayeeAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "livepeer.payments.v1.PayeeAdmin",
	HandlerType: (*PayeeAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResetSession",
			Handler:    _PayeeAdmin_ResetSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "livepeer/payments/v1/payee_admin.proto",
}
