// Livepeer Payments v1 — PayerDaemon service.
//
// The PayerDaemon runs next to a payer application — a Livepeer gateway
// or any consumer app paying an orchestrator. It creates and signs
// tickets, manages per-session sender nonces, and watches the payer's
// on-chain escrow.
//
// Mounted only when the daemon is started with `--mode=sender`. Calls
// to it in receiver mode return UNIMPLEMENTED.
//
// This service is NOT part of the wire-compat contract; it is a
// daemon↔consumer-app contract that may evolve under v1. See
// `../docs/wire-compat.md`.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: livepeer/payments/v1/payer_daemon.proto

package paymentsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PayerDaemon_CreatePayment_FullMethodName    = "/livepeer.payments.v1.PayerDaemon/CreatePayment"
	PayerDaemon_GetDepositInfo_FullMethodName   = "/livepeer.payments.v1.PayerDaemon/GetDepositInfo"
	PayerDaemon_GetSessionDebits_FullMethodName = "/livepeer.payments.v1.PayerDaemon/GetSessionDebits"
	PayerDaemon_Health_FullMethodName           = "/livepeer.payments.v1.PayerDaemon/Health"
)

// PayerDaemonClient is the client API for PayerDaemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PayerDaemonClient interface {
	// Create a payment blob (a `Payment` carrying one or more tickets)
	// for a selected payee identity at a target spend.
	//
	// On the quote-free sender path, the daemon:
	//  1. Resolves a worker URL for `recipient` (via the local resolver
	//     or a configured override).
	//  2. POSTs `(sender, recipient, face_value, capability, offering)`
	//     to the worker's `/v1/payment/ticket-params` endpoint.
	//  3. Receives canonical `TicketParams` back.
	//  4. Validates against sender escrow / EV caps.
	//  5. Signs a one-ticket `Payment`.
	//
	// The `face_value` argument is interpreted as the caller's TARGET
	// SPEND (expected value), not a mandatory winning-ticket size. The
	// receiver may answer with a larger `TicketParams.face_value` plus a
	// lower `TicketParams.win_prob` when redemption economics require a
	// redeemable ticket. Senders MUST treat the response `TicketParams`
	// as the source of truth and not assume the returned `face_value`
	// equals the requested face_value.
	CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error)
	// Inspect the payer's current TicketBroker deposit / reserve state.
	// Read-only; the daemon does not fund escrow.
	GetDepositInfo(ctx context.Context, in *GetDepositInfoRequest, opts ...grpc.CallOption) (*GetDepositInfoResponse, error)
	// Read the per-session debit ledger for a long-lived session
	// (`ws-realtime@v0`, `session-control-plus-media@v0`, etc.). Used by
	// gateway adapters at session-close time to surface a final
	// `Livepeer-Work-Units` count to the gateway caller without adding a
	// close-frame extension or a control-plane event. The daemon may
	// return UNIMPLEMENTED when long-lived debit tracking is not wired
	// (the gateway-side adapter treats UNIMPLEMENTED as "0 work units,
	// best effort"). The actual debit-pushdown from the broker-side
	// ticker lands with plan 0015.
	GetSessionDebits(ctx context.Context, in *GetSessionDebitsRequest, opts ...grpc.CallOption) (*GetSessionDebitsResponse, error)
	// Health returns "ok" if the daemon is ready to mint payments. The
	// gateway calls this once at startup.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type payerDaemonClient struct {
	cc grpc.ClientConnInterface
}

func NewPayerDaemonClient(cc grpc.ClientConnInterface) PayerDaemonClient {
	return &payerDaemonClient{cc}
}

func (c *payerDaemonClient) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentResponse)
	err := c.cc.Invoke(ctx, PayerDaemon_CreatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payerDaemonClient) GetDepositInfo(ctx context.Context, in *GetDepositInfoRequest, opts ...grpc.CallOption) (*GetDepositInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDepositInfoResponse)
	err := c.cc.Invoke(ctx, PayerDaemon_GetDepositInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payerDaemonClient) GetSessionDebits(ctx context.Context, in *GetSessionDebitsRequest, opts ...grpc.CallOption) (*GetSessionDebitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionDebitsResponse)
	err := c.cc.Invoke(ctx, PayerDaemon_GetSessionDebits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payerDaemonClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PayerDaemon_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayerDaemonServer is the server API for PayerDaemon service.
// All implementations must embed UnimplementedPayerDaemonServer
// for forward compatibility.
type PayerDaemonServer interface {
	// Create a payment blob (a `Payment` carrying one or more tickets)
	// for a selected payee identity at a target spend.
	//
	// On the quote-free sender path, the daemon:
	//  1. Resolves a worker URL for `recipient` (via the local resolver
	//     or a configured override).
	//  2. POSTs `(sender, recipient, face_value, capability, offering)`
	//     to the worker's `/v1/payment/ticket-params` endpoint.
	//  3. Receives canonical `TicketParams` back.
	//  4. Validates against sender escrow / EV caps.
	//  5. Signs a one-ticket `Payment`.
	//
	// The `face_value` argument is interpreted as the caller's TARGET
	// SPEND (expected value), not a mandatory winning-ticket size. The
	// receiver may answer with a larger `TicketParams.face_value` plus a
	// lower `TicketParams.win_prob` when redemption economics require a
	// redeemable ticket. Senders MUST treat the response `TicketParams`
	// as the source of truth and not assume the returned `face_value`
	// equals the requested face_value.
	CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error)
	// Inspect the payer's current TicketBroker deposit / reserve state.
	// Read-only; the daemon does not fund escrow.
	GetDepositInfo(context.Context, *GetDepositInfoRequest) (*GetDepositInfoResponse, error)
	// Read the per-session debit ledger for a long-lived session
	// (`ws-realtime@v0`, `session-control-plus-media@v0`, etc.). Used by
	// gateway adapters at session-close time to surface a final
	// `Livepeer-Work-Units` count to the gateway caller without adding a
	// close-frame extension or a control-plane event. The daemon may
	// return UNIMPLEMENTED when long-lived debit tracking is not wired
	// (the gateway-side adapter treats UNIMPLEMENTED as "0 work units,
	// best effort"). The actual debit-pushdown from the broker-side
	// ticker lands with plan 0015.
	GetSessionDebits(context.Context, *GetSessionDebitsRequest) (*GetSessionDebitsResponse, error)
	// Health returns "ok" if the daemon is ready to mint payments. The
	// gateway calls this once at startup.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedPayerDaemonServer()
}

// UnimplementedPayerDaemonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPayerDaemonServer struct{}

func (UnimplementedPayerDaemonServer) CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedPayerDaemonServer) GetDepositInfo(context.Context, *GetDepositInfoRequest) (*GetDepositInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDepositInfo not implemented")
}
func (UnimplementedPayerDaemonServer) GetSessionDebits(context.Context, *GetSessionDebitsRequest) (*GetSessionDebitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionDebits not implemented")
}
func (UnimplementedPayerDaemonServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPayerDaemonServer) mustEmbedUnimplementedPayerDaemonServer() {}
func (UnimplementedPayerDaemonServer) testEmbeddedByValue()                     {}

// UnsafePayerDaemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PayerDaemonServer will
// result in compilation errors.
type UnsafePayerDaemonServer interface {
	mustEmbedUnimplementedPayerDaemonServer()
}

func RegisterPayerDaemonServer(s grpc.ServiceRegistrar, srv PayerDaemonServer) {
	// If the following call panics, it indicates UnimplementedPayerDaemonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PayerDaemon_ServiceDesc, srv)
}

func _PayerDaemon_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayerDaemonServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayerDaemon_CreatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayerDaemonServer).CreatePayment(ctx, req.(*CreatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayerDaemon_GetDepositInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepositInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayerDaemonServer).GetDepositInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayerDaemon_GetDepositInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayerDaemonServer).GetDepositInfo(ctx, req.(*GetDepositInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayerDaemon_GetSessionDebits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionDebitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayerDaemonServer).GetSessionDebits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayerDaemon_GetSessionDebits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayerDaemonServer).GetSessionDebits(ctx, req.(*GetSessionDebitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayerDaemon_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayerDaemonServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayerDaemon_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayerDaemonServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PayerDaemon_ServiceDesc is the grpc.ServiceDesc for PayerDaemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PayerDaemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "livepeer.payments.v1.PayerDaemon",
	HandlerType: (*PayerDaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePayment",
			Handler:    _PayerDaemon_CreatePayment_Handler,
		},
		{
			MethodName: "GetDepositInfo",
			Handler:    _PayerDaemon_GetDepositInfo_Handler,
		},
		{
			MethodName: "GetSessionDebits",
			Handler:    _PayerDaemon_GetSessionDebits_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _PayerDaemon_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "livepeer/payments/v1/payer_daemon.proto",
}
