// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: livepeer/payments/v1/session_revision.proto

package paymentsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionRevisionRecord_Outcome int32

const (
	SessionRevisionRecord_OUTCOME_UNSPECIFIED SessionRevisionRecord_Outcome = 0
	SessionRevisionRecord_ADMITTED            SessionRevisionRecord_Outcome = 1
	SessionRevisionRecord_NOT_ADMITTED        SessionRevisionRecord_Outcome = 2
)

// Enum value maps for SessionRevisionRecord_Outcome.
var (
	SessionRevisionRecord_Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "ADMITTED",
		2: "NOT_ADMITTED",
	}
	SessionRevisionRecord_Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED": 0,
		"ADMITTED":            1,
		"NOT_ADMITTED":        2,
	}
)

func (x SessionRevisionRecord_Outcome) Enum() *SessionRevisionRecord_Outcome {
	p := new(SessionRevisionRecord_Outcome)
	*p = x
	return p
}

func (x SessionRevisionRecord_Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionRevisionRecord_Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_livepeer_payments_v1_session_revision_proto_enumTypes[0].Descriptor()
}

func (SessionRevisionRecord_Outcome) Type() protoreflect.EnumType {
	return &file_livepeer_payments_v1_session_revision_proto_enumTypes[0]
}

func (x SessionRevisionRecord_Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionRevisionRecord_Outcome.Descriptor instead.
func (SessionRevisionRecord_Outcome) EnumDescriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_session_revision_proto_rawDescGZIP(), []int{0, 0}
}

// Immutable broker observation, signed with the delegated settlement key using
// the settlement JCS envelope. It does not settle the logical session. Consumers
// MUST compare every identity, domain, quote and authorization hash with their
// own issued grant. Claimed authorization scope does not attest signature validity.
type SessionRevisionRecord struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WholesaleAccountId string                 `protobuf:"bytes,23,opt,name=wholesale_account_id,json=wholesaleAccountId,proto3" json:"wholesale_account_id,omitempty"`
	// Always "livepeer-session-revision/v1"; prevents cross-purpose replay.
	EvidenceDomain             string                        `protobuf:"bytes,1,opt,name=evidence_domain,json=evidenceDomain,proto3" json:"evidence_domain,omitempty"`
	Protocol                   string                        `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"` // Always "paid-session/v1".
	SettlementDomainId         string                        `protobuf:"bytes,3,opt,name=settlement_domain_id,json=settlementDomainId,proto3" json:"settlement_domain_id,omitempty"`
	BrokerUri                  string                        `protobuf:"bytes,4,opt,name=broker_uri,json=brokerUri,proto3" json:"broker_uri,omitempty"`
	SessionId                  string                        `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GatewaySessionId           string                        `protobuf:"bytes,6,opt,name=gateway_session_id,json=gatewaySessionId,proto3" json:"gateway_session_id,omitempty"`
	RequestId                  string                        `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Payer                      []byte                        `protobuf:"bytes,8,opt,name=payer,proto3" json:"payer,omitempty"`
	Payee                      []byte                        `protobuf:"bytes,9,opt,name=payee,proto3" json:"payee,omitempty"`
	AuthorizationId            string                        `protobuf:"bytes,10,opt,name=authorization_id,json=authorizationId,proto3" json:"authorization_id,omitempty"`
	PredecessorAuthorizationId string                        `protobuf:"bytes,11,opt,name=predecessor_authorization_id,json=predecessorAuthorizationId,proto3" json:"predecessor_authorization_id,omitempty"`
	Revision                   uint64                        `protobuf:"varint,12,opt,name=revision,proto3" json:"revision,omitempty"`
	AuthorizationFingerprint   []byte                        `protobuf:"bytes,13,opt,name=authorization_fingerprint,json=authorizationFingerprint,proto3" json:"authorization_fingerprint,omitempty"` // SHA-256 of exact signed wire bytes.
	AcceptedQuoteRef           *QuoteRef                     `protobuf:"bytes,14,opt,name=accepted_quote_ref,json=acceptedQuoteRef,proto3" json:"accepted_quote_ref,omitempty"`
	Outcome                    SessionRevisionRecord_Outcome `protobuf:"varint,15,opt,name=outcome,proto3,enum=livepeer.payments.v1.SessionRevisionRecord_Outcome" json:"outcome,omitempty"`
	// NOT_ADMITTED requires "receiver_fenced" or "expired_unused".
	// An error, timeout, gateway assertion or missing record is insufficient.
	NonAdmissionBasis string   `protobuf:"bytes,16,opt,name=non_admission_basis,json=nonAdmissionBasis,proto3" json:"non_admission_basis,omitempty"`
	Reason            string   `protobuf:"bytes,17,opt,name=reason,proto3" json:"reason,omitempty"` // Allowlisted diagnostic code; never controls accounting.
	Stage             string   `protobuf:"bytes,18,opt,name=stage,proto3" json:"stage,omitempty"`
	ReceiverCode      string   `protobuf:"bytes,19,opt,name=receiver_code,json=receiverCode,proto3" json:"receiver_code,omitempty"`
	ObservedAt        string   `protobuf:"bytes,20,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"` // RFC3339Nano; immutable across lookups and retries.
	MaxTotalUnits     uint64   `protobuf:"varint,21,opt,name=max_total_units,json=maxTotalUnits,proto3" json:"max_total_units,omitempty"`
	MaxDebitWei       *BigUInt `protobuf:"bytes,22,opt,name=max_debit_wei,json=maxDebitWei,proto3" json:"max_debit_wei,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionRevisionRecord) Reset() {
	*x = SessionRevisionRecord{}
	mi := &file_livepeer_payments_v1_session_revision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRevisionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRevisionRecord) ProtoMessage() {}

func (x *SessionRevisionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_session_revision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRevisionRecord.ProtoReflect.Descriptor instead.
func (*SessionRevisionRecord) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_session_revision_proto_rawDescGZIP(), []int{0}
}

func (x *SessionRevisionRecord) GetWholesaleAccountId() string {
	if x != nil {
		return x.WholesaleAccountId
	}
	return ""
}

func (x *SessionRevisionRecord) GetEvidenceDomain() string {
	if x != nil {
		return x.EvidenceDomain
	}
	return ""
}

func (x *SessionRevisionRecord) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *SessionRevisionRecord) GetSettlementDomainId() string {
	if x != nil {
		return x.SettlementDomainId
	}
	return ""
}

func (x *SessionRevisionRecord) GetBrokerUri() string {
	if x != nil {
		return x.BrokerUri
	}
	return ""
}

func (x *SessionRevisionRecord) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionRevisionRecord) GetGatewaySessionId() string {
	if x != nil {
		return x.GatewaySessionId
	}
	return ""
}

func (x *SessionRevisionRecord) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SessionRevisionRecord) GetPayer() []byte {
	if x != nil {
		return x.Payer
	}
	return nil
}

func (x *SessionRevisionRecord) GetPayee() []byte {
	if x != nil {
		return x.Payee
	}
	return nil
}

func (x *SessionRevisionRecord) GetAuthorizationId() string {
	if x != nil {
		return x.AuthorizationId
	}
	return ""
}

func (x *SessionRevisionRecord) GetPredecessorAuthorizationId() string {
	if x != nil {
		return x.PredecessorAuthorizationId
	}
	return ""
}

func (x *SessionRevisionRecord) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *SessionRevisionRecord) GetAuthorizationFingerprint() []byte {
	if x != nil {
		return x.AuthorizationFingerprint
	}
	return nil
}

func (x *SessionRevisionRecord) GetAcceptedQuoteRef() *QuoteRef {
	if x != nil {
		return x.AcceptedQuoteRef
	}
	return nil
}

func (x *SessionRevisionRecord) GetOutcome() SessionRevisionRecord_Outcome {
	if x != nil {
		return x.Outcome
	}
	return SessionRevisionRecord_OUTCOME_UNSPECIFIED
}

func (x *SessionRevisionRecord) GetNonAdmissionBasis() string {
	if x != nil {
		return x.NonAdmissionBasis
	}
	return ""
}

func (x *SessionRevisionRecord) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SessionRevisionRecord) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *SessionRevisionRecord) GetReceiverCode() string {
	if x != nil {
		return x.ReceiverCode
	}
	return ""
}

func (x *SessionRevisionRecord) GetObservedAt() string {
	if x != nil {
		return x.ObservedAt
	}
	return ""
}

func (x *SessionRevisionRecord) GetMaxTotalUnits() uint64 {
	if x != nil {
		return x.MaxTotalUnits
	}
	return 0
}

func (x *SessionRevisionRecord) GetMaxDebitWei() *BigUInt {
	if x != nil {
		return x.MaxDebitWei
	}
	return nil
}

var File_livepeer_payments_v1_session_revision_proto protoreflect.FileDescriptor

const file_livepeer_payments_v1_session_revision_proto_rawDesc = "" +
	"\n" +
	"+livepeer/payments/v1/session_revision.proto\x12\x14livepeer.payments.v1\x1a livepeer/payments/v1/types.proto\"\xad\b\n" +
	"\x15SessionRevisionRecord\x120\n" +
	"\x14wholesale_account_id\x18\x17 \x01(\tR\x12wholesaleAccountId\x12'\n" +
	"\x0fevidence_domain\x18\x01 \x01(\tR\x0eevidenceDomain\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x120\n" +
	"\x14settlement_domain_id\x18\x03 \x01(\tR\x12settlementDomainId\x12\x1d\n" +
	"\n" +
	"broker_uri\x18\x04 \x01(\tR\tbrokerUri\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12,\n" +
	"\x12gateway_session_id\x18\x06 \x01(\tR\x10gatewaySessionId\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\x12\x14\n" +
	"\x05payer\x18\b \x01(\fR\x05payer\x12\x14\n" +
	"\x05payee\x18\t \x01(\fR\x05payee\x12)\n" +
	"\x10authorization_id\x18\n" +
	" \x01(\tR\x0fauthorizationId\x12@\n" +
	"\x1cpredecessor_authorization_id\x18\v \x01(\tR\x1apredecessorAuthorizationId\x12\x1a\n" +
	"\brevision\x18\f \x01(\x04R\brevision\x12;\n" +
	"\x19authorization_fingerprint\x18\r \x01(\fR\x18authorizationFingerprint\x12L\n" +
	"\x12accepted_quote_ref\x18\x0e \x01(\v2\x1e.livepeer.payments.v1.QuoteRefR\x10acceptedQuoteRef\x12M\n" +
	"\aoutcome\x18\x0f \x01(\x0e23.livepeer.payments.v1.SessionRevisionRecord.OutcomeR\aoutcome\x12.\n" +
	"\x13non_admission_basis\x18\x10 \x01(\tR\x11nonAdmissionBasis\x12\x16\n" +
	"\x06reason\x18\x11 \x01(\tR\x06reason\x12\x14\n" +
	"\x05stage\x18\x12 \x01(\tR\x05stage\x12#\n" +
	"\rreceiver_code\x18\x13 \x01(\tR\freceiverCode\x12\x1f\n" +
	"\vobserved_at\x18\x14 \x01(\tR\n" +
	"observedAt\x12&\n" +
	"\x0fmax_total_units\x18\x15 \x01(\x04R\rmaxTotalUnits\x12A\n" +
	"\rmax_debit_wei\x18\x16 \x01(\v2\x1d.livepeer.payments.v1.BigUIntR\vmaxDebitWei\"B\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bADMITTED\x10\x01\x12\x10\n" +
	"\fNOT_ADMITTED\x10\x02BrZpgithub.com/Cloud-SPE/livepeer-network-modules/livepeer-network-protocol/proto-go/livepeer/payments/v1;paymentsv1b\x06proto3"

var (
	file_livepeer_payments_v1_session_revision_proto_rawDescOnce sync.Once
	file_livepeer_payments_v1_session_revision_proto_rawDescData []byte
)

func file_livepeer_payments_v1_session_revision_proto_rawDescGZIP() []byte {
	file_livepeer_payments_v1_session_revision_proto_rawDescOnce.Do(func() {
		file_livepeer_payments_v1_session_revision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_livepeer_payments_v1_session_revision_proto_rawDesc), len(file_livepeer_payments_v1_session_revision_proto_rawDesc)))
	})
	return file_livepeer_payments_v1_session_revision_proto_rawDescData
}

var file_livepeer_payments_v1_session_revision_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_livepeer_payments_v1_session_revision_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_livepeer_payments_v1_session_revision_proto_goTypes = []any{
	(SessionRevisionRecord_Outcome)(0), // 0: livepeer.payments.v1.SessionRevisionRecord.Outcome
	(*SessionRevisionRecord)(nil),      // 1: livepeer.payments.v1.SessionRevisionRecord
	(*QuoteRef)(nil),                   // 2: livepeer.payments.v1.QuoteRef
	(*BigUInt)(nil),                    // 3: livepeer.payments.v1.BigUInt
}
var file_livepeer_payments_v1_session_revision_proto_depIdxs = []int32{
	2, // 0: livepeer.payments.v1.SessionRevisionRecord.accepted_quote_ref:type_name -> livepeer.payments.v1.QuoteRef
	0, // 1: livepeer.payments.v1.SessionRevisionRecord.outcome:type_name -> livepeer.payments.v1.SessionRevisionRecord.Outcome
	3, // 2: livepeer.payments.v1.SessionRevisionRecord.max_debit_wei:type_name -> livepeer.payments.v1.BigUInt
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_livepeer_payments_v1_session_revision_proto_init() }
func file_livepeer_payments_v1_session_revision_proto_init() {
	if File_livepeer_payments_v1_session_revision_proto != nil {
		return
	}
	file_livepeer_payments_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_livepeer_payments_v1_session_revision_proto_rawDesc), len(file_livepeer_payments_v1_session_revision_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_livepeer_payments_v1_session_revision_proto_goTypes,
		DependencyIndexes: file_livepeer_payments_v1_session_revision_proto_depIdxs,
		EnumInfos:         file_livepeer_payments_v1_session_revision_proto_enumTypes,
		MessageInfos:      file_livepeer_payments_v1_session_revision_proto_msgTypes,
	}.Build()
	File_livepeer_payments_v1_session_revision_proto = out.File
	file_livepeer_payments_v1_session_revision_proto_goTypes = nil
	file_livepeer_payments_v1_session_revision_proto_depIdxs = nil
}
