// Livepeer Payments v1 — wire-format types.
//
// These messages are a wire-compatible re-declaration of the
// payment-relevant portion of go-livepeer's `net/lp_rpc.proto`. Field
// numbers and wire types are preserved byte-for-byte so that
// `livepeer.payments.v1.Payment` encodes identically to `net.Payment`
// from go-livepeer.
//
// See `../docs/wire-compat.md` for the byte-for-byte invariant and the
// round-trip test that enforces it.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: livepeer/payments/v1/types.proto

package paymentsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpendAuthorizationState int32

const (
	SpendAuthorizationState_SPEND_AUTHORIZATION_STATE_UNSPECIFIED SpendAuthorizationState = 0
	SpendAuthorizationState_SPEND_AUTHORIZATION_ISSUED            SpendAuthorizationState = 1
	SpendAuthorizationState_SPEND_AUTHORIZATION_ADMITTED          SpendAuthorizationState = 2
	SpendAuthorizationState_SPEND_AUTHORIZATION_SETTLED           SpendAuthorizationState = 3
	SpendAuthorizationState_SPEND_AUTHORIZATION_EXPIRED_UNUSED    SpendAuthorizationState = 4
	SpendAuthorizationState_SPEND_AUTHORIZATION_OUTCOME_UNKNOWN   SpendAuthorizationState = 5
	SpendAuthorizationState_SPEND_AUTHORIZATION_SUPERSEDED        SpendAuthorizationState = 6
)

// Enum value maps for SpendAuthorizationState.
var (
	SpendAuthorizationState_name = map[int32]string{
		0: "SPEND_AUTHORIZATION_STATE_UNSPECIFIED",
		1: "SPEND_AUTHORIZATION_ISSUED",
		2: "SPEND_AUTHORIZATION_ADMITTED",
		3: "SPEND_AUTHORIZATION_SETTLED",
		4: "SPEND_AUTHORIZATION_EXPIRED_UNUSED",
		5: "SPEND_AUTHORIZATION_OUTCOME_UNKNOWN",
		6: "SPEND_AUTHORIZATION_SUPERSEDED",
	}
	SpendAuthorizationState_value = map[string]int32{
		"SPEND_AUTHORIZATION_STATE_UNSPECIFIED": 0,
		"SPEND_AUTHORIZATION_ISSUED":            1,
		"SPEND_AUTHORIZATION_ADMITTED":          2,
		"SPEND_AUTHORIZATION_SETTLED":           3,
		"SPEND_AUTHORIZATION_EXPIRED_UNUSED":    4,
		"SPEND_AUTHORIZATION_OUTCOME_UNKNOWN":   5,
		"SPEND_AUTHORIZATION_SUPERSEDED":        6,
	}
)

func (x SpendAuthorizationState) Enum() *SpendAuthorizationState {
	p := new(SpendAuthorizationState)
	*p = x
	return p
}

func (x SpendAuthorizationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpendAuthorizationState) Descriptor() protoreflect.EnumDescriptor {
	return file_livepeer_payments_v1_types_proto_enumTypes[0].Descriptor()
}

func (SpendAuthorizationState) Type() protoreflect.EnumType {
	return &file_livepeer_payments_v1_types_proto_enumTypes[0]
}

func (x SpendAuthorizationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpendAuthorizationState.Descriptor instead.
func (SpendAuthorizationState) EnumDescriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{0}
}

// PaymentRejectionReason is the machine-readable reason a payee daemon
// rejected a ticket in ProcessPayment. UNSPECIFIED means the ticket was
// accepted.
type PaymentRejectionReason int32

const (
	PaymentRejectionReason_PAYMENT_REJECTION_REASON_UNSPECIFIED            PaymentRejectionReason = 0
	PaymentRejectionReason_PAYMENT_REJECTION_REASON_INVALID_RECIPIENT_RAND PaymentRejectionReason = 1
	PaymentRejectionReason_PAYMENT_REJECTION_REASON_NONCE_REPLAY           PaymentRejectionReason = 2
	PaymentRejectionReason_PAYMENT_REJECTION_REASON_NONCE_CAP_REACHED      PaymentRejectionReason = 3
	PaymentRejectionReason_PAYMENT_REJECTION_REASON_INVALID_SIGNATURE      PaymentRejectionReason = 4
	PaymentRejectionReason_PAYMENT_REJECTION_REASON_OTHER                  PaymentRejectionReason = 5
)

// Enum value maps for PaymentRejectionReason.
var (
	PaymentRejectionReason_name = map[int32]string{
		0: "PAYMENT_REJECTION_REASON_UNSPECIFIED",
		1: "PAYMENT_REJECTION_REASON_INVALID_RECIPIENT_RAND",
		2: "PAYMENT_REJECTION_REASON_NONCE_REPLAY",
		3: "PAYMENT_REJECTION_REASON_NONCE_CAP_REACHED",
		4: "PAYMENT_REJECTION_REASON_INVALID_SIGNATURE",
		5: "PAYMENT_REJECTION_REASON_OTHER",
	}
	PaymentRejectionReason_value = map[string]int32{
		"PAYMENT_REJECTION_REASON_UNSPECIFIED":            0,
		"PAYMENT_REJECTION_REASON_INVALID_RECIPIENT_RAND": 1,
		"PAYMENT_REJECTION_REASON_NONCE_REPLAY":           2,
		"PAYMENT_REJECTION_REASON_NONCE_CAP_REACHED":      3,
		"PAYMENT_REJECTION_REASON_INVALID_SIGNATURE":      4,
		"PAYMENT_REJECTION_REASON_OTHER":                  5,
	}
)

func (x PaymentRejectionReason) Enum() *PaymentRejectionReason {
	p := new(PaymentRejectionReason)
	*p = x
	return p
}

func (x PaymentRejectionReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentRejectionReason) Descriptor() protoreflect.EnumDescriptor {
	return file_livepeer_payments_v1_types_proto_enumTypes[1].Descriptor()
}

func (PaymentRejectionReason) Type() protoreflect.EnumType {
	return &file_livepeer_payments_v1_types_proto_enumTypes[1]
}

func (x PaymentRejectionReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentRejectionReason.Descriptor instead.
func (PaymentRejectionReason) EnumDescriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{1}
}

type SettlementRecord_SettlementOutcome int32

const (
	SettlementRecord_SETTLEMENT_OUTCOME_UNSPECIFIED SettlementRecord_SettlementOutcome = 0
	SettlementRecord_EXACT                          SettlementRecord_SettlementOutcome = 1
	SettlementRecord_UNDERFUNDED                    SettlementRecord_SettlementOutcome = 2
	SettlementRecord_OVERFUNDED                     SettlementRecord_SettlementOutcome = 3
	SettlementRecord_STOPPED_AT_BUDGET              SettlementRecord_SettlementOutcome = 4
	SettlementRecord_TOPPED_UP                      SettlementRecord_SettlementOutcome = 5
	// Reserved for decoding pre-authorization records. Authorization-only
	// brokers MUST NOT emit a terminal DEBIT_FAILED record: uncertain account
	// settlement remains accounting_pending and retries the same authorization.
	SettlementRecord_DEBIT_FAILED SettlementRecord_SettlementOutcome = 6
)

// Enum value maps for SettlementRecord_SettlementOutcome.
var (
	SettlementRecord_SettlementOutcome_name = map[int32]string{
		0: "SETTLEMENT_OUTCOME_UNSPECIFIED",
		1: "EXACT",
		2: "UNDERFUNDED",
		3: "OVERFUNDED",
		4: "STOPPED_AT_BUDGET",
		5: "TOPPED_UP",
		6: "DEBIT_FAILED",
	}
	SettlementRecord_SettlementOutcome_value = map[string]int32{
		"SETTLEMENT_OUTCOME_UNSPECIFIED": 0,
		"EXACT":                          1,
		"UNDERFUNDED":                    2,
		"OVERFUNDED":                     3,
		"STOPPED_AT_BUDGET":              4,
		"TOPPED_UP":                      5,
		"DEBIT_FAILED":                   6,
	}
)

func (x SettlementRecord_SettlementOutcome) Enum() *SettlementRecord_SettlementOutcome {
	p := new(SettlementRecord_SettlementOutcome)
	*p = x
	return p
}

func (x SettlementRecord_SettlementOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SettlementRecord_SettlementOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_livepeer_payments_v1_types_proto_enumTypes[2].Descriptor()
}

func (SettlementRecord_SettlementOutcome) Type() protoreflect.EnumType {
	return &file_livepeer_payments_v1_types_proto_enumTypes[2]
}

func (x SettlementRecord_SettlementOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SettlementRecord_SettlementOutcome.Descriptor instead.
func (SettlementRecord_SettlementOutcome) EnumDescriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{17, 0}
}

// The outcome. A distinct value on purpose: a zero-unit settlement
// says an exchange happened and cost nothing, which is a different
// claim and one a consumer must not confuse with this.
type NonAdmissionRecord_Outcome int32

const (
	NonAdmissionRecord_OUTCOME_UNSPECIFIED NonAdmissionRecord_Outcome = 0
	NonAdmissionRecord_NOT_ADMITTED        NonAdmissionRecord_Outcome = 1
)

// Enum value maps for NonAdmissionRecord_Outcome.
var (
	NonAdmissionRecord_Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "NOT_ADMITTED",
	}
	NonAdmissionRecord_Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED": 0,
		"NOT_ADMITTED":        1,
	}
)

func (x NonAdmissionRecord_Outcome) Enum() *NonAdmissionRecord_Outcome {
	p := new(NonAdmissionRecord_Outcome)
	*p = x
	return p
}

func (x NonAdmissionRecord_Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NonAdmissionRecord_Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_livepeer_payments_v1_types_proto_enumTypes[3].Descriptor()
}

func (NonAdmissionRecord_Outcome) Type() protoreflect.EnumType {
	return &file_livepeer_payments_v1_types_proto_enumTypes[3]
}

func (x NonAdmissionRecord_Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NonAdmissionRecord_Outcome.Descriptor instead.
func (NonAdmissionRecord_Outcome) EnumDescriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{18, 0}
}

// PriceInfo conveys pricing info for a unit of work.
//
// `pixelsPerUnit` is a historical name; the denominator is really just
// "work units" — pixels, tokens, seconds, characters, anything the
// consumer chooses. For wire compatibility the field name is preserved.
type PriceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Price in wei per `pixels_per_unit` units of work.
	//
	// WIRE COMPAT: the proto field NAME differs from go-livepeer's
	// (`pricePerUnit` vs `price_per_unit`), but the field NUMBER is
	// identical. Proto encoding keys on number, not name, so bytes on
	// the wire are compatible. The Go-generated field name is
	// `PricePerUnit` in both projects.
	PricePerUnit int64 `protobuf:"varint,1,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	// Work units covered by `price_per_unit`. Setting `price_per_unit = 1`
	// with a larger `pixels_per_unit` lets pricing go finer than 1 wei
	// per unit.
	PixelsPerUnit int64 `protobuf:"varint,2,opt,name=pixels_per_unit,json=pixelsPerUnit,proto3" json:"pixels_per_unit,omitempty"`
	// Capability this price applies to (uint32 capability ID, as in
	// go-livepeer). The daemon's RPC surface accepts string capability
	// names and maps them to this uint32 at the boundary.
	Capability uint32 `protobuf:"varint,3,opt,name=capability,proto3" json:"capability,omitempty"`
	// Non-binary constraint this price applies to (e.g., a specific
	// model id).
	Constraint    string `protobuf:"bytes,4,opt,name=constraint,proto3" json:"constraint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceInfo) Reset() {
	*x = PriceInfo{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceInfo) ProtoMessage() {}

func (x *PriceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceInfo.ProtoReflect.Descriptor instead.
func (*PriceInfo) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *PriceInfo) GetPricePerUnit() int64 {
	if x != nil {
		return x.PricePerUnit
	}
	return 0
}

func (x *PriceInfo) GetPixelsPerUnit() int64 {
	if x != nil {
		return x.PixelsPerUnit
	}
	return 0
}

func (x *PriceInfo) GetCapability() uint32 {
	if x != nil {
		return x.Capability
	}
	return 0
}

func (x *PriceInfo) GetConstraint() string {
	if x != nil {
		return x.Constraint
	}
	return ""
}

// TicketParams is the recipient-controlled portion of a ticket. The
// payee issues these to a payer during discovery (via `GetQuote` /
// `GetTicketParams`); the payer uses them verbatim when constructing
// tickets in a `TicketBatch`.
type TicketParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ETH address of the recipient.
	Recipient []byte `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// Payout in wei if the ticket wins. Big-endian bytes.
	FaceValue []byte `protobuf:"bytes,2,opt,name=face_value,json=faceValue,proto3" json:"face_value,omitempty"`
	// Probability the ticket wins, scaled to the 256-bit win-probability
	// field (maxWinProb = 2^256 - 1). Big-endian bytes.
	WinProb []byte `protobuf:"bytes,3,opt,name=win_prob,json=winProb,proto3" json:"win_prob,omitempty"`
	// 32-byte keccak-256 hash commitment to a random number held by the
	// recipient. Used as the session key.
	RecipientRandHash []byte `protobuf:"bytes,4,opt,name=recipient_rand_hash,json=recipientRandHash,proto3" json:"recipient_rand_hash,omitempty"`
	// Seed the recipient uses to derive the random number corresponding
	// to `recipient_rand_hash`. HMAC-derived per (sender, capability,
	// monotonic counter) so seeds cannot collide across senders.
	Seed []byte `protobuf:"bytes,5,opt,name=seed,proto3" json:"seed,omitempty"`
	// L1 block number after which this set of TicketParams is no longer
	// valid. Big-endian bytes.
	ExpirationBlock []byte `protobuf:"bytes,6,opt,name=expiration_block,json=expirationBlock,proto3" json:"expiration_block,omitempty"`
	// Expiration parameters used at ticket-validation time.
	ExpirationParams *TicketExpirationParams `protobuf:"bytes,7,opt,name=expiration_params,json=expirationParams,proto3" json:"expiration_params,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TicketParams) Reset() {
	*x = TicketParams{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketParams) ProtoMessage() {}

func (x *TicketParams) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketParams.ProtoReflect.Descriptor instead.
func (*TicketParams) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *TicketParams) GetRecipient() []byte {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *TicketParams) GetFaceValue() []byte {
	if x != nil {
		return x.FaceValue
	}
	return nil
}

func (x *TicketParams) GetWinProb() []byte {
	if x != nil {
		return x.WinProb
	}
	return nil
}

func (x *TicketParams) GetRecipientRandHash() []byte {
	if x != nil {
		return x.RecipientRandHash
	}
	return nil
}

func (x *TicketParams) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

func (x *TicketParams) GetExpirationBlock() []byte {
	if x != nil {
		return x.ExpirationBlock
	}
	return nil
}

func (x *TicketParams) GetExpirationParams() *TicketExpirationParams {
	if x != nil {
		return x.ExpirationParams
	}
	return nil
}

// TicketSenderParams contains per-ticket nonce + signature values that
// the sender produces while creating a ticket batch.
type TicketSenderParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonically increasing counter that makes a ticket unique
	// relative to a given `recipient_rand_hash` in `TicketParams`. The
	// receiver tracks up to 600 nonces per recipient_rand_hash and
	// rejects duplicates.
	SenderNonce uint32 `protobuf:"varint,1,opt,name=sender_nonce,json=senderNonce,proto3" json:"sender_nonce,omitempty"`
	// Sender's ECDSA signature over the ticket hash.
	//
	// Format: `[R || S || V]` (65 bytes). `V ∈ {27, 28}`. Signature is
	// computed over `accounts.TextHash(ticket.Hash().Bytes())` — i.e.,
	// the ticket hash wrapped in the Ethereum personal_sign EIP-191
	// prefix `\x19Ethereum Signed Message:\n32`. See
	// `../docs/wire-compat.md` §"Signature wire-compat".
	Sig           []byte `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketSenderParams) Reset() {
	*x = TicketSenderParams{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketSenderParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketSenderParams) ProtoMessage() {}

func (x *TicketSenderParams) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketSenderParams.ProtoReflect.Descriptor instead.
func (*TicketSenderParams) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *TicketSenderParams) GetSenderNonce() uint32 {
	if x != nil {
		return x.SenderNonce
	}
	return 0
}

func (x *TicketSenderParams) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

// TicketExpirationParams carries the Livepeer "round" and associated
// block hash used to validate ticket freshness against the protocol
// round state.
type TicketExpirationParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Livepeer protocol round during which the tickets were created.
	CreationRound int64 `protobuf:"varint,1,opt,name=creation_round,json=creationRound,proto3" json:"creation_round,omitempty"`
	// Block hash associated with `creation_round`.
	CreationRoundBlockHash []byte `protobuf:"bytes,2,opt,name=creation_round_block_hash,json=creationRoundBlockHash,proto3" json:"creation_round_block_hash,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TicketExpirationParams) Reset() {
	*x = TicketExpirationParams{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketExpirationParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketExpirationParams) ProtoMessage() {}

func (x *TicketExpirationParams) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketExpirationParams.ProtoReflect.Descriptor instead.
func (*TicketExpirationParams) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *TicketExpirationParams) GetCreationRound() int64 {
	if x != nil {
		return x.CreationRound
	}
	return 0
}

func (x *TicketExpirationParams) GetCreationRoundBlockHash() []byte {
	if x != nil {
		return x.CreationRoundBlockHash
	}
	return nil
}

// Payment is the on-the-wire payment message. One `Payment` can carry
// many tickets (one per entry in `ticket_sender_params`) so a payer
// can cover a whole segment / job / session in a single wire message.
//
// Encoding: deterministic protobuf-3 wire format, base64-encoded
// (RFC 4648 §4 — standard, not URL-safe; padding REQUIRED) when
// transported as the `Livepeer-Payment` HTTP header value.
type Payment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Recipient-controlled ticket parameters. Stays the same across all
	// tickets in this payment.
	TicketParams *TicketParams `protobuf:"bytes,1,opt,name=ticket_params,json=ticketParams,proto3" json:"ticket_params,omitempty"`
	// ETH address of the sender.
	Sender []byte `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	// Shared expiration params for all tickets in this payment.
	ExpirationParams *TicketExpirationParams `protobuf:"bytes,3,opt,name=expiration_params,json=expirationParams,proto3" json:"expiration_params,omitempty"`
	// Per-ticket sender parameters (nonce + signature). One entry per
	// ticket.
	TicketSenderParams []*TicketSenderParams `protobuf:"bytes,4,rep,name=ticket_sender_params,json=ticketSenderParams,proto3" json:"ticket_sender_params,omitempty"`
	// Payer's last-known price for this work. Used by the payee to
	// detect stale clients and trigger a re-quote.
	ExpectedPrice *PriceInfo `protobuf:"bytes,5,opt,name=expected_price,json=expectedPrice,proto3" json:"expected_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *Payment) GetTicketParams() *TicketParams {
	if x != nil {
		return x.TicketParams
	}
	return nil
}

func (x *Payment) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Payment) GetExpirationParams() *TicketExpirationParams {
	if x != nil {
		return x.ExpirationParams
	}
	return nil
}

func (x *Payment) GetTicketSenderParams() []*TicketSenderParams {
	if x != nil {
		return x.TicketSenderParams
	}
	return nil
}

func (x *Payment) GetExpectedPrice() *PriceInfo {
	if x != nil {
		return x.ExpectedPrice
	}
	return nil
}

// OfferingPrice pairs an offering identifier with its wei-per-work-unit
// price. Shared between GetQuoteResponse and ListCapabilitiesResponse so
// the two surfaces cannot drift.
type OfferingPrice struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Offering identifier, e.g. "llama-3.3-70b". Must match the offering
	// string the bridge uses when resolving a request to a node.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Price for one work unit (see `CapabilityEntry.work_unit` for the
	// meaning of "unit" on this capability).
	PriceInfo     *PriceInfo `protobuf:"bytes,2,opt,name=price_info,json=priceInfo,proto3" json:"price_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferingPrice) Reset() {
	*x = OfferingPrice{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferingPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferingPrice) ProtoMessage() {}

func (x *OfferingPrice) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferingPrice.ProtoReflect.Descriptor instead.
func (*OfferingPrice) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *OfferingPrice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OfferingPrice) GetPriceInfo() *PriceInfo {
	if x != nil {
		return x.PriceInfo
	}
	return nil
}

// CapabilityEntry is one row of the daemon's capability catalog.
type CapabilityEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Capability string as published by the worker / broker. Opaque to
	// the daemon; callers should not assume slash-form and colon-form
	// OpenAI IDs are interchangeable.
	Capability string `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	// Work-unit identifier for observability ("token", "audio_second",
	// "image_step_megapixel", "character", ...). The daemon treats work
	// units as opaque int64 — this field is metadata for the worker /
	// bridge.
	WorkUnit string `protobuf:"bytes,2,opt,name=work_unit,json=workUnit,proto3" json:"work_unit,omitempty"`
	// Offerings served on this capability, with their configured prices.
	Offerings     []*OfferingPrice `protobuf:"bytes,3,rep,name=offerings,proto3" json:"offerings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityEntry) Reset() {
	*x = CapabilityEntry{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityEntry) ProtoMessage() {}

func (x *CapabilityEntry) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityEntry.ProtoReflect.Descriptor instead.
func (*CapabilityEntry) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *CapabilityEntry) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *CapabilityEntry) GetWorkUnit() string {
	if x != nil {
		return x.WorkUnit
	}
	return ""
}

func (x *CapabilityEntry) GetOfferings() []*OfferingPrice {
	if x != nil {
		return x.Offerings
	}
	return nil
}

// HealthRequest / HealthResponse are shared by both PayerDaemon and
// PayeeDaemon. Both services expose `Health` so callers can probe
// readiness at startup before binding their own listeners.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{7}
}

type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Liveness signal. v0.2 returns the literal string "ok" when ready.
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// BigUInt is the canonical daemon-app representation for non-negative integers
// that may exceed 64 bits. Bytes are unsigned big-endian with no sign byte.
// Zero is encoded as the empty byte string or a single 0x00 byte; producers
// SHOULD prefer the empty byte string for canonical form.
type BigUInt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BigUInt) Reset() {
	*x = BigUInt{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BigUInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigUInt) ProtoMessage() {}

func (x *BigUInt) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigUInt.ProtoReflect.Descriptor instead.
func (*BigUInt) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *BigUInt) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// QuoteRef anchors gateway-selected pricing to a stable route/quote identity.
type QuoteRef struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	QuoteId               string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	QuoteVersion          uint64                 `protobuf:"varint,2,opt,name=quote_version,json=quoteVersion,proto3" json:"quote_version,omitempty"`
	ConstraintFingerprint []byte                 `protobuf:"bytes,3,opt,name=constraint_fingerprint,json=constraintFingerprint,proto3" json:"constraint_fingerprint,omitempty"`
	RouteFingerprint      []byte                 `protobuf:"bytes,4,opt,name=route_fingerprint,json=routeFingerprint,proto3" json:"route_fingerprint,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *QuoteRef) Reset() {
	*x = QuoteRef{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRef) ProtoMessage() {}

func (x *QuoteRef) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteRef.ProtoReflect.Descriptor instead.
func (*QuoteRef) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{10}
}

func (x *QuoteRef) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *QuoteRef) GetQuoteVersion() uint64 {
	if x != nil {
		return x.QuoteVersion
	}
	return 0
}

func (x *QuoteRef) GetConstraintFingerprint() []byte {
	if x != nil {
		return x.ConstraintFingerprint
	}
	return nil
}

func (x *QuoteRef) GetRouteFingerprint() []byte {
	if x != nil {
		return x.RouteFingerprint
	}
	return nil
}

// AcceptedPrice is the quote basis the gateway accepted before payment minting.
type AcceptedPrice struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PricePerUnitWei *BigUInt               `protobuf:"bytes,1,opt,name=price_per_unit_wei,json=pricePerUnitWei,proto3" json:"price_per_unit_wei,omitempty"`
	UnitsPerPrice   uint64                 `protobuf:"varint,2,opt,name=units_per_price,json=unitsPerPrice,proto3" json:"units_per_price,omitempty"`
	WorkUnitName    string                 `protobuf:"bytes,3,opt,name=work_unit_name,json=workUnitName,proto3" json:"work_unit_name,omitempty"`
	Capability      string                 `protobuf:"bytes,4,opt,name=capability,proto3" json:"capability,omitempty"`
	Offering        string                 `protobuf:"bytes,5,opt,name=offering,proto3" json:"offering,omitempty"`
	QuoteRef        *QuoteRef              `protobuf:"bytes,6,opt,name=quote_ref,json=quoteRef,proto3" json:"quote_ref,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AcceptedPrice) Reset() {
	*x = AcceptedPrice{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptedPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedPrice) ProtoMessage() {}

func (x *AcceptedPrice) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedPrice.ProtoReflect.Descriptor instead.
func (*AcceptedPrice) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{11}
}

func (x *AcceptedPrice) GetPricePerUnitWei() *BigUInt {
	if x != nil {
		return x.PricePerUnitWei
	}
	return nil
}

func (x *AcceptedPrice) GetUnitsPerPrice() uint64 {
	if x != nil {
		return x.UnitsPerPrice
	}
	return 0
}

func (x *AcceptedPrice) GetWorkUnitName() string {
	if x != nil {
		return x.WorkUnitName
	}
	return ""
}

func (x *AcceptedPrice) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *AcceptedPrice) GetOffering() string {
	if x != nil {
		return x.Offering
	}
	return ""
}

func (x *AcceptedPrice) GetQuoteRef() *QuoteRef {
	if x != nil {
		return x.QuoteRef
	}
	return nil
}

// FundingIntent describes the budget the gateway is authorizing for a request/session.
type FundingIntent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EstimatedUnits uint64                 `protobuf:"varint,1,opt,name=estimated_units,json=estimatedUnits,proto3" json:"estimated_units,omitempty"`
	FundedValueWei *BigUInt               `protobuf:"bytes,2,opt,name=funded_value_wei,json=fundedValueWei,proto3" json:"funded_value_wei,omitempty"`
	MaxTotalUnits  uint64                 `protobuf:"varint,3,opt,name=max_total_units,json=maxTotalUnits,proto3" json:"max_total_units,omitempty"`
	TopUpAllowed   bool                   `protobuf:"varint,4,opt,name=top_up_allowed,json=topUpAllowed,proto3" json:"top_up_allowed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FundingIntent) Reset() {
	*x = FundingIntent{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundingIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundingIntent) ProtoMessage() {}

func (x *FundingIntent) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundingIntent.ProtoReflect.Descriptor instead.
func (*FundingIntent) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{12}
}

func (x *FundingIntent) GetEstimatedUnits() uint64 {
	if x != nil {
		return x.EstimatedUnits
	}
	return 0
}

func (x *FundingIntent) GetFundedValueWei() *BigUInt {
	if x != nil {
		return x.FundedValueWei
	}
	return nil
}

func (x *FundingIntent) GetMaxTotalUnits() uint64 {
	if x != nil {
		return x.MaxTotalUnits
	}
	return 0
}

func (x *FundingIntent) GetTopUpAllowed() bool {
	if x != nil {
		return x.TopUpAllowed
	}
	return false
}

// SpendAuthorizationPayload is the payer-signed authority for exactly one
// job or logical session. It is deliberately separate from Payment: tickets
// add value to a stable payer-payee account, while this payload says which
// engagement may reserve and debit that value.
//
// Signature input is the deterministic protobuf encoding of this message,
// hashed with keccak256 and signed with Ethereum personal_sign (EIP-191).
type SpendAuthorizationPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Domain/version tag. Producers MUST set
	// "livepeer-spend-authorization/v1".
	Domain                     string         `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Payer                      []byte         `protobuf:"bytes,2,opt,name=payer,proto3" json:"payer,omitempty"`
	Payee                      []byte         `protobuf:"bytes,3,opt,name=payee,proto3" json:"payee,omitempty"`
	AuthorizationId            string         `protobuf:"bytes,4,opt,name=authorization_id,json=authorizationId,proto3" json:"authorization_id,omitempty"`
	RequestId                  string         `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId                  string         `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Protocol                   string         `protobuf:"bytes,7,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Capability                 string         `protobuf:"bytes,8,opt,name=capability,proto3" json:"capability,omitempty"`
	Offering                   string         `protobuf:"bytes,9,opt,name=offering,proto3" json:"offering,omitempty"`
	AcceptedPrice              *AcceptedPrice `protobuf:"bytes,10,opt,name=accepted_price,json=acceptedPrice,proto3" json:"accepted_price,omitempty"`
	MaxDebitWei                *BigUInt       `protobuf:"bytes,11,opt,name=max_debit_wei,json=maxDebitWei,proto3" json:"max_debit_wei,omitempty"`
	MaxTotalUnits              uint64         `protobuf:"varint,12,opt,name=max_total_units,json=maxTotalUnits,proto3" json:"max_total_units,omitempty"`
	NotBefore                  string         `protobuf:"bytes,13,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	ExpiresAt                  string         `protobuf:"bytes,14,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RequestDigest              []byte         `protobuf:"bytes,15,opt,name=request_digest,json=requestDigest,proto3" json:"request_digest,omitempty"`
	CallerPublicKey            []byte         `protobuf:"bytes,16,opt,name=caller_public_key,json=callerPublicKey,proto3" json:"caller_public_key,omitempty"`
	Revision                   uint64         `protobuf:"varint,17,opt,name=revision,proto3" json:"revision,omitempty"`
	PredecessorAuthorizationId string         `protobuf:"bytes,18,opt,name=predecessor_authorization_id,json=predecessorAuthorizationId,proto3" json:"predecessor_authorization_id,omitempty"`
	BrokerUri                  string         `protobuf:"bytes,19,opt,name=broker_uri,json=brokerUri,proto3" json:"broker_uri,omitempty"`
	ChainId                    uint64         `protobuf:"varint,20,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Denomination               string         `protobuf:"bytes,21,opt,name=denomination,proto3" json:"denomination,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *SpendAuthorizationPayload) Reset() {
	*x = SpendAuthorizationPayload{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpendAuthorizationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendAuthorizationPayload) ProtoMessage() {}

func (x *SpendAuthorizationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendAuthorizationPayload.ProtoReflect.Descriptor instead.
func (*SpendAuthorizationPayload) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{13}
}

func (x *SpendAuthorizationPayload) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *SpendAuthorizationPayload) GetPayer() []byte {
	if x != nil {
		return x.Payer
	}
	return nil
}

func (x *SpendAuthorizationPayload) GetPayee() []byte {
	if x != nil {
		return x.Payee
	}
	return nil
}

func (x *SpendAuthorizationPayload) GetAuthorizationId() string {
	if x != nil {
		return x.AuthorizationId
	}
	return ""
}

func (x *SpendAuthorizationPayload) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SpendAuthorizationPayload) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SpendAuthorizationPayload) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *SpendAuthorizationPayload) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *SpendAuthorizationPayload) GetOffering() string {
	if x != nil {
		return x.Offering
	}
	return ""
}

func (x *SpendAuthorizationPayload) GetAcceptedPrice() *AcceptedPrice {
	if x != nil {
		return x.AcceptedPrice
	}
	return nil
}

func (x *SpendAuthorizationPayload) GetMaxDebitWei() *BigUInt {
	if x != nil {
		return x.MaxDebitWei
	}
	return nil
}

func (x *SpendAuthorizationPayload) GetMaxTotalUnits() uint64 {
	if x != nil {
		return x.MaxTotalUnits
	}
	return 0
}

func (x *SpendAuthorizationPayload) GetNotBefore() string {
	if x != nil {
		return x.NotBefore
	}
	return ""
}

func (x *SpendAuthorizationPayload) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *SpendAuthorizationPayload) GetRequestDigest() []byte {
	if x != nil {
		return x.RequestDigest
	}
	return nil
}

func (x *SpendAuthorizationPayload) GetCallerPublicKey() []byte {
	if x != nil {
		return x.CallerPublicKey
	}
	return nil
}

func (x *SpendAuthorizationPayload) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *SpendAuthorizationPayload) GetPredecessorAuthorizationId() string {
	if x != nil {
		return x.PredecessorAuthorizationId
	}
	return ""
}

func (x *SpendAuthorizationPayload) GetBrokerUri() string {
	if x != nil {
		return x.BrokerUri
	}
	return ""
}

func (x *SpendAuthorizationPayload) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *SpendAuthorizationPayload) GetDenomination() string {
	if x != nil {
		return x.Denomination
	}
	return ""
}

type SpendAuthorization struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Payload       *SpendAuthorizationPayload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte                     `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpendAuthorization) Reset() {
	*x = SpendAuthorization{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpendAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendAuthorization) ProtoMessage() {}

func (x *SpendAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendAuthorization.ProtoReflect.Descriptor instead.
func (*SpendAuthorization) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{14}
}

func (x *SpendAuthorization) GetPayload() *SpendAuthorizationPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SpendAuthorization) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// AccountFundingIntent asks the sender to fund only the difference between a
// payer-selected target float and a trusted receiver balance observation.
// The caller is the payer application on the sender daemon's trusted socket;
// untrusted end callers never supply these values directly.
type AccountFundingIntent struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TargetAvailableWei   *BigUInt               `protobuf:"bytes,1,opt,name=target_available_wei,json=targetAvailableWei,proto3" json:"target_available_wei,omitempty"`
	ObservedAvailableWei *BigUInt               `protobuf:"bytes,2,opt,name=observed_available_wei,json=observedAvailableWei,proto3" json:"observed_available_wei,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AccountFundingIntent) Reset() {
	*x = AccountFundingIntent{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountFundingIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountFundingIntent) ProtoMessage() {}

func (x *AccountFundingIntent) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountFundingIntent.ProtoReflect.Descriptor instead.
func (*AccountFundingIntent) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{15}
}

func (x *AccountFundingIntent) GetTargetAvailableWei() *BigUInt {
	if x != nil {
		return x.TargetAvailableWei
	}
	return nil
}

func (x *AccountFundingIntent) GetObservedAvailableWei() *BigUInt {
	if x != nil {
		return x.ObservedAvailableWei
	}
	return nil
}

type WholesaleAccountView struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Payer             []byte                 `protobuf:"bytes,1,opt,name=payer,proto3" json:"payer,omitempty"`
	Payee             []byte                 `protobuf:"bytes,2,opt,name=payee,proto3" json:"payee,omitempty"`
	CreditedValueWei  *BigUInt               `protobuf:"bytes,3,opt,name=credited_value_wei,json=creditedValueWei,proto3" json:"credited_value_wei,omitempty"`
	ReservedValueWei  *BigUInt               `protobuf:"bytes,4,opt,name=reserved_value_wei,json=reservedValueWei,proto3" json:"reserved_value_wei,omitempty"`
	DebitedValueWei   *BigUInt               `protobuf:"bytes,5,opt,name=debited_value_wei,json=debitedValueWei,proto3" json:"debited_value_wei,omitempty"`
	AvailableValueWei *BigUInt               `protobuf:"bytes,6,opt,name=available_value_wei,json=availableValueWei,proto3" json:"available_value_wei,omitempty"`
	Version           uint64                 `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	ObservedAt        string                 `protobuf:"bytes,8,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	ChainId           uint64                 `protobuf:"varint,9,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Denomination      string                 `protobuf:"bytes,10,opt,name=denomination,proto3" json:"denomination,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WholesaleAccountView) Reset() {
	*x = WholesaleAccountView{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WholesaleAccountView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WholesaleAccountView) ProtoMessage() {}

func (x *WholesaleAccountView) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WholesaleAccountView.ProtoReflect.Descriptor instead.
func (*WholesaleAccountView) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{16}
}

func (x *WholesaleAccountView) GetPayer() []byte {
	if x != nil {
		return x.Payer
	}
	return nil
}

func (x *WholesaleAccountView) GetPayee() []byte {
	if x != nil {
		return x.Payee
	}
	return nil
}

func (x *WholesaleAccountView) GetCreditedValueWei() *BigUInt {
	if x != nil {
		return x.CreditedValueWei
	}
	return nil
}

func (x *WholesaleAccountView) GetReservedValueWei() *BigUInt {
	if x != nil {
		return x.ReservedValueWei
	}
	return nil
}

func (x *WholesaleAccountView) GetDebitedValueWei() *BigUInt {
	if x != nil {
		return x.DebitedValueWei
	}
	return nil
}

func (x *WholesaleAccountView) GetAvailableValueWei() *BigUInt {
	if x != nil {
		return x.AvailableValueWei
	}
	return nil
}

func (x *WholesaleAccountView) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WholesaleAccountView) GetObservedAt() string {
	if x != nil {
		return x.ObservedAt
	}
	return ""
}

func (x *WholesaleAccountView) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *WholesaleAccountView) GetDenomination() string {
	if x != nil {
		return x.Denomination
	}
	return ""
}

// SettlementRecord is the broker-authoritative accounting result for a request/session.
type SettlementRecord struct {
	state            protoimpl.MessageState             `protogen:"open.v1"`
	AcceptedQuoteRef *QuoteRef                          `protobuf:"bytes,1,opt,name=accepted_quote_ref,json=acceptedQuoteRef,proto3" json:"accepted_quote_ref,omitempty"`
	WorkUnitName     string                             `protobuf:"bytes,2,opt,name=work_unit_name,json=workUnitName,proto3" json:"work_unit_name,omitempty"`
	EstimatedUnits   uint64                             `protobuf:"varint,3,opt,name=estimated_units,json=estimatedUnits,proto3" json:"estimated_units,omitempty"`
	ActualUnits      uint64                             `protobuf:"varint,4,opt,name=actual_units,json=actualUnits,proto3" json:"actual_units,omitempty"`
	BilledUnits      uint64                             `protobuf:"varint,5,opt,name=billed_units,json=billedUnits,proto3" json:"billed_units,omitempty"`
	FundedValueWei   *BigUInt                           `protobuf:"bytes,6,opt,name=funded_value_wei,json=fundedValueWei,proto3" json:"funded_value_wei,omitempty"`
	BilledValueWei   *BigUInt                           `protobuf:"bytes,7,opt,name=billed_value_wei,json=billedValueWei,proto3" json:"billed_value_wei,omitempty"`
	Outcome          SettlementRecord_SettlementOutcome `protobuf:"varint,8,opt,name=outcome,proto3,enum=livepeer.payments.v1.SettlementRecord_SettlementOutcome" json:"outcome,omitempty"`
	// Optional workload-specific metadata. Not part of canonical arithmetic.
	Breakdown map[string]string `protobuf:"bytes,9,rep,name=breakdown,proto3" json:"breakdown,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Stable broker-local session id.
	SessionId string `protobuf:"bytes,10,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// In authorization-only records work_id mirrors authorization_id. The
	// predecessor/rotation fields are retained only to decode historical
	// ticket-session records and MUST be empty/zero on new records.
	WorkId             string `protobuf:"bytes,11,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	PredecessorWorkId  string `protobuf:"bytes,12,opt,name=predecessor_work_id,json=predecessorWorkId,proto3" json:"predecessor_work_id,omitempty"`
	RotationGeneration uint32 `protobuf:"varint,13,opt,name=rotation_generation,json=rotationGeneration,proto3" json:"rotation_generation,omitempty"`
	// Cumulative over the whole logical session. debited_units is the
	// authoritative billing quantity:
	// claimed_units is what a runner asserted, debited_units is what the
	// ledger moved. billed_value_wei above is
	// ceil(debited_units * amount_wei / per_units) over these cumulative
	// units — one ceiling over the total, never a sum of per-event
	// ceilings (offering-axes.md §6.1).
	ClaimedUnits uint64 `protobuf:"varint,14,opt,name=claimed_units,json=claimedUnits,proto3" json:"claimed_units,omitempty"`
	DebitedUnits uint64 `protobuf:"varint,15,opt,name=debited_units,json=debitedUnits,proto3" json:"debited_units,omitempty"`
	// Historical ticket-session generation fields. Authorization-only brokers
	// MUST leave them zero/empty; aggregate ticket funding is reported through
	// account_funding_value_wei and account observations instead.
	GenerationDebitedUnits   uint64   `protobuf:"varint,16,opt,name=generation_debited_units,json=generationDebitedUnits,proto3" json:"generation_debited_units,omitempty"`
	GenerationBilledValueWei *BigUInt `protobuf:"bytes,17,opt,name=generation_billed_value_wei,json=generationBilledValueWei,proto3" json:"generation_billed_value_wei,omitempty"`
	GenerationFundedValueWei *BigUInt `protobuf:"bytes,18,opt,name=generation_funded_value_wei,json=generationFundedValueWei,proto3" json:"generation_funded_value_wei,omitempty"`
	// The price this session was pinned to at open. Carried so a reader
	// can recompute billed_value_wei without trusting it.
	AmountWei *BigUInt `protobuf:"bytes,19,opt,name=amount_wei,json=amountWei,proto3" json:"amount_wei,omitempty"`
	PerUnits  uint64   `protobuf:"varint,20,opt,name=per_units,json=perUnits,proto3" json:"per_units,omitempty"`
	// Monotonic per session_id and unchanged by authorization revision.
	// (session_id, settlement_seq) is the replay binding: a record is
	// meaningful for exactly one session at exactly one point in its life.
	SettlementSeq uint64 `protobuf:"varint,21,opt,name=settlement_seq,json=settlementSeq,proto3" json:"settlement_seq,omitempty"`
	// When this record was produced. A record is a statement about the
	// session as of this instant, not a cached blob.
	IssuedAt string `protobuf:"bytes,22,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	// Session state when the record was produced: "open", "winding_down"
	// or "closed". Distinguishes an interim snapshot from a final
	// settlement.
	State string `protobuf:"bytes,23,opt,name=state,proto3" json:"state,omitempty"`
	// Broker-assigned id for a single job exchange, matching
	// `Livepeer-Job-Id`. REQUIRED on a paid-job settlement.
	//
	// job_id is broker-assigned; request_id and authorization_id provide the
	// caller-owned and payer-owned bindings.
	JobId string `protobuf:"bytes,24,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Historical ticket-session curve position. Authorization-only brokers
	// MUST leave this zero; billed_value_wei is computed on the authorization's
	// cumulative units.
	PaymentCumulativeUnits uint64 `protobuf:"varint,25,opt,name=payment_cumulative_units,json=paymentCumulativeUnits,proto3" json:"payment_cumulative_units,omitempty"`
	// The GATEWAY's own id for this session, echoed from session open.
	// REQUIRED on a paid-session settlement.
	//
	// This is the identifier the session consumer issued itself.
	GatewaySessionId string `protobuf:"bytes,26,opt,name=gateway_session_id,json=gatewaySessionId,proto3" json:"gateway_session_id,omitempty"`
	// The gateway's own id for this EXCHANGE, echoed from
	// `Livepeer-Request-Id`. REQUIRED on a paid-job settlement.
	//
	// This is the counterpart to gateway_session_id on the job path and MUST
	// match the required Livepeer-Request-Id.
	RequestId string `protobuf:"bytes,27,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// ---- authorization-backed account settlement ----
	// Required for paid-workload settlements. These fields keep account
	// funding, temporary reservation, and actual debit visibly distinct.
	AuthorizationId        string   `protobuf:"bytes,28,opt,name=authorization_id,json=authorizationId,proto3" json:"authorization_id,omitempty"`
	AuthorizedValueWei     *BigUInt `protobuf:"bytes,29,opt,name=authorized_value_wei,json=authorizedValueWei,proto3" json:"authorized_value_wei,omitempty"`
	ReservedValueWei       *BigUInt `protobuf:"bytes,30,opt,name=reserved_value_wei,json=reservedValueWei,proto3" json:"reserved_value_wei,omitempty"`
	ReleasedValueWei       *BigUInt `protobuf:"bytes,31,opt,name=released_value_wei,json=releasedValueWei,proto3" json:"released_value_wei,omitempty"`
	AccountFundingValueWei *BigUInt `protobuf:"bytes,32,opt,name=account_funding_value_wei,json=accountFundingValueWei,proto3" json:"account_funding_value_wei,omitempty"`
	AccountVersion         uint64   `protobuf:"varint,33,opt,name=account_version,json=accountVersion,proto3" json:"account_version,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SettlementRecord) Reset() {
	*x = SettlementRecord{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementRecord) ProtoMessage() {}

func (x *SettlementRecord) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementRecord.ProtoReflect.Descriptor instead.
func (*SettlementRecord) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{17}
}

func (x *SettlementRecord) GetAcceptedQuoteRef() *QuoteRef {
	if x != nil {
		return x.AcceptedQuoteRef
	}
	return nil
}

func (x *SettlementRecord) GetWorkUnitName() string {
	if x != nil {
		return x.WorkUnitName
	}
	return ""
}

func (x *SettlementRecord) GetEstimatedUnits() uint64 {
	if x != nil {
		return x.EstimatedUnits
	}
	return 0
}

func (x *SettlementRecord) GetActualUnits() uint64 {
	if x != nil {
		return x.ActualUnits
	}
	return 0
}

func (x *SettlementRecord) GetBilledUnits() uint64 {
	if x != nil {
		return x.BilledUnits
	}
	return 0
}

func (x *SettlementRecord) GetFundedValueWei() *BigUInt {
	if x != nil {
		return x.FundedValueWei
	}
	return nil
}

func (x *SettlementRecord) GetBilledValueWei() *BigUInt {
	if x != nil {
		return x.BilledValueWei
	}
	return nil
}

func (x *SettlementRecord) GetOutcome() SettlementRecord_SettlementOutcome {
	if x != nil {
		return x.Outcome
	}
	return SettlementRecord_SETTLEMENT_OUTCOME_UNSPECIFIED
}

func (x *SettlementRecord) GetBreakdown() map[string]string {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

func (x *SettlementRecord) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SettlementRecord) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *SettlementRecord) GetPredecessorWorkId() string {
	if x != nil {
		return x.PredecessorWorkId
	}
	return ""
}

func (x *SettlementRecord) GetRotationGeneration() uint32 {
	if x != nil {
		return x.RotationGeneration
	}
	return 0
}

func (x *SettlementRecord) GetClaimedUnits() uint64 {
	if x != nil {
		return x.ClaimedUnits
	}
	return 0
}

func (x *SettlementRecord) GetDebitedUnits() uint64 {
	if x != nil {
		return x.DebitedUnits
	}
	return 0
}

func (x *SettlementRecord) GetGenerationDebitedUnits() uint64 {
	if x != nil {
		return x.GenerationDebitedUnits
	}
	return 0
}

func (x *SettlementRecord) GetGenerationBilledValueWei() *BigUInt {
	if x != nil {
		return x.GenerationBilledValueWei
	}
	return nil
}

func (x *SettlementRecord) GetGenerationFundedValueWei() *BigUInt {
	if x != nil {
		return x.GenerationFundedValueWei
	}
	return nil
}

func (x *SettlementRecord) GetAmountWei() *BigUInt {
	if x != nil {
		return x.AmountWei
	}
	return nil
}

func (x *SettlementRecord) GetPerUnits() uint64 {
	if x != nil {
		return x.PerUnits
	}
	return 0
}

func (x *SettlementRecord) GetSettlementSeq() uint64 {
	if x != nil {
		return x.SettlementSeq
	}
	return 0
}

func (x *SettlementRecord) GetIssuedAt() string {
	if x != nil {
		return x.IssuedAt
	}
	return ""
}

func (x *SettlementRecord) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SettlementRecord) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SettlementRecord) GetPaymentCumulativeUnits() uint64 {
	if x != nil {
		return x.PaymentCumulativeUnits
	}
	return 0
}

func (x *SettlementRecord) GetGatewaySessionId() string {
	if x != nil {
		return x.GatewaySessionId
	}
	return ""
}

func (x *SettlementRecord) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SettlementRecord) GetAuthorizationId() string {
	if x != nil {
		return x.AuthorizationId
	}
	return ""
}

func (x *SettlementRecord) GetAuthorizedValueWei() *BigUInt {
	if x != nil {
		return x.AuthorizedValueWei
	}
	return nil
}

func (x *SettlementRecord) GetReservedValueWei() *BigUInt {
	if x != nil {
		return x.ReservedValueWei
	}
	return nil
}

func (x *SettlementRecord) GetReleasedValueWei() *BigUInt {
	if x != nil {
		return x.ReleasedValueWei
	}
	return nil
}

func (x *SettlementRecord) GetAccountFundingValueWei() *BigUInt {
	if x != nil {
		return x.AccountFundingValueWei
	}
	return nil
}

func (x *SettlementRecord) GetAccountVersion() uint64 {
	if x != nil {
		return x.AccountVersion
	}
	return 0
}

// NonAdmissionRecord is a broker's signed statement that it never
// admitted an exchange for a request id.
//
// It exists because expiry proves an envelope can never be spent AGAIN
// and proves nothing about whether it was already used. A customer can
// submit an envelope, take the work, withhold the job id and settlement
// from its clearinghouse, wait out expiry and ask for the money back —
// and chain state cannot tell that apart from genuine non-use, because a
// losing ticket is never redeemed and most tickets lose.
//
// So this is the evidence a refund needs, and it is deliberately shaped
// so it cannot be laundered through the party that benefits from it:
// a consumer fetches it directly from the broker, keyed on an id the
// CONSUMER issued.
//
// It is a claim, not a proof — but an attributable one. A broker that
// signs a non-admission and has also signed a settlement for the same
// request has produced two contradictory statements under one delegated
// key, which is why both MUST be retained.
type NonAdmissionRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Always "paid-job/v1" or "paid-session/v1". Present so a record
	// cannot be replayed across protocols.
	Protocol string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// The request id the consumer issued and queried by. This is the ONE
	// field below that the broker independently knows: it looked this id
	// up in its own store and found nothing.
	RequestId string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// ---- caller-supplied scope ----
	//
	// EVERYTHING IN THIS BLOCK IS ECHOED FROM THE QUERY, NOT OBSERVED BY
	// THE BROKER. It describes an exchange that never happened, so the
	// broker has nothing of its own to check it against.
	//
	// It is signed anyway, as scope: a record naming only a request id
	// could be replayed against a different envelope that happened to
	// carry the same id from another payer. A consumer MUST compare every
	// field to its own record before acting — the broker's signature here
	// attests "I have no record of request_id X, asked in this context",
	// and not "these values are true".
	WorkId    string `protobuf:"bytes,3,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	Sender    []byte `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient []byte `protobuf:"bytes,5,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// Full quote identity, mirroring a settlement's accepted_quote_ref
	// including both fingerprints, so the record is bound to the same
	// commercial terms the exchange would have carried. Caller-supplied,
	// like the rest of this block.
	AcceptedQuoteRef *QuoteRef `protobuf:"bytes,6,opt,name=accepted_quote_ref,json=acceptedQuoteRef,proto3" json:"accepted_quote_ref,omitempty"`
	// The broker asserting it, so a consumer knows whose key must have
	// signed and whose statement to hold against them later.
	BrokerEthAddress string `protobuf:"bytes,7,opt,name=broker_eth_address,json=brokerEthAddress,proto3" json:"broker_eth_address,omitempty"`
	// When the broker looked. RFC3339 with nanoseconds.
	ObservedAt string `protobuf:"bytes,8,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	// The earliest moment this broker's records are continuous through.
	//
	// A consumer MUST reject the record unless coverage began no later
	// than its own job's issuance: a store that was reset, restored from
	// backup, or reinitialized after issuance cannot distinguish "never
	// admitted" from "forgot". A broker whose store lost continuity MUST
	// move this forward and thereby disqualify itself for jobs older than
	// the gap, rather than attest across it.
	CoverageStartedAt string                     `protobuf:"bytes,9,opt,name=coverage_started_at,json=coverageStartedAt,proto3" json:"coverage_started_at,omitempty"`
	Outcome           NonAdmissionRecord_Outcome `protobuf:"varint,10,opt,name=outcome,proto3,enum=livepeer.payments.v1.NonAdmissionRecord_Outcome" json:"outcome,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NonAdmissionRecord) Reset() {
	*x = NonAdmissionRecord{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonAdmissionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonAdmissionRecord) ProtoMessage() {}

func (x *NonAdmissionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonAdmissionRecord.ProtoReflect.Descriptor instead.
func (*NonAdmissionRecord) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{18}
}

func (x *NonAdmissionRecord) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NonAdmissionRecord) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *NonAdmissionRecord) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *NonAdmissionRecord) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *NonAdmissionRecord) GetRecipient() []byte {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *NonAdmissionRecord) GetAcceptedQuoteRef() *QuoteRef {
	if x != nil {
		return x.AcceptedQuoteRef
	}
	return nil
}

func (x *NonAdmissionRecord) GetBrokerEthAddress() string {
	if x != nil {
		return x.BrokerEthAddress
	}
	return ""
}

func (x *NonAdmissionRecord) GetObservedAt() string {
	if x != nil {
		return x.ObservedAt
	}
	return ""
}

func (x *NonAdmissionRecord) GetCoverageStartedAt() string {
	if x != nil {
		return x.CoverageStartedAt
	}
	return ""
}

func (x *NonAdmissionRecord) GetOutcome() NonAdmissionRecord_Outcome {
	if x != nil {
		return x.Outcome
	}
	return NonAdmissionRecord_OUTCOME_UNSPECIFIED
}

// TicketStatus reports the payee daemon's disposition for one ticket
// inside a ProcessPayment batch.
type TicketStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SenderNonce     uint32                 `protobuf:"varint,1,opt,name=sender_nonce,json=senderNonce,proto3" json:"sender_nonce,omitempty"`
	RejectionReason PaymentRejectionReason `protobuf:"varint,2,opt,name=rejection_reason,json=rejectionReason,proto3,enum=livepeer.payments.v1.PaymentRejectionReason" json:"rejection_reason,omitempty"`
	CreditedEv      []byte                 `protobuf:"bytes,3,opt,name=credited_ev,json=creditedEv,proto3" json:"credited_ev,omitempty"`
	WasWinning      bool                   `protobuf:"varint,4,opt,name=was_winning,json=wasWinning,proto3" json:"was_winning,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TicketStatus) Reset() {
	*x = TicketStatus{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketStatus) ProtoMessage() {}

func (x *TicketStatus) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketStatus.ProtoReflect.Descriptor instead.
func (*TicketStatus) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{19}
}

func (x *TicketStatus) GetSenderNonce() uint32 {
	if x != nil {
		return x.SenderNonce
	}
	return 0
}

func (x *TicketStatus) GetRejectionReason() PaymentRejectionReason {
	if x != nil {
		return x.RejectionReason
	}
	return PaymentRejectionReason_PAYMENT_REJECTION_REASON_UNSPECIFIED
}

func (x *TicketStatus) GetCreditedEv() []byte {
	if x != nil {
		return x.CreditedEv
	}
	return nil
}

func (x *TicketStatus) GetWasWinning() bool {
	if x != nil {
		return x.WasWinning
	}
	return false
}

// PendingRedemption describes one ticket queued for on-chain redemption.
// Returned by ListPendingRedemptions for operator observability.
type PendingRedemption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deterministic ticket identifier (keccak256 of the ticket hash).
	TicketHash []byte `protobuf:"bytes,1,opt,name=ticket_hash,json=ticketHash,proto3" json:"ticket_hash,omitempty"`
	Sender     []byte `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	// Face value (wei, big-endian bytes).
	FaceValue []byte `protobuf:"bytes,3,opt,name=face_value,json=faceValue,proto3" json:"face_value,omitempty"`
	// Unix epoch seconds when the ticket was queued.
	QueuedAt int64 `protobuf:"varint,4,opt,name=queued_at,json=queuedAt,proto3" json:"queued_at,omitempty"`
	// Number of on-chain redemption attempts made so far.
	Attempts      int32 `protobuf:"varint,5,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingRedemption) Reset() {
	*x = PendingRedemption{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingRedemption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingRedemption) ProtoMessage() {}

func (x *PendingRedemption) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingRedemption.ProtoReflect.Descriptor instead.
func (*PendingRedemption) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{20}
}

func (x *PendingRedemption) GetTicketHash() []byte {
	if x != nil {
		return x.TicketHash
	}
	return nil
}

func (x *PendingRedemption) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *PendingRedemption) GetFaceValue() []byte {
	if x != nil {
		return x.FaceValue
	}
	return nil
}

func (x *PendingRedemption) GetQueuedAt() int64 {
	if x != nil {
		return x.QueuedAt
	}
	return 0
}

func (x *PendingRedemption) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

var File_livepeer_payments_v1_types_proto protoreflect.FileDescriptor

const file_livepeer_payments_v1_types_proto_rawDesc = "" +
	"\n" +
	" livepeer/payments/v1/types.proto\x12\x14livepeer.payments.v1\"\x99\x01\n" +
	"\tPriceInfo\x12$\n" +
	"\x0eprice_per_unit\x18\x01 \x01(\x03R\fpricePerUnit\x12&\n" +
	"\x0fpixels_per_unit\x18\x02 \x01(\x03R\rpixelsPerUnit\x12\x1e\n" +
	"\n" +
	"capability\x18\x03 \x01(\rR\n" +
	"capability\x12\x1e\n" +
	"\n" +
	"constraint\x18\x04 \x01(\tR\n" +
	"constraint\"\xb0\x02\n" +
	"\fTicketParams\x12\x1c\n" +
	"\trecipient\x18\x01 \x01(\fR\trecipient\x12\x1d\n" +
	"\n" +
	"face_value\x18\x02 \x01(\fR\tfaceValue\x12\x19\n" +
	"\bwin_prob\x18\x03 \x01(\fR\awinProb\x12.\n" +
	"\x13recipient_rand_hash\x18\x04 \x01(\fR\x11recipientRandHash\x12\x12\n" +
	"\x04seed\x18\x05 \x01(\fR\x04seed\x12)\n" +
	"\x10expiration_block\x18\x06 \x01(\fR\x0fexpirationBlock\x12Y\n" +
	"\x11expiration_params\x18\a \x01(\v2,.livepeer.payments.v1.TicketExpirationParamsR\x10expirationParams\"I\n" +
	"\x12TicketSenderParams\x12!\n" +
	"\fsender_nonce\x18\x01 \x01(\rR\vsenderNonce\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\fR\x03sig\"z\n" +
	"\x16TicketExpirationParams\x12%\n" +
	"\x0ecreation_round\x18\x01 \x01(\x03R\rcreationRound\x129\n" +
	"\x19creation_round_block_hash\x18\x02 \x01(\fR\x16creationRoundBlockHash\"\xe9\x02\n" +
	"\aPayment\x12G\n" +
	"\rticket_params\x18\x01 \x01(\v2\".livepeer.payments.v1.TicketParamsR\fticketParams\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\fR\x06sender\x12Y\n" +
	"\x11expiration_params\x18\x03 \x01(\v2,.livepeer.payments.v1.TicketExpirationParamsR\x10expirationParams\x12Z\n" +
	"\x14ticket_sender_params\x18\x04 \x03(\v2(.livepeer.payments.v1.TicketSenderParamsR\x12ticketSenderParams\x12F\n" +
	"\x0eexpected_price\x18\x05 \x01(\v2\x1f.livepeer.payments.v1.PriceInfoR\rexpectedPrice\"_\n" +
	"\rOfferingPrice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12>\n" +
	"\n" +
	"price_info\x18\x02 \x01(\v2\x1f.livepeer.payments.v1.PriceInfoR\tpriceInfo\"\x91\x01\n" +
	"\x0fCapabilityEntry\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\x12\x1b\n" +
	"\twork_unit\x18\x02 \x01(\tR\bworkUnit\x12A\n" +
	"\tofferings\x18\x03 \x03(\v2#.livepeer.payments.v1.OfferingPriceR\tofferings\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x1f\n" +
	"\aBigUInt\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"\xae\x01\n" +
	"\bQuoteRef\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12#\n" +
	"\rquote_version\x18\x02 \x01(\x04R\fquoteVersion\x125\n" +
	"\x16constraint_fingerprint\x18\x03 \x01(\fR\x15constraintFingerprint\x12+\n" +
	"\x11route_fingerprint\x18\x04 \x01(\fR\x10routeFingerprint\"\xa2\x02\n" +
	"\rAcceptedPrice\x12J\n" +
	"\x12price_per_unit_wei\x18\x01 \x01(\v2\x1d.livepeer.payments.v1.BigUIntR\x0fpricePerUnitWei\x12&\n" +
	"\x0funits_per_price\x18\x02 \x01(\x04R\runitsPerPrice\x12$\n" +
	"\x0ework_unit_name\x18\x03 \x01(\tR\fworkUnitName\x12\x1e\n" +
	"\n" +
	"capability\x18\x04 \x01(\tR\n" +
	"capability\x12\x1a\n" +
	"\boffering\x18\x05 \x01(\tR\boffering\x12;\n" +
	"\tquote_ref\x18\x06 \x01(\v2\x1e.livepeer.payments.v1.QuoteRefR\bquoteRef\"\xcf\x01\n" +
	"\rFundingIntent\x12'\n" +
	"\x0festimated_units\x18\x01 \x01(\x04R\x0eestimatedUnits\x12G\n" +
	"\x10funded_value_wei\x18\x02 \x01(\v2\x1d.livepeer.payments.v1.BigUIntR\x0efundedValueWei\x12&\n" +
	"\x0fmax_total_units\x18\x03 \x01(\x04R\rmaxTotalUnits\x12$\n" +
	"\x0etop_up_allowed\x18\x04 \x01(\bR\ftopUpAllowed\"\xa4\x06\n" +
	"\x19SpendAuthorizationPayload\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x14\n" +
	"\x05payer\x18\x02 \x01(\fR\x05payer\x12\x14\n" +
	"\x05payee\x18\x03 \x01(\fR\x05payee\x12)\n" +
	"\x10authorization_id\x18\x04 \x01(\tR\x0fauthorizationId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bprotocol\x18\a \x01(\tR\bprotocol\x12\x1e\n" +
	"\n" +
	"capability\x18\b \x01(\tR\n" +
	"capability\x12\x1a\n" +
	"\boffering\x18\t \x01(\tR\boffering\x12J\n" +
	"\x0eaccepted_price\x18\n" +
	" \x01(\v2#.livepeer.payments.v1.AcceptedPriceR\racceptedPrice\x12A\n" +
	"\rmax_debit_wei\x18\v \x01(\v2\x1d.livepeer.payments.v1.BigUIntR\vmaxDebitWei\x12&\n" +
	"\x0fmax_total_units\x18\f \x01(\x04R\rmaxTotalUnits\x12\x1d\n" +
	"\n" +
	"not_before\x18\r \x01(\tR\tnotBefore\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x0e \x01(\tR\texpiresAt\x12%\n" +
	"\x0erequest_digest\x18\x0f \x01(\fR\rrequestDigest\x12*\n" +
	"\x11caller_public_key\x18\x10 \x01(\fR\x0fcallerPublicKey\x12\x1a\n" +
	"\brevision\x18\x11 \x01(\x04R\brevision\x12@\n" +
	"\x1cpredecessor_authorization_id\x18\x12 \x01(\tR\x1apredecessorAuthorizationId\x12\x1d\n" +
	"\n" +
	"broker_uri\x18\x13 \x01(\tR\tbrokerUri\x12\x19\n" +
	"\bchain_id\x18\x14 \x01(\x04R\achainId\x12\"\n" +
	"\fdenomination\x18\x15 \x01(\tR\fdenomination\"}\n" +
	"\x12SpendAuthorization\x12I\n" +
	"\apayload\x18\x01 \x01(\v2/.livepeer.payments.v1.SpendAuthorizationPayloadR\apayload\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xbc\x01\n" +
	"\x14AccountFundingIntent\x12O\n" +
	"\x14target_available_wei\x18\x01 \x01(\v2\x1d.livepeer.payments.v1.BigUIntR\x12targetAvailableWei\x12S\n" +
	"\x16observed_available_wei\x18\x02 \x01(\v2\x1d.livepeer.payments.v1.BigUIntR\x14observedAvailableWei\"\xf0\x03\n" +
	"\x14WholesaleAccountView\x12\x14\n" +
	"\x05payer\x18\x01 \x01(\fR\x05payer\x12\x14\n" +
	"\x05payee\x18\x02 \x01(\fR\x05payee\x12K\n" +
	"\x12credited_value_wei\x18\x03 \x01(\v2\x1d.livepeer.payments.v1.BigUIntR\x10creditedValueWei\x12K\n" +
	"\x12reserved_value_wei\x18\x04 \x01(\v2\x1d.livepeer.payments.v1.BigUIntR\x10reservedValueWei\x12I\n" +
	"\x11debited_value_wei\x18\x05 \x01(\v2\x1d.livepeer.payments.v1.BigUIntR\x0fdebitedValueWei\x12M\n" +
	"\x13available_value_wei\x18\x06 \x01(\v2\x1d.livepeer.payments.v1.BigUIntR\x11availableValueWei\x12\x18\n" +
	"\aversion\x18\a \x01(\x04R\aversion\x12\x1f\n" +
	"\vobserved_at\x18\b \x01(\tR\n" +
	"observedAt\x12\x19\n" +
	"\bchain_id\x18\t \x01(\x04R\achainId\x12\"\n" +
	"\fdenomination\x18\n" +
	" \x01(\tR\fdenomination\"\xd1\x0f\n" +
	"\x10SettlementRecord\x12L\n" +
	"\x12accepted_quote_ref\x18\x01 \x01(\v2\x1e.livepeer.payments.v1.QuoteRefR\x10acceptedQuoteRef\x12$\n" +
	"\x0ework_unit_name\x18\x02 \x01(\tR\fworkUnitName\x12'\n" +
	"\x0festimated_units\x18\x03 \x01(\x04R\x0eestimatedUnits\x12!\n" +
	"\factual_units\x18\x04 \x01(\x04R\vactualUnits\x12!\n" +
	"\fbilled_units\x18\x05 \x01(\x04R\vbilledUnits\x12G\n" +
	"\x10funded_value_wei\x18\x06 \x01(\v2\x1d.livepeer.payments.v1.BigUIntR\x0efundedValueWei\x12G\n" +
	"\x10billed_value_wei\x18\a \x01(\v2\x1d.livepeer.payments.v1.BigUIntR\x0ebilledValueWei\x12R\n" +
	"\aoutcome\x18\b \x01(\x0e28.livepeer.payments.v1.SettlementRecord.SettlementOutcomeR\aoutcome\x12S\n" +
	"\tbreakdown\x18\t \x03(\v25.livepeer.payments.v1.SettlementRecord.BreakdownEntryR\tbreakdown\x12\x1d\n" +
	"\n" +
	"session_id\x18\n" +
	" \x01(\tR\tsessionId\x12\x17\n" +
	"\awork_id\x18\v \x01(\tR\x06workId\x12.\n" +
	"\x13predecessor_work_id\x18\f \x01(\tR\x11predecessorWorkId\x12/\n" +
	"\x13rotation_generation\x18\r \x01(\rR\x12rotationGeneration\x12#\n" +
	"\rclaimed_units\x18\x0e \x01(\x04R\fclaimedUnits\x12#\n" +
	"\rdebited_units\x18\x0f \x01(\x04R\fdebitedUnits\x128\n" +
	"\x18generation_debited_units\x18\x10 \x01(\x04R\x16generationDebitedUnits\x12\\\n" +
	"\x1bgeneration_billed_value_wei\x18\x11 \x01(\v2\x1d.livepeer.payments.v1.BigUIntR\x18generationBilledValueWei\x12\\\n" +
	"\x1bgeneration_funded_value_wei\x18\x12 \x01(\v2\x1d.livepeer.payments.v1.BigUIntR\x18generationFundedValueWei\x12<\n" +
	"\n" +
	"amount_wei\x18\x13 \x01(\v2\x1d.livepeer.payments.v1.BigUIntR\tamountWei\x12\x1b\n" +
	"\tper_units\x18\x14 \x01(\x04R\bperUnits\x12%\n" +
	"\x0esettlement_seq\x18\x15 \x01(\x04R\rsettlementSeq\x12\x1b\n" +
	"\tissued_at\x18\x16 \x01(\tR\bissuedAt\x12\x14\n" +
	"\x05state\x18\x17 \x01(\tR\x05state\x12\x15\n" +
	"\x06job_id\x18\x18 \x01(\tR\x05jobId\x128\n" +
	"\x18payment_cumulative_units\x18\x19 \x01(\x04R\x16paymentCumulativeUnits\x12,\n" +
	"\x12gateway_session_id\x18\x1a \x01(\tR\x10gatewaySessionId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x1b \x01(\tR\trequestId\x12)\n" +
	"\x10authorization_id\x18\x1c \x01(\tR\x0fauthorizationId\x12O\n" +
	"\x14authorized_value_wei\x18\x1d \x01(\v2\x1d.livepeer.payments.v1.BigUIntR\x12authorizedValueWei\x12K\n" +
	"\x12reserved_value_wei\x18\x1e \x01(\v2\x1d.livepeer.payments.v1.BigUIntR\x10reservedValueWei\x12K\n" +
	"\x12released_value_wei\x18\x1f \x01(\v2\x1d.livepeer.payments.v1.BigUIntR\x10releasedValueWei\x12X\n" +
	"\x19account_funding_value_wei\x18  \x01(\v2\x1d.livepeer.payments.v1.BigUIntR\x16accountFundingValueWei\x12'\n" +
	"\x0faccount_version\x18! \x01(\x04R\x0eaccountVersion\x1a<\n" +
	"\x0eBreakdownEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x01\n" +
	"\x11SettlementOutcome\x12\"\n" +
	"\x1eSETTLEMENT_OUTCOME_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05EXACT\x10\x01\x12\x0f\n" +
	"\vUNDERFUNDED\x10\x02\x12\x0e\n" +
	"\n" +
	"OVERFUNDED\x10\x03\x12\x15\n" +
	"\x11STOPPED_AT_BUDGET\x10\x04\x12\r\n" +
	"\tTOPPED_UP\x10\x05\x12\x10\n" +
	"\fDEBIT_FAILED\x10\x06\"\xed\x03\n" +
	"\x12NonAdmissionRecord\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x17\n" +
	"\awork_id\x18\x03 \x01(\tR\x06workId\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\fR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x05 \x01(\fR\trecipient\x12L\n" +
	"\x12accepted_quote_ref\x18\x06 \x01(\v2\x1e.livepeer.payments.v1.QuoteRefR\x10acceptedQuoteRef\x12,\n" +
	"\x12broker_eth_address\x18\a \x01(\tR\x10brokerEthAddress\x12\x1f\n" +
	"\vobserved_at\x18\b \x01(\tR\n" +
	"observedAt\x12.\n" +
	"\x13coverage_started_at\x18\t \x01(\tR\x11coverageStartedAt\x12J\n" +
	"\aoutcome\x18\n" +
	" \x01(\x0e20.livepeer.payments.v1.NonAdmissionRecord.OutcomeR\aoutcome\"4\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fNOT_ADMITTED\x10\x01\"\xcc\x01\n" +
	"\fTicketStatus\x12!\n" +
	"\fsender_nonce\x18\x01 \x01(\rR\vsenderNonce\x12W\n" +
	"\x10rejection_reason\x18\x02 \x01(\x0e2,.livepeer.payments.v1.PaymentRejectionReasonR\x0frejectionReason\x12\x1f\n" +
	"\vcredited_ev\x18\x03 \x01(\fR\n" +
	"creditedEv\x12\x1f\n" +
	"\vwas_winning\x18\x04 \x01(\bR\n" +
	"wasWinning\"\xa4\x01\n" +
	"\x11PendingRedemption\x12\x1f\n" +
	"\vticket_hash\x18\x01 \x01(\fR\n" +
	"ticketHash\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\fR\x06sender\x12\x1d\n" +
	"\n" +
	"face_value\x18\x03 \x01(\fR\tfaceValue\x12\x1b\n" +
	"\tqueued_at\x18\x04 \x01(\x03R\bqueuedAt\x12\x1a\n" +
	"\battempts\x18\x05 \x01(\x05R\battempts*\x9c\x02\n" +
	"\x17SpendAuthorizationState\x12)\n" +
	"%SPEND_AUTHORIZATION_STATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSPEND_AUTHORIZATION_ISSUED\x10\x01\x12 \n" +
	"\x1cSPEND_AUTHORIZATION_ADMITTED\x10\x02\x12\x1f\n" +
	"\x1bSPEND_AUTHORIZATION_SETTLED\x10\x03\x12&\n" +
	"\"SPEND_AUTHORIZATION_EXPIRED_UNUSED\x10\x04\x12'\n" +
	"#SPEND_AUTHORIZATION_OUTCOME_UNKNOWN\x10\x05\x12\"\n" +
	"\x1eSPEND_AUTHORIZATION_SUPERSEDED\x10\x06*\xa6\x02\n" +
	"\x16PaymentRejectionReason\x12(\n" +
	"$PAYMENT_REJECTION_REASON_UNSPECIFIED\x10\x00\x123\n" +
	"/PAYMENT_REJECTION_REASON_INVALID_RECIPIENT_RAND\x10\x01\x12)\n" +
	"%PAYMENT_REJECTION_REASON_NONCE_REPLAY\x10\x02\x12.\n" +
	"*PAYMENT_REJECTION_REASON_NONCE_CAP_REACHED\x10\x03\x12.\n" +
	"*PAYMENT_REJECTION_REASON_INVALID_SIGNATURE\x10\x04\x12\"\n" +
	"\x1ePAYMENT_REJECTION_REASON_OTHER\x10\x05BrZpgithub.com/Cloud-SPE/livepeer-network-modules/livepeer-network-protocol/proto-go/livepeer/payments/v1;paymentsv1b\x06proto3"

var (
	file_livepeer_payments_v1_types_proto_rawDescOnce sync.Once
	file_livepeer_payments_v1_types_proto_rawDescData []byte
)

func file_livepeer_payments_v1_types_proto_rawDescGZIP() []byte {
	file_livepeer_payments_v1_types_proto_rawDescOnce.Do(func() {
		file_livepeer_payments_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_livepeer_payments_v1_types_proto_rawDesc), len(file_livepeer_payments_v1_types_proto_rawDesc)))
	})
	return file_livepeer_payments_v1_types_proto_rawDescData
}

var file_livepeer_payments_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_livepeer_payments_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_livepeer_payments_v1_types_proto_goTypes = []any{
	(SpendAuthorizationState)(0),            // 0: livepeer.payments.v1.SpendAuthorizationState
	(PaymentRejectionReason)(0),             // 1: livepeer.payments.v1.PaymentRejectionReason
	(SettlementRecord_SettlementOutcome)(0), // 2: livepeer.payments.v1.SettlementRecord.SettlementOutcome
	(NonAdmissionRecord_Outcome)(0),         // 3: livepeer.payments.v1.NonAdmissionRecord.Outcome
	(*PriceInfo)(nil),                       // 4: livepeer.payments.v1.PriceInfo
	(*TicketParams)(nil),                    // 5: livepeer.payments.v1.TicketParams
	(*TicketSenderParams)(nil),              // 6: livepeer.payments.v1.TicketSenderParams
	(*TicketExpirationParams)(nil),          // 7: livepeer.payments.v1.TicketExpirationParams
	(*Payment)(nil),                         // 8: livepeer.payments.v1.Payment
	(*OfferingPrice)(nil),                   // 9: livepeer.payments.v1.OfferingPrice
	(*CapabilityEntry)(nil),                 // 10: livepeer.payments.v1.CapabilityEntry
	(*HealthRequest)(nil),                   // 11: livepeer.payments.v1.HealthRequest
	(*HealthResponse)(nil),                  // 12: livepeer.payments.v1.HealthResponse
	(*BigUInt)(nil),                         // 13: livepeer.payments.v1.BigUInt
	(*QuoteRef)(nil),                        // 14: livepeer.payments.v1.QuoteRef
	(*AcceptedPrice)(nil),                   // 15: livepeer.payments.v1.AcceptedPrice
	(*FundingIntent)(nil),                   // 16: livepeer.payments.v1.FundingIntent
	(*SpendAuthorizationPayload)(nil),       // 17: livepeer.payments.v1.SpendAuthorizationPayload
	(*SpendAuthorization)(nil),              // 18: livepeer.payments.v1.SpendAuthorization
	(*AccountFundingIntent)(nil),            // 19: livepeer.payments.v1.AccountFundingIntent
	(*WholesaleAccountView)(nil),            // 20: livepeer.payments.v1.WholesaleAccountView
	(*SettlementRecord)(nil),                // 21: livepeer.payments.v1.SettlementRecord
	(*NonAdmissionRecord)(nil),              // 22: livepeer.payments.v1.NonAdmissionRecord
	(*TicketStatus)(nil),                    // 23: livepeer.payments.v1.TicketStatus
	(*PendingRedemption)(nil),               // 24: livepeer.payments.v1.PendingRedemption
	nil,                                     // 25: livepeer.payments.v1.SettlementRecord.BreakdownEntry
}
var file_livepeer_payments_v1_types_proto_depIdxs = []int32{
	7,  // 0: livepeer.payments.v1.TicketParams.expiration_params:type_name -> livepeer.payments.v1.TicketExpirationParams
	5,  // 1: livepeer.payments.v1.Payment.ticket_params:type_name -> livepeer.payments.v1.TicketParams
	7,  // 2: livepeer.payments.v1.Payment.expiration_params:type_name -> livepeer.payments.v1.TicketExpirationParams
	6,  // 3: livepeer.payments.v1.Payment.ticket_sender_params:type_name -> livepeer.payments.v1.TicketSenderParams
	4,  // 4: livepeer.payments.v1.Payment.expected_price:type_name -> livepeer.payments.v1.PriceInfo
	4,  // 5: livepeer.payments.v1.OfferingPrice.price_info:type_name -> livepeer.payments.v1.PriceInfo
	9,  // 6: livepeer.payments.v1.CapabilityEntry.offerings:type_name -> livepeer.payments.v1.OfferingPrice
	13, // 7: livepeer.payments.v1.AcceptedPrice.price_per_unit_wei:type_name -> livepeer.payments.v1.BigUInt
	14, // 8: livepeer.payments.v1.AcceptedPrice.quote_ref:type_name -> livepeer.payments.v1.QuoteRef
	13, // 9: livepeer.payments.v1.FundingIntent.funded_value_wei:type_name -> livepeer.payments.v1.BigUInt
	15, // 10: livepeer.payments.v1.SpendAuthorizationPayload.accepted_price:type_name -> livepeer.payments.v1.AcceptedPrice
	13, // 11: livepeer.payments.v1.SpendAuthorizationPayload.max_debit_wei:type_name -> livepeer.payments.v1.BigUInt
	17, // 12: livepeer.payments.v1.SpendAuthorization.payload:type_name -> livepeer.payments.v1.SpendAuthorizationPayload
	13, // 13: livepeer.payments.v1.AccountFundingIntent.target_available_wei:type_name -> livepeer.payments.v1.BigUInt
	13, // 14: livepeer.payments.v1.AccountFundingIntent.observed_available_wei:type_name -> livepeer.payments.v1.BigUInt
	13, // 15: livepeer.payments.v1.WholesaleAccountView.credited_value_wei:type_name -> livepeer.payments.v1.BigUInt
	13, // 16: livepeer.payments.v1.WholesaleAccountView.reserved_value_wei:type_name -> livepeer.payments.v1.BigUInt
	13, // 17: livepeer.payments.v1.WholesaleAccountView.debited_value_wei:type_name -> livepeer.payments.v1.BigUInt
	13, // 18: livepeer.payments.v1.WholesaleAccountView.available_value_wei:type_name -> livepeer.payments.v1.BigUInt
	14, // 19: livepeer.payments.v1.SettlementRecord.accepted_quote_ref:type_name -> livepeer.payments.v1.QuoteRef
	13, // 20: livepeer.payments.v1.SettlementRecord.funded_value_wei:type_name -> livepeer.payments.v1.BigUInt
	13, // 21: livepeer.payments.v1.SettlementRecord.billed_value_wei:type_name -> livepeer.payments.v1.BigUInt
	2,  // 22: livepeer.payments.v1.SettlementRecord.outcome:type_name -> livepeer.payments.v1.SettlementRecord.SettlementOutcome
	25, // 23: livepeer.payments.v1.SettlementRecord.breakdown:type_name -> livepeer.payments.v1.SettlementRecord.BreakdownEntry
	13, // 24: livepeer.payments.v1.SettlementRecord.generation_billed_value_wei:type_name -> livepeer.payments.v1.BigUInt
	13, // 25: livepeer.payments.v1.SettlementRecord.generation_funded_value_wei:type_name -> livepeer.payments.v1.BigUInt
	13, // 26: livepeer.payments.v1.SettlementRecord.amount_wei:type_name -> livepeer.payments.v1.BigUInt
	13, // 27: livepeer.payments.v1.SettlementRecord.authorized_value_wei:type_name -> livepeer.payments.v1.BigUInt
	13, // 28: livepeer.payments.v1.SettlementRecord.reserved_value_wei:type_name -> livepeer.payments.v1.BigUInt
	13, // 29: livepeer.payments.v1.SettlementRecord.released_value_wei:type_name -> livepeer.payments.v1.BigUInt
	13, // 30: livepeer.payments.v1.SettlementRecord.account_funding_value_wei:type_name -> livepeer.payments.v1.BigUInt
	14, // 31: livepeer.payments.v1.NonAdmissionRecord.accepted_quote_ref:type_name -> livepeer.payments.v1.QuoteRef
	3,  // 32: livepeer.payments.v1.NonAdmissionRecord.outcome:type_name -> livepeer.payments.v1.NonAdmissionRecord.Outcome
	1,  // 33: livepeer.payments.v1.TicketStatus.rejection_reason:type_name -> livepeer.payments.v1.PaymentRejectionReason
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_livepeer_payments_v1_types_proto_init() }
func file_livepeer_payments_v1_types_proto_init() {
	if File_livepeer_payments_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_livepeer_payments_v1_types_proto_rawDesc), len(file_livepeer_payments_v1_types_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_livepeer_payments_v1_types_proto_goTypes,
		DependencyIndexes: file_livepeer_payments_v1_types_proto_depIdxs,
		EnumInfos:         file_livepeer_payments_v1_types_proto_enumTypes,
		MessageInfos:      file_livepeer_payments_v1_types_proto_msgTypes,
	}.Build()
	File_livepeer_payments_v1_types_proto = out.File
	file_livepeer_payments_v1_types_proto_goTypes = nil
	file_livepeer_payments_v1_types_proto_depIdxs = nil
}
