import { chromium } from 'playwright';
import { readFile, mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const evidence = process.env.PORTAL_BROWSER_EVIDENCE || '/evidence';
const {origin} = JSON.parse(await readFile(`${evidence}/fixture.json`, 'utf8'));
const browser = await chromium.launch({headless: true});
const context = await browser.newContext({ignoreHTTPSErrors: true, viewport: {width: 1440, height: 1000}});
const page = await context.newPage();
const errors=[];page.on('pageerror',error=>errors.push(error.message));
await page.addInitScript(() => {
  window.ethereum = {request: async ({method,params}) => {
    if (method === 'eth_requestAccounts') return [(await (await fetch('/fixture/wallet')).json()).wallet];
    if (method === 'personal_sign') return (await (await fetch('/fixture/sign',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:params[0]})})).json()).signature;
    throw new Error('Unexpected wallet method');
  }};
});
try {
  await mkdir(evidence,{recursive:true});
  await page.goto(origin);
  await page.getByRole('heading',{name:'Your GPUs. Your regional memberships.'}).waitFor();
  assert.equal(await page.locator('[style]').count(),0);
  await page.screenshot({path:`${evidence}/signed-out.png`,fullPage:true,caret:'initial'});
  await page.getByRole('button',{name:'Sign in with wallet'}).click();
  await page.getByRole('button',{name:'Sign out',exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:/^Join /}).count(),2,'sign-in must not join either pool');
  const eu=page.locator('#region-eu');const us=page.locator('#region-us');
  await eu.locator('form[data-action=join] input[type=checkbox]').check();
  await eu.getByRole('button',{name:'Join EU',exact:true}).click();
  await eu.getByText('You accepted this version.').waitFor();
  assert.equal(await us.getByRole('button',{name:'Join US',exact:true}).count(),1,'EU join must leave US unjoined');
  await eu.getByText('Enroll a host in EU',{exact:true}).click();
  await eu.getByLabel('Host label',{exact:true}).fill('GPU host');
  await eu.getByLabel('GPU UUIDs, one per line (optional)').fill('gpu-fixture');
  await eu.getByRole('button',{name:'Create install command',exact:true}).click();
  const dialog=page.getByRole('dialog');await dialog.waitFor();
  const command=await dialog.getByLabel('One-use command').inputValue();
  assert.match(command,/curl -fsS 'https:\/\/127\.0\.0\.1:\d+\/install\/[a-f0-9]{64}' \| sh/);
  assert.ok(!command.includes('fixture-enrollment'));
  const bundleURL=await dialog.getByRole('link',{name:'Download bundle instead'}).getAttribute('href');
  const first=await context.request.get(bundleURL);assert.equal(first.status(),200);
  assert.equal((await context.request.get(bundleURL)).status(),410,'one-time bundle replay');
  await dialog.getByRole('button',{name:'Close',exact:true}).click();
  await eu.getByRole('heading',{name:'GPU host',exact:true}).waitFor();
  await eu.getByText(/Latest agent apply result/).click();
  await eu.getByText(/runner: running.*Container started/).waitFor();
  await eu.getByText('Move this GPU to another region',{exact:true}).click();
  await eu.getByLabel(/^Destination/).selectOption('us');
  const transfer=eu.locator('form[data-action=transfer]');
  await transfer.getByLabel('Reason',{exact:true}).fill('Move selected GPU');
  await transfer.locator('input[type=checkbox]').check();
  await transfer.getByRole('button',{name:'Request regional transfer'}).click();
  await eu.getByText('Waiting for actual agent stop confirmation',{exact:true}).waitFor();
  await eu.getByText('Workload preferences',{exact:true}).click();
  await eu.getByLabel('Template ID',{exact:true}).fill('transcode');
  await eu.getByRole('button',{name:'Opt out',exact:true}).click();
  await eu.getByText('Workload preferences',{exact:true}).click();
  await eu.getByRole('button',{name:'Remove opt-out',exact:true}).click();
  await eu.getByText('Enrollment credentials and retirement',{exact:true}).click();
  const rotate=eu.locator('form[data-action=rotate]');
  await rotate.locator('input[type=checkbox]').check();
  await rotate.getByRole('button',{name:'Rotate and create install command'}).click();
  await dialog.waitFor();
  assert.match(await dialog.getByLabel('One-use command').inputValue(),/\/install\/[a-f0-9]{64}/);
  await dialog.getByRole('button',{name:'Close',exact:true}).click();
  await us.locator('form[data-action=join] input[type=checkbox]').check();
  await us.getByRole('button',{name:'Join US',exact:true}).click();
  await us.getByText('You accepted this version.').waitFor();
  await page.getByRole('cell',{name:/^Complete/}).waitFor();
  await page.screenshot({path:`${evidence}/members-desktop.png`,fullPage:true,caret:'initial'});
  await context.request.post(`${origin}/fixture/offline?pool=us&value=true`);
  await page.reload();
  await page.getByRole('cell',{name:/^Partial or stale/}).waitFor();
  assert.match(await page.locator('#earnings').innerText(),/stale/);
  assert.match(await page.locator('#region-eu').innerText(),/GPU host/,'healthy region continues');
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:`${evidence}/members-mobile-stale.png`,fullPage:true,caret:'initial'});
  assert.equal(await page.locator('[style]').count(),0);
  assert.ok(await page.locator('main h1').count()===1);
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);assert.equal(overflow,false,'page horizontal overflow');
  const blocked=await page.evaluate(async()=>{const r=await fetch('/api/regions/eu/../../admin/v1/payouts',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});return r.status});assert.notEqual(blocked,200);
  await eu.getByText('Enrollment credentials and retirement',{exact:true}).click();
  const retire=eu.locator('form').filter({has:page.getByRole('button',{name:'Retire host',exact:true})});
  await retire.locator('input[type=checkbox]').check();
  await retire.getByRole('button',{name:'Retire host',exact:true}).click();
  await eu.getByText('retiring',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Sign out',exact:true}).click();
  await page.getByRole('button',{name:'Sign in with wallet',exact:true}).waitFor();
  assert.deepEqual(errors,[]);
  console.log('PASS: wallet sign-in without join; independent joins; selected enrollment; one-use bootstrap; agent apply status; pending transfer; opt-out/removal; credential rotation; retirement; logout; compatible reports; stale US with healthy EU; mobile layout; semantic DOM; no script errors. Regional services are fixtures, not live rollout.');
} catch(error) {
  await page.screenshot({path:`${evidence}/failure.png`,fullPage:true,caret:'initial'});
  console.error(await page.locator('main').innerText());
  throw error;
} finally {
  await context.request.post(`${origin}/fixture/stop`).catch(()=>{});
  await browser.close();
}
