// Livepeer Protocol v1 — protocol-daemon gRPC surface.
//
// Operator-facing RPCs over a unix socket. No auth at the boundary;
// trust the local caller.
//
// See docs/product-specs/grpc-surface.md for usage, error codes, and
// examples.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: livepeer/protocol/v1/protocol.proto

package protocolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SkipReason_Code int32

const (
	SkipReason_CODE_UNSPECIFIED           SkipReason_Code = 0
	SkipReason_CODE_ALREADY_REWARDED      SkipReason_Code = 1 // tinfo.LastRewardRound >= round
	SkipReason_CODE_TRANSCODER_INACTIVE   SkipReason_Code = 2 // !tinfo.IsActiveAtRound(round)
	SkipReason_CODE_ROUND_INITIALIZED     SkipReason_Code = 3 // round.Initialized — applies to ForceInitializeRound
	SkipReason_CODE_ROUND_NOT_INITIALIZED SkipReason_Code = 4 // !round.Initialized — reward() reverts until initializeRound lands
	// Force-reward pre-send guards: a forced reward broadcasts a new tx
	// unless one of these makes the send pointless (it would revert and
	// still burn gas, or another tx is already in flight).
	SkipReason_CODE_REWARD_IN_FLIGHT     SkipReason_Code = 5 // a reward tx for this round is already pending/unconfirmed
	SkipReason_CODE_REWARD_WOULD_REVERT  SkipReason_Code = 6 // eth_call dry-run reverted; reason carried in `reason`
	SkipReason_CODE_INSUFFICIENT_BALANCE SkipReason_Code = 7 // wallet balance below the gas cost of the tx
	// Bonding-admin (transfer-bond / withdraw-fees) skip codes.
	SkipReason_CODE_ROUND_NOT_LOCKED    SkipReason_Code = 10 // round not in its lock window
	SkipReason_CODE_NOTHING_TO_TRANSFER SkipReason_Code = 11 // pendingStake <= configured retain
	SkipReason_CODE_BELOW_FEE_THRESHOLD SkipReason_Code = 12 // pendingFees < configured threshold
	SkipReason_CODE_REWARD_NOT_CALLED   SkipReason_Code = 13 // reward-before-transfer guard: reward unconfirmed
	SkipReason_CODE_ACTION_DISABLED     SkipReason_Code = 14 // the action is disabled in operational config
)

// Enum value maps for SkipReason_Code.
var (
	SkipReason_Code_name = map[int32]string{
		0:  "CODE_UNSPECIFIED",
		1:  "CODE_ALREADY_REWARDED",
		2:  "CODE_TRANSCODER_INACTIVE",
		3:  "CODE_ROUND_INITIALIZED",
		4:  "CODE_ROUND_NOT_INITIALIZED",
		5:  "CODE_REWARD_IN_FLIGHT",
		6:  "CODE_REWARD_WOULD_REVERT",
		7:  "CODE_INSUFFICIENT_BALANCE",
		10: "CODE_ROUND_NOT_LOCKED",
		11: "CODE_NOTHING_TO_TRANSFER",
		12: "CODE_BELOW_FEE_THRESHOLD",
		13: "CODE_REWARD_NOT_CALLED",
		14: "CODE_ACTION_DISABLED",
	}
	SkipReason_Code_value = map[string]int32{
		"CODE_UNSPECIFIED":           0,
		"CODE_ALREADY_REWARDED":      1,
		"CODE_TRANSCODER_INACTIVE":   2,
		"CODE_ROUND_INITIALIZED":     3,
		"CODE_ROUND_NOT_INITIALIZED": 4,
		"CODE_REWARD_IN_FLIGHT":      5,
		"CODE_REWARD_WOULD_REVERT":   6,
		"CODE_INSUFFICIENT_BALANCE":  7,
		"CODE_ROUND_NOT_LOCKED":      10,
		"CODE_NOTHING_TO_TRANSFER":   11,
		"CODE_BELOW_FEE_THRESHOLD":   12,
		"CODE_REWARD_NOT_CALLED":     13,
		"CODE_ACTION_DISABLED":       14,
	}
)

func (x SkipReason_Code) Enum() *SkipReason_Code {
	p := new(SkipReason_Code)
	*p = x
	return p
}

func (x SkipReason_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SkipReason_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_livepeer_protocol_v1_protocol_proto_enumTypes[0].Descriptor()
}

func (SkipReason_Code) Type() protoreflect.EnumType {
	return &file_livepeer_protocol_v1_protocol_proto_enumTypes[0]
}

func (x SkipReason_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SkipReason_Code.Descriptor instead.
func (SkipReason_Code) EnumDescriptor() ([]byte, []int) {
	return file_livepeer_protocol_v1_protocol_proto_rawDescGZIP(), []int{14, 0}
}

// Empty is the canonical zero-arg request.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_livepeer_protocol_v1_protocol_proto_rawDescGZIP(), []int{0}
}

// HealthStatus reports the daemon's high-level health.
type HealthStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ok is true when preflight passed and at least one mode-specific
	// service is running.
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// mode is the daemon's operating mode: "round-init" | "reward" | "both".
	Mode string `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	// version is the binary's build version.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// chain_id is the configured expected chain ID.
	ChainId       uint64 `protobuf:"varint,4,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_livepeer_protocol_v1_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *HealthStatus) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthStatus) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *HealthStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthStatus) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

// RoundEvent is one Round transition observed by the daemon.
type RoundEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint64                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	StartBlock    uint64                 `protobuf:"varint,2,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	L1StartBlock  uint64                 `protobuf:"varint,3,opt,name=l1_start_block,json=l1StartBlock,proto3" json:"l1_start_block,omitempty"`
	Length        uint64                 `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	Initialized   bool                   `protobuf:"varint,5,opt,name=initialized,proto3" json:"initialized,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,6,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundEvent) Reset() {
	*x = RoundEvent{}
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundEvent) ProtoMessage() {}

func (x *RoundEvent) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundEvent.ProtoReflect.Descriptor instead.
func (*RoundEvent) Descriptor() ([]byte, []int) {
	return file_livepeer_protocol_v1_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *RoundEvent) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *RoundEvent) GetStartBlock() uint64 {
	if x != nil {
		return x.StartBlock
	}
	return 0
}

func (x *RoundEvent) GetL1StartBlock() uint64 {
	if x != nil {
		return x.L1StartBlock
	}
	return 0
}

func (x *RoundEvent) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *RoundEvent) GetInitialized() bool {
	if x != nil {
		return x.Initialized
	}
	return false
}

func (x *RoundEvent) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

// RoundStatus is the round-init service's most recent observation.
type RoundStatus struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	LastRound               uint64                 `protobuf:"varint,1,opt,name=last_round,json=lastRound,proto3" json:"last_round,omitempty"`
	LastIntentId            []byte                 `protobuf:"bytes,2,opt,name=last_intent_id,json=lastIntentId,proto3" json:"last_intent_id,omitempty"`
	LastError               string                 `protobuf:"bytes,3,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	CurrentRoundInitialized bool                   `protobuf:"varint,4,opt,name=current_round_initialized,json=currentRoundInitialized,proto3" json:"current_round_initialized,omitempty"`
	// current_round_locked reports whether the current round is within its
	// lock window (the gate for transfer-bond / withdraw-fees automation).
	CurrentRoundLocked bool `protobuf:"varint,5,opt,name=current_round_locked,json=currentRoundLocked,proto3" json:"current_round_locked,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RoundStatus) Reset() {
	*x = RoundStatus{}
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundStatus) ProtoMessage() {}

func (x *RoundStatus) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundStatus.ProtoReflect.Descriptor instead.
func (*RoundStatus) Descriptor() ([]byte, []int) {
	return file_livepeer_protocol_v1_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *RoundStatus) GetLastRound() uint64 {
	if x != nil {
		return x.LastRound
	}
	return 0
}

func (x *RoundStatus) GetLastIntentId() []byte {
	if x != nil {
		return x.LastIntentId
	}
	return nil
}

func (x *RoundStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *RoundStatus) GetCurrentRoundInitialized() bool {
	if x != nil {
		return x.CurrentRoundInitialized
	}
	return false
}

func (x *RoundStatus) GetCurrentRoundLocked() bool {
	if x != nil {
		return x.CurrentRoundLocked
	}
	return false
}

// RewardStatus is the reward service's most recent observation.
type RewardStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LastRound         uint64                 `protobuf:"varint,1,opt,name=last_round,json=lastRound,proto3" json:"last_round,omitempty"`
	OrchAddress       []byte                 `protobuf:"bytes,2,opt,name=orch_address,json=orchAddress,proto3" json:"orch_address,omitempty"`
	Eligible          bool                   `protobuf:"varint,3,opt,name=eligible,proto3" json:"eligible,omitempty"`
	EligibilityReason string                 `protobuf:"bytes,4,opt,name=eligibility_reason,json=eligibilityReason,proto3" json:"eligibility_reason,omitempty"`
	LastRewardRound   uint64                 `protobuf:"varint,5,opt,name=last_reward_round,json=lastRewardRound,proto3" json:"last_reward_round,omitempty"`
	Active            bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	LastIntentId      []byte                 `protobuf:"bytes,7,opt,name=last_intent_id,json=lastIntentId,proto3" json:"last_intent_id,omitempty"`
	LastEarnedWei     []byte                 `protobuf:"bytes,8,opt,name=last_earned_wei,json=lastEarnedWei,proto3" json:"last_earned_wei,omitempty"` // big-endian unsigned bytes
	LastError         string                 `protobuf:"bytes,9,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RewardStatus) Reset() {
	*x = RewardStatus{}
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewardStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardStatus) ProtoMessage() {}

func (x *RewardStatus) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardStatus.ProtoReflect.Descriptor instead.
func (*RewardStatus) Descriptor() ([]byte, []int) {
	return file_livepeer_protocol_v1_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *RewardStatus) GetLastRound() uint64 {
	if x != nil {
		return x.LastRound
	}
	return 0
}

func (x *RewardStatus) GetOrchAddress() []byte {
	if x != nil {
		return x.OrchAddress
	}
	return nil
}

func (x *RewardStatus) GetEligible() bool {
	if x != nil {
		return x.Eligible
	}
	return false
}

func (x *RewardStatus) GetEligibilityReason() string {
	if x != nil {
		return x.EligibilityReason
	}
	return ""
}

func (x *RewardStatus) GetLastRewardRound() uint64 {
	if x != nil {
		return x.LastRewardRound
	}
	return 0
}

func (x *RewardStatus) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *RewardStatus) GetLastIntentId() []byte {
	if x != nil {
		return x.LastIntentId
	}
	return nil
}

func (x *RewardStatus) GetLastEarnedWei() []byte {
	if x != nil {
		return x.LastEarnedWei
	}
	return nil
}

func (x *RewardStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

// TxIntentRef is a reference to a TxIntent in chain-commons. Carried by
// ForceOutcome.submitted and consumed by GetTxIntent.
type TxIntentRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 32-byte SHA-256 IntentID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxIntentRef) Reset() {
	*x = TxIntentRef{}
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxIntentRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxIntentRef) ProtoMessage() {}

func (x *TxIntentRef) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxIntentRef.ProtoReflect.Descriptor instead.
func (*TxIntentRef) Descriptor() ([]byte, []int) {
	return file_livepeer_protocol_v1_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *TxIntentRef) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

// SetServiceURIRequest asks protocol-daemon to submit a
// ServiceRegistry.setServiceURI tx through txintent.
type SetServiceURIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetServiceURIRequest) Reset() {
	*x = SetServiceURIRequest{}
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetServiceURIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetServiceURIRequest) ProtoMessage() {}

func (x *SetServiceURIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetServiceURIRequest.ProtoReflect.Descriptor instead.
func (*SetServiceURIRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_protocol_v1_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *SetServiceURIRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// SetAIServiceURIRequest asks protocol-daemon to submit an AI service
// registry setServiceURI tx through txintent.
type SetAIServiceURIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAIServiceURIRequest) Reset() {
	*x = SetAIServiceURIRequest{}
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAIServiceURIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAIServiceURIRequest) ProtoMessage() {}

func (x *SetAIServiceURIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAIServiceURIRequest.ProtoReflect.Descriptor instead.
func (*SetAIServiceURIRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_protocol_v1_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *SetAIServiceURIRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// OnChainServiceURIStatus reports the current ServiceRegistry pointer for
// the orchestrator identity this daemon is managing.
type OnChainServiceURIStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnChainServiceURIStatus) Reset() {
	*x = OnChainServiceURIStatus{}
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnChainServiceURIStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnChainServiceURIStatus) ProtoMessage() {}

func (x *OnChainServiceURIStatus) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnChainServiceURIStatus.ProtoReflect.Descriptor instead.
func (*OnChainServiceURIStatus) Descriptor() ([]byte, []int) {
	return file_livepeer_protocol_v1_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *OnChainServiceURIStatus) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// OnChainAIServiceURIStatus reports the current AI service registry
// pointer for the orchestrator identity this daemon is managing.
type OnChainAIServiceURIStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnChainAIServiceURIStatus) Reset() {
	*x = OnChainAIServiceURIStatus{}
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnChainAIServiceURIStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnChainAIServiceURIStatus) ProtoMessage() {}

func (x *OnChainAIServiceURIStatus) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnChainAIServiceURIStatus.ProtoReflect.Descriptor instead.
func (*OnChainAIServiceURIStatus) Descriptor() ([]byte, []int) {
	return file_livepeer_protocol_v1_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *OnChainAIServiceURIStatus) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// RegistrationStatus reports whether the orchestrator has an on-chain
// ServiceRegistry pointer today.
type RegistrationStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registered    bool                   `protobuf:"varint,1,opt,name=registered,proto3" json:"registered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationStatus) Reset() {
	*x = RegistrationStatus{}
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationStatus) ProtoMessage() {}

func (x *RegistrationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationStatus.ProtoReflect.Descriptor instead.
func (*RegistrationStatus) Descriptor() ([]byte, []int) {
	return file_livepeer_protocol_v1_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *RegistrationStatus) GetRegistered() bool {
	if x != nil {
		return x.Registered
	}
	return false
}

// AIRegistrationStatus reports whether the orchestrator has an on-chain
// AI service registry pointer today.
type AIRegistrationStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registered    bool                   `protobuf:"varint,1,opt,name=registered,proto3" json:"registered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIRegistrationStatus) Reset() {
	*x = AIRegistrationStatus{}
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIRegistrationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIRegistrationStatus) ProtoMessage() {}

func (x *AIRegistrationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIRegistrationStatus.ProtoReflect.Descriptor instead.
func (*AIRegistrationStatus) Descriptor() ([]byte, []int) {
	return file_livepeer_protocol_v1_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *AIRegistrationStatus) GetRegistered() bool {
	if x != nil {
		return x.Registered
	}
	return false
}

// WalletBalanceStatus reports the daemon wallet's current ETH balance.
type WalletBalanceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress []byte                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	BalanceWei    []byte                 `protobuf:"bytes,2,opt,name=balance_wei,json=balanceWei,proto3" json:"balance_wei,omitempty"` // big-endian unsigned bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletBalanceStatus) Reset() {
	*x = WalletBalanceStatus{}
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletBalanceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletBalanceStatus) ProtoMessage() {}

func (x *WalletBalanceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletBalanceStatus.ProtoReflect.Descriptor instead.
func (*WalletBalanceStatus) Descriptor() ([]byte, []int) {
	return file_livepeer_protocol_v1_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *WalletBalanceStatus) GetWalletAddress() []byte {
	if x != nil {
		return x.WalletAddress
	}
	return nil
}

func (x *WalletBalanceStatus) GetBalanceWei() []byte {
	if x != nil {
		return x.BalanceWei
	}
	return nil
}

// ForceOutcome reports the daemon's response to a force-action RPC.
// Either a transaction was submitted (in which case the IntentID is
// returned) or the daemon short-circuited because the on-chain state
// made the action a no-op (in which case a typed reason is returned).
type ForceOutcome struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*ForceOutcome_Submitted
	//	*ForceOutcome_Skipped
	Outcome       isForceOutcome_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceOutcome) Reset() {
	*x = ForceOutcome{}
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceOutcome) ProtoMessage() {}

func (x *ForceOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceOutcome.ProtoReflect.Descriptor instead.
func (*ForceOutcome) Descriptor() ([]byte, []int) {
	return file_livepeer_protocol_v1_protocol_proto_rawDescGZIP(), []int{13}
}

func (x *ForceOutcome) GetOutcome() isForceOutcome_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *ForceOutcome) GetSubmitted() *TxIntentRef {
	if x != nil {
		if x, ok := x.Outcome.(*ForceOutcome_Submitted); ok {
			return x.Submitted
		}
	}
	return nil
}

func (x *ForceOutcome) GetSkipped() *SkipReason {
	if x != nil {
		if x, ok := x.Outcome.(*ForceOutcome_Skipped); ok {
			return x.Skipped
		}
	}
	return nil
}

type isForceOutcome_Outcome interface {
	isForceOutcome_Outcome()
}

type ForceOutcome_Submitted struct {
	Submitted *TxIntentRef `protobuf:"bytes,1,opt,name=submitted,proto3,oneof"`
}

type ForceOutcome_Skipped struct {
	Skipped *SkipReason `protobuf:"bytes,2,opt,name=skipped,proto3,oneof"`
}

func (*ForceOutcome_Submitted) isForceOutcome_Outcome() {}

func (*ForceOutcome_Skipped) isForceOutcome_Outcome() {}

// SkipReason carries why the daemon did not fire a transaction.
type SkipReason struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable reason — surfaced in operator-facing UIs and audit
	// logs. Examples: "already rewarded this round", "transcoder is not
	// active at this round", "round already initialized".
	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	// Stable machine identifier; switch on this rather than the human
	// text. CODE_UNSPECIFIED is reserved for forward-compat (a future
	// skip path the client doesn't recognize maps here).
	Code          SkipReason_Code `protobuf:"varint,2,opt,name=code,proto3,enum=livepeer.protocol.v1.SkipReason_Code" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkipReason) Reset() {
	*x = SkipReason{}
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkipReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipReason) ProtoMessage() {}

func (x *SkipReason) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipReason.ProtoReflect.Descriptor instead.
func (*SkipReason) Descriptor() ([]byte, []int) {
	return file_livepeer_protocol_v1_protocol_proto_rawDescGZIP(), []int{14}
}

func (x *SkipReason) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SkipReason) GetCode() SkipReason_Code {
	if x != nil {
		return x.Code
	}
	return SkipReason_CODE_UNSPECIFIED
}

// OperationalConfig is the daemon's runtime-editable policy: which
// automated behaviors are on, and the receivers/thresholds for the
// round-locked fund-movement actions. Amounts are operator-facing decimal
// strings (LPT / ETH); addresses are 0x-hex strings. Edited via SetConfig.
type OperationalConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RoundInitEnabled      bool                   `protobuf:"varint,1,opt,name=round_init_enabled,json=roundInitEnabled,proto3" json:"round_init_enabled,omitempty"`
	RewardEnabled         bool                   `protobuf:"varint,2,opt,name=reward_enabled,json=rewardEnabled,proto3" json:"reward_enabled,omitempty"`
	RewardBeforeTransfer  bool                   `protobuf:"varint,3,opt,name=reward_before_transfer,json=rewardBeforeTransfer,proto3" json:"reward_before_transfer,omitempty"`
	TransferBondEnabled   bool                   `protobuf:"varint,4,opt,name=transfer_bond_enabled,json=transferBondEnabled,proto3" json:"transfer_bond_enabled,omitempty"`
	TransferBondReceiver  string                 `protobuf:"bytes,5,opt,name=transfer_bond_receiver,json=transferBondReceiver,proto3" json:"transfer_bond_receiver,omitempty"`      // 0x-hex address
	TransferBondMinRetain string                 `protobuf:"bytes,6,opt,name=transfer_bond_min_retain,json=transferBondMinRetain,proto3" json:"transfer_bond_min_retain,omitempty"` // decimal LPT
	WithdrawFeesEnabled   bool                   `protobuf:"varint,7,opt,name=withdraw_fees_enabled,json=withdrawFeesEnabled,proto3" json:"withdraw_fees_enabled,omitempty"`
	WithdrawFeesReceiver  string                 `protobuf:"bytes,8,opt,name=withdraw_fees_receiver,json=withdrawFeesReceiver,proto3" json:"withdraw_fees_receiver,omitempty"`    // 0x-hex address
	WithdrawFeesThreshold string                 `protobuf:"bytes,9,opt,name=withdraw_fees_threshold,json=withdrawFeesThreshold,proto3" json:"withdraw_fees_threshold,omitempty"` // decimal ETH
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *OperationalConfig) Reset() {
	*x = OperationalConfig{}
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationalConfig) ProtoMessage() {}

func (x *OperationalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationalConfig.ProtoReflect.Descriptor instead.
func (*OperationalConfig) Descriptor() ([]byte, []int) {
	return file_livepeer_protocol_v1_protocol_proto_rawDescGZIP(), []int{15}
}

func (x *OperationalConfig) GetRoundInitEnabled() bool {
	if x != nil {
		return x.RoundInitEnabled
	}
	return false
}

func (x *OperationalConfig) GetRewardEnabled() bool {
	if x != nil {
		return x.RewardEnabled
	}
	return false
}

func (x *OperationalConfig) GetRewardBeforeTransfer() bool {
	if x != nil {
		return x.RewardBeforeTransfer
	}
	return false
}

func (x *OperationalConfig) GetTransferBondEnabled() bool {
	if x != nil {
		return x.TransferBondEnabled
	}
	return false
}

func (x *OperationalConfig) GetTransferBondReceiver() string {
	if x != nil {
		return x.TransferBondReceiver
	}
	return ""
}

func (x *OperationalConfig) GetTransferBondMinRetain() string {
	if x != nil {
		return x.TransferBondMinRetain
	}
	return ""
}

func (x *OperationalConfig) GetWithdrawFeesEnabled() bool {
	if x != nil {
		return x.WithdrawFeesEnabled
	}
	return false
}

func (x *OperationalConfig) GetWithdrawFeesReceiver() string {
	if x != nil {
		return x.WithdrawFeesReceiver
	}
	return ""
}

func (x *OperationalConfig) GetWithdrawFeesThreshold() string {
	if x != nil {
		return x.WithdrawFeesThreshold
	}
	return ""
}

// SetTranscoderRequest sets the orchestrator's reward cut and fee cut.
// Both are percentages meaning "what the orchestrator keeps" (the daemon
// converts to ppm and flips fee_cut into the contract's fee_share).
type SetTranscoderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RewardCut     string                 `protobuf:"bytes,1,opt,name=reward_cut,json=rewardCut,proto3" json:"reward_cut,omitempty"` // percent, e.g. "10" or "95.5"
	FeeCut        string                 `protobuf:"bytes,2,opt,name=fee_cut,json=feeCut,proto3" json:"fee_cut,omitempty"`          // percent, e.g. "10" or "95.5"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTranscoderRequest) Reset() {
	*x = SetTranscoderRequest{}
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTranscoderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTranscoderRequest) ProtoMessage() {}

func (x *SetTranscoderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTranscoderRequest.ProtoReflect.Descriptor instead.
func (*SetTranscoderRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_protocol_v1_protocol_proto_rawDescGZIP(), []int{16}
}

func (x *SetTranscoderRequest) GetRewardCut() string {
	if x != nil {
		return x.RewardCut
	}
	return ""
}

func (x *SetTranscoderRequest) GetFeeCut() string {
	if x != nil {
		return x.FeeCut
	}
	return ""
}

// CastVoteRequest votes on a treasury (LivepeerGovernor) proposal.
type CastVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"` // decimal uint256
	Support       uint32                 `protobuf:"varint,2,opt,name=support,proto3" json:"support,omitempty"`                        // OZ GovernorCountingSimple: 0=Against 1=For 2=Abstain
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                           // optional; empty -> castVote, else castVoteWithReason
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastVoteRequest) Reset() {
	*x = CastVoteRequest{}
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastVoteRequest) ProtoMessage() {}

func (x *CastVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastVoteRequest.ProtoReflect.Descriptor instead.
func (*CastVoteRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_protocol_v1_protocol_proto_rawDescGZIP(), []int{17}
}

func (x *CastVoteRequest) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *CastVoteRequest) GetSupport() uint32 {
	if x != nil {
		return x.Support
	}
	return 0
}

func (x *CastVoteRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// GetTreasuryProposalRequest asks for the pre-vote safety snapshot.
type GetTreasuryProposalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"` // decimal uint256
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTreasuryProposalRequest) Reset() {
	*x = GetTreasuryProposalRequest{}
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTreasuryProposalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreasuryProposalRequest) ProtoMessage() {}

func (x *GetTreasuryProposalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreasuryProposalRequest.ProtoReflect.Descriptor instead.
func (*GetTreasuryProposalRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_protocol_v1_protocol_proto_rawDescGZIP(), []int{18}
}

func (x *GetTreasuryProposalRequest) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

// TreasuryProposal is the pre-vote safety snapshot for a proposal.
type TreasuryProposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`                                // "Active" | "Defeated" | ...
	Deadline      uint64                 `protobuf:"varint,2,opt,name=deadline,proto3" json:"deadline,omitempty"`                         // proposal deadline (timepoint)
	Snapshot      uint64                 `protobuf:"varint,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`                         // voting-power snapshot timepoint
	HasVoted      bool                   `protobuf:"varint,4,opt,name=has_voted,json=hasVoted,proto3" json:"has_voted,omitempty"`         // whether the daemon wallet already voted
	VotingPower   []byte                 `protobuf:"bytes,5,opt,name=voting_power,json=votingPower,proto3" json:"voting_power,omitempty"` // big-endian unsigned; power at snapshot
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreasuryProposal) Reset() {
	*x = TreasuryProposal{}
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreasuryProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreasuryProposal) ProtoMessage() {}

func (x *TreasuryProposal) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreasuryProposal.ProtoReflect.Descriptor instead.
func (*TreasuryProposal) Descriptor() ([]byte, []int) {
	return file_livepeer_protocol_v1_protocol_proto_rawDescGZIP(), []int{19}
}

func (x *TreasuryProposal) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TreasuryProposal) GetDeadline() uint64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *TreasuryProposal) GetSnapshot() uint64 {
	if x != nil {
		return x.Snapshot
	}
	return 0
}

func (x *TreasuryProposal) GetHasVoted() bool {
	if x != nil {
		return x.HasVoted
	}
	return false
}

func (x *TreasuryProposal) GetVotingPower() []byte {
	if x != nil {
		return x.VotingPower
	}
	return nil
}

// TxIntentSnapshot mirrors chain-commons.txintent.TxIntent for the wire.
type TxIntentSnapshot struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind                  string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Status                string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "pending"|"signed"|"submitted"|"mined"|"confirmed"|"failed"|"replaced"
	FailedClass           string                 `protobuf:"bytes,4,opt,name=failed_class,json=failedClass,proto3" json:"failed_class,omitempty"`
	FailedCode            string                 `protobuf:"bytes,5,opt,name=failed_code,json=failedCode,proto3" json:"failed_code,omitempty"`
	FailedMessage         string                 `protobuf:"bytes,6,opt,name=failed_message,json=failedMessage,proto3" json:"failed_message,omitempty"`
	CreatedAtUnixNano     uint64                 `protobuf:"varint,7,opt,name=created_at_unix_nano,json=createdAtUnixNano,proto3" json:"created_at_unix_nano,omitempty"`
	LastUpdatedAtUnixNano uint64                 `protobuf:"varint,8,opt,name=last_updated_at_unix_nano,json=lastUpdatedAtUnixNano,proto3" json:"last_updated_at_unix_nano,omitempty"`
	ConfirmedAtUnixNano   uint64                 `protobuf:"varint,9,opt,name=confirmed_at_unix_nano,json=confirmedAtUnixNano,proto3" json:"confirmed_at_unix_nano,omitempty"`
	AttemptCount          uint32                 `protobuf:"varint,10,opt,name=attempt_count,json=attemptCount,proto3" json:"attempt_count,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TxIntentSnapshot) Reset() {
	*x = TxIntentSnapshot{}
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxIntentSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxIntentSnapshot) ProtoMessage() {}

func (x *TxIntentSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_protocol_v1_protocol_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxIntentSnapshot.ProtoReflect.Descriptor instead.
func (*TxIntentSnapshot) Descriptor() ([]byte, []int) {
	return file_livepeer_protocol_v1_protocol_proto_rawDescGZIP(), []int{20}
}

func (x *TxIntentSnapshot) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *TxIntentSnapshot) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TxIntentSnapshot) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TxIntentSnapshot) GetFailedClass() string {
	if x != nil {
		return x.FailedClass
	}
	return ""
}

func (x *TxIntentSnapshot) GetFailedCode() string {
	if x != nil {
		return x.FailedCode
	}
	return ""
}

func (x *TxIntentSnapshot) GetFailedMessage() string {
	if x != nil {
		return x.FailedMessage
	}
	return ""
}

func (x *TxIntentSnapshot) GetCreatedAtUnixNano() uint64 {
	if x != nil {
		return x.CreatedAtUnixNano
	}
	return 0
}

func (x *TxIntentSnapshot) GetLastUpdatedAtUnixNano() uint64 {
	if x != nil {
		return x.LastUpdatedAtUnixNano
	}
	return 0
}

func (x *TxIntentSnapshot) GetConfirmedAtUnixNano() uint64 {
	if x != nil {
		return x.ConfirmedAtUnixNano
	}
	return 0
}

func (x *TxIntentSnapshot) GetAttemptCount() uint32 {
	if x != nil {
		return x.AttemptCount
	}
	return 0
}

var File_livepeer_protocol_v1_protocol_proto protoreflect.FileDescriptor

const file_livepeer_protocol_v1_protocol_proto_rawDesc = "" +
	"\n" +
	"#livepeer/protocol/v1/protocol.proto\x12\x14livepeer.protocol.v1\"\a\n" +
	"\x05Empty\"g\n" +
	"\fHealthStatus\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x19\n" +
	"\bchain_id\x18\x04 \x01(\x04R\achainId\"\xc4\x01\n" +
	"\n" +
	"RoundEvent\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\x12\x1f\n" +
	"\vstart_block\x18\x02 \x01(\x04R\n" +
	"startBlock\x12$\n" +
	"\x0el1_start_block\x18\x03 \x01(\x04R\fl1StartBlock\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x04R\x06length\x12 \n" +
	"\vinitialized\x18\x05 \x01(\bR\vinitialized\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x06 \x01(\fR\tblockHash\"\xdf\x01\n" +
	"\vRoundStatus\x12\x1d\n" +
	"\n" +
	"last_round\x18\x01 \x01(\x04R\tlastRound\x12$\n" +
	"\x0elast_intent_id\x18\x02 \x01(\fR\flastIntentId\x12\x1d\n" +
	"\n" +
	"last_error\x18\x03 \x01(\tR\tlastError\x12:\n" +
	"\x19current_round_initialized\x18\x04 \x01(\bR\x17currentRoundInitialized\x120\n" +
	"\x14current_round_locked\x18\x05 \x01(\bR\x12currentRoundLocked\"\xcc\x02\n" +
	"\fRewardStatus\x12\x1d\n" +
	"\n" +
	"last_round\x18\x01 \x01(\x04R\tlastRound\x12!\n" +
	"\forch_address\x18\x02 \x01(\fR\vorchAddress\x12\x1a\n" +
	"\beligible\x18\x03 \x01(\bR\beligible\x12-\n" +
	"\x12eligibility_reason\x18\x04 \x01(\tR\x11eligibilityReason\x12*\n" +
	"\x11last_reward_round\x18\x05 \x01(\x04R\x0flastRewardRound\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\x12$\n" +
	"\x0elast_intent_id\x18\a \x01(\fR\flastIntentId\x12&\n" +
	"\x0flast_earned_wei\x18\b \x01(\fR\rlastEarnedWei\x12\x1d\n" +
	"\n" +
	"last_error\x18\t \x01(\tR\tlastError\"\x1d\n" +
	"\vTxIntentRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"(\n" +
	"\x14SetServiceURIRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"*\n" +
	"\x16SetAIServiceURIRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"+\n" +
	"\x17OnChainServiceURIStatus\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"-\n" +
	"\x19OnChainAIServiceURIStatus\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"4\n" +
	"\x12RegistrationStatus\x12\x1e\n" +
	"\n" +
	"registered\x18\x01 \x01(\bR\n" +
	"registered\"6\n" +
	"\x14AIRegistrationStatus\x12\x1e\n" +
	"\n" +
	"registered\x18\x01 \x01(\bR\n" +
	"registered\"]\n" +
	"\x13WalletBalanceStatus\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\fR\rwalletAddress\x12\x1f\n" +
	"\vbalance_wei\x18\x02 \x01(\fR\n" +
	"balanceWei\"\x9a\x01\n" +
	"\fForceOutcome\x12A\n" +
	"\tsubmitted\x18\x01 \x01(\v2!.livepeer.protocol.v1.TxIntentRefH\x00R\tsubmitted\x12<\n" +
	"\askipped\x18\x02 \x01(\v2 .livepeer.protocol.v1.SkipReasonH\x00R\askippedB\t\n" +
	"\aoutcome\"\xd8\x03\n" +
	"\n" +
	"SkipReason\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x129\n" +
	"\x04code\x18\x02 \x01(\x0e2%.livepeer.protocol.v1.SkipReason.CodeR\x04code\"\xf6\x02\n" +
	"\x04Code\x12\x14\n" +
	"\x10CODE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CODE_ALREADY_REWARDED\x10\x01\x12\x1c\n" +
	"\x18CODE_TRANSCODER_INACTIVE\x10\x02\x12\x1a\n" +
	"\x16CODE_ROUND_INITIALIZED\x10\x03\x12\x1e\n" +
	"\x1aCODE_ROUND_NOT_INITIALIZED\x10\x04\x12\x19\n" +
	"\x15CODE_REWARD_IN_FLIGHT\x10\x05\x12\x1c\n" +
	"\x18CODE_REWARD_WOULD_REVERT\x10\x06\x12\x1d\n" +
	"\x19CODE_INSUFFICIENT_BALANCE\x10\a\x12\x19\n" +
	"\x15CODE_ROUND_NOT_LOCKED\x10\n" +
	"\x12\x1c\n" +
	"\x18CODE_NOTHING_TO_TRANSFER\x10\v\x12\x1c\n" +
	"\x18CODE_BELOW_FEE_THRESHOLD\x10\f\x12\x1a\n" +
	"\x16CODE_REWARD_NOT_CALLED\x10\r\x12\x18\n" +
	"\x14CODE_ACTION_DISABLED\x10\x0e\"\xe3\x03\n" +
	"\x11OperationalConfig\x12,\n" +
	"\x12round_init_enabled\x18\x01 \x01(\bR\x10roundInitEnabled\x12%\n" +
	"\x0ereward_enabled\x18\x02 \x01(\bR\rrewardEnabled\x124\n" +
	"\x16reward_before_transfer\x18\x03 \x01(\bR\x14rewardBeforeTransfer\x122\n" +
	"\x15transfer_bond_enabled\x18\x04 \x01(\bR\x13transferBondEnabled\x124\n" +
	"\x16transfer_bond_receiver\x18\x05 \x01(\tR\x14transferBondReceiver\x127\n" +
	"\x18transfer_bond_min_retain\x18\x06 \x01(\tR\x15transferBondMinRetain\x122\n" +
	"\x15withdraw_fees_enabled\x18\a \x01(\bR\x13withdrawFeesEnabled\x124\n" +
	"\x16withdraw_fees_receiver\x18\b \x01(\tR\x14withdrawFeesReceiver\x126\n" +
	"\x17withdraw_fees_threshold\x18\t \x01(\tR\x15withdrawFeesThreshold\"N\n" +
	"\x14SetTranscoderRequest\x12\x1d\n" +
	"\n" +
	"reward_cut\x18\x01 \x01(\tR\trewardCut\x12\x17\n" +
	"\afee_cut\x18\x02 \x01(\tR\x06feeCut\"d\n" +
	"\x0fCastVoteRequest\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\x12\x18\n" +
	"\asupport\x18\x02 \x01(\rR\asupport\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"=\n" +
	"\x1aGetTreasuryProposalRequest\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\"\xa0\x01\n" +
	"\x10TreasuryProposal\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1a\n" +
	"\bdeadline\x18\x02 \x01(\x04R\bdeadline\x12\x1a\n" +
	"\bsnapshot\x18\x03 \x01(\x04R\bsnapshot\x12\x1b\n" +
	"\thas_voted\x18\x04 \x01(\bR\bhasVoted\x12!\n" +
	"\fvoting_power\x18\x05 \x01(\fR\vvotingPower\"\xfe\x02\n" +
	"\x10TxIntentSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\ffailed_class\x18\x04 \x01(\tR\vfailedClass\x12\x1f\n" +
	"\vfailed_code\x18\x05 \x01(\tR\n" +
	"failedCode\x12%\n" +
	"\x0efailed_message\x18\x06 \x01(\tR\rfailedMessage\x12/\n" +
	"\x14created_at_unix_nano\x18\a \x01(\x04R\x11createdAtUnixNano\x128\n" +
	"\x19last_updated_at_unix_nano\x18\b \x01(\x04R\x15lastUpdatedAtUnixNano\x123\n" +
	"\x16confirmed_at_unix_nano\x18\t \x01(\x04R\x13confirmedAtUnixNano\x12#\n" +
	"\rattempt_count\x18\n" +
	" \x01(\rR\fattemptCount2\x81\x0f\n" +
	"\x0eProtocolDaemon\x12P\n" +
	"\x0eGetRoundStatus\x12\x1b.livepeer.protocol.v1.Empty\x1a!.livepeer.protocol.v1.RoundStatus\x12R\n" +
	"\x0fGetRewardStatus\x12\x1b.livepeer.protocol.v1.Empty\x1a\".livepeer.protocol.v1.RewardStatus\x12W\n" +
	"\x14ForceInitializeRound\x12\x1b.livepeer.protocol.v1.Empty\x1a\".livepeer.protocol.v1.ForceOutcome\x12R\n" +
	"\x0fForceRewardCall\x12\x1b.livepeer.protocol.v1.Empty\x1a\".livepeer.protocol.v1.ForceOutcome\x12^\n" +
	"\rSetServiceURI\x12*.livepeer.protocol.v1.SetServiceURIRequest\x1a!.livepeer.protocol.v1.TxIntentRef\x12b\n" +
	"\x0fSetAIServiceURI\x12,.livepeer.protocol.v1.SetAIServiceURIRequest\x1a!.livepeer.protocol.v1.TxIntentRef\x12b\n" +
	"\x14GetOnChainServiceURI\x12\x1b.livepeer.protocol.v1.Empty\x1a-.livepeer.protocol.v1.OnChainServiceURIStatus\x12f\n" +
	"\x16GetOnChainAIServiceURI\x12\x1b.livepeer.protocol.v1.Empty\x1a/.livepeer.protocol.v1.OnChainAIServiceURIStatus\x12U\n" +
	"\fIsRegistered\x12\x1b.livepeer.protocol.v1.Empty\x1a(.livepeer.protocol.v1.RegistrationStatus\x12Y\n" +
	"\x0eIsAIRegistered\x12\x1b.livepeer.protocol.v1.Empty\x1a*.livepeer.protocol.v1.AIRegistrationStatus\x12Z\n" +
	"\x10GetWalletBalance\x12\x1b.livepeer.protocol.v1.Empty\x1a).livepeer.protocol.v1.WalletBalanceStatus\x12X\n" +
	"\vGetTxIntent\x12!.livepeer.protocol.v1.TxIntentRef\x1a&.livepeer.protocol.v1.TxIntentSnapshot\x12T\n" +
	"\x11StreamRoundEvents\x12\x1b.livepeer.protocol.v1.Empty\x1a .livepeer.protocol.v1.RoundEvent0\x01\x12I\n" +
	"\x06Health\x12\x1b.livepeer.protocol.v1.Empty\x1a\".livepeer.protocol.v1.HealthStatus\x12Q\n" +
	"\tGetConfig\x12\x1b.livepeer.protocol.v1.Empty\x1a'.livepeer.protocol.v1.OperationalConfig\x12]\n" +
	"\tSetConfig\x12'.livepeer.protocol.v1.OperationalConfig\x1a'.livepeer.protocol.v1.OperationalConfig\x12^\n" +
	"\rSetTranscoder\x12*.livepeer.protocol.v1.SetTranscoderRequest\x1a!.livepeer.protocol.v1.TxIntentRef\x12T\n" +
	"\x11ForceTransferBond\x12\x1b.livepeer.protocol.v1.Empty\x1a\".livepeer.protocol.v1.ForceOutcome\x12T\n" +
	"\x11ForceWithdrawFees\x12\x1b.livepeer.protocol.v1.Empty\x1a\".livepeer.protocol.v1.ForceOutcome\x12T\n" +
	"\bCastVote\x12%.livepeer.protocol.v1.CastVoteRequest\x1a!.livepeer.protocol.v1.TxIntentRef\x12o\n" +
	"\x13GetTreasuryProposal\x120.livepeer.protocol.v1.GetTreasuryProposalRequest\x1a&.livepeer.protocol.v1.TreasuryProposalB_Z]github.com/Cloud-SPE/livepeer-network-modules/proto-contracts/livepeer/protocol/v1;protocolv1b\x06proto3"

var (
	file_livepeer_protocol_v1_protocol_proto_rawDescOnce sync.Once
	file_livepeer_protocol_v1_protocol_proto_rawDescData []byte
)

func file_livepeer_protocol_v1_protocol_proto_rawDescGZIP() []byte {
	file_livepeer_protocol_v1_protocol_proto_rawDescOnce.Do(func() {
		file_livepeer_protocol_v1_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_livepeer_protocol_v1_protocol_proto_rawDesc), len(file_livepeer_protocol_v1_protocol_proto_rawDesc)))
	})
	return file_livepeer_protocol_v1_protocol_proto_rawDescData
}

var file_livepeer_protocol_v1_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_livepeer_protocol_v1_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_livepeer_protocol_v1_protocol_proto_goTypes = []any{
	(SkipReason_Code)(0),               // 0: livepeer.protocol.v1.SkipReason.Code
	(*Empty)(nil),                      // 1: livepeer.protocol.v1.Empty
	(*HealthStatus)(nil),               // 2: livepeer.protocol.v1.HealthStatus
	(*RoundEvent)(nil),                 // 3: livepeer.protocol.v1.RoundEvent
	(*RoundStatus)(nil),                // 4: livepeer.protocol.v1.RoundStatus
	(*RewardStatus)(nil),               // 5: livepeer.protocol.v1.RewardStatus
	(*TxIntentRef)(nil),                // 6: livepeer.protocol.v1.TxIntentRef
	(*SetServiceURIRequest)(nil),       // 7: livepeer.protocol.v1.SetServiceURIRequest
	(*SetAIServiceURIRequest)(nil),     // 8: livepeer.protocol.v1.SetAIServiceURIRequest
	(*OnChainServiceURIStatus)(nil),    // 9: livepeer.protocol.v1.OnChainServiceURIStatus
	(*OnChainAIServiceURIStatus)(nil),  // 10: livepeer.protocol.v1.OnChainAIServiceURIStatus
	(*RegistrationStatus)(nil),         // 11: livepeer.protocol.v1.RegistrationStatus
	(*AIRegistrationStatus)(nil),       // 12: livepeer.protocol.v1.AIRegistrationStatus
	(*WalletBalanceStatus)(nil),        // 13: livepeer.protocol.v1.WalletBalanceStatus
	(*ForceOutcome)(nil),               // 14: livepeer.protocol.v1.ForceOutcome
	(*SkipReason)(nil),                 // 15: livepeer.protocol.v1.SkipReason
	(*OperationalConfig)(nil),          // 16: livepeer.protocol.v1.OperationalConfig
	(*SetTranscoderRequest)(nil),       // 17: livepeer.protocol.v1.SetTranscoderRequest
	(*CastVoteRequest)(nil),            // 18: livepeer.protocol.v1.CastVoteRequest
	(*GetTreasuryProposalRequest)(nil), // 19: livepeer.protocol.v1.GetTreasuryProposalRequest
	(*TreasuryProposal)(nil),           // 20: livepeer.protocol.v1.TreasuryProposal
	(*TxIntentSnapshot)(nil),           // 21: livepeer.protocol.v1.TxIntentSnapshot
}
var file_livepeer_protocol_v1_protocol_proto_depIdxs = []int32{
	6,  // 0: livepeer.protocol.v1.ForceOutcome.submitted:type_name -> livepeer.protocol.v1.TxIntentRef
	15, // 1: livepeer.protocol.v1.ForceOutcome.skipped:type_name -> livepeer.protocol.v1.SkipReason
	0,  // 2: livepeer.protocol.v1.SkipReason.code:type_name -> livepeer.protocol.v1.SkipReason.Code
	1,  // 3: livepeer.protocol.v1.ProtocolDaemon.GetRoundStatus:input_type -> livepeer.protocol.v1.Empty
	1,  // 4: livepeer.protocol.v1.ProtocolDaemon.GetRewardStatus:input_type -> livepeer.protocol.v1.Empty
	1,  // 5: livepeer.protocol.v1.ProtocolDaemon.ForceInitializeRound:input_type -> livepeer.protocol.v1.Empty
	1,  // 6: livepeer.protocol.v1.ProtocolDaemon.ForceRewardCall:input_type -> livepeer.protocol.v1.Empty
	7,  // 7: livepeer.protocol.v1.ProtocolDaemon.SetServiceURI:input_type -> livepeer.protocol.v1.SetServiceURIRequest
	8,  // 8: livepeer.protocol.v1.ProtocolDaemon.SetAIServiceURI:input_type -> livepeer.protocol.v1.SetAIServiceURIRequest
	1,  // 9: livepeer.protocol.v1.ProtocolDaemon.GetOnChainServiceURI:input_type -> livepeer.protocol.v1.Empty
	1,  // 10: livepeer.protocol.v1.ProtocolDaemon.GetOnChainAIServiceURI:input_type -> livepeer.protocol.v1.Empty
	1,  // 11: livepeer.protocol.v1.ProtocolDaemon.IsRegistered:input_type -> livepeer.protocol.v1.Empty
	1,  // 12: livepeer.protocol.v1.ProtocolDaemon.IsAIRegistered:input_type -> livepeer.protocol.v1.Empty
	1,  // 13: livepeer.protocol.v1.ProtocolDaemon.GetWalletBalance:input_type -> livepeer.protocol.v1.Empty
	6,  // 14: livepeer.protocol.v1.ProtocolDaemon.GetTxIntent:input_type -> livepeer.protocol.v1.TxIntentRef
	1,  // 15: livepeer.protocol.v1.ProtocolDaemon.StreamRoundEvents:input_type -> livepeer.protocol.v1.Empty
	1,  // 16: livepeer.protocol.v1.ProtocolDaemon.Health:input_type -> livepeer.protocol.v1.Empty
	1,  // 17: livepeer.protocol.v1.ProtocolDaemon.GetConfig:input_type -> livepeer.protocol.v1.Empty
	16, // 18: livepeer.protocol.v1.ProtocolDaemon.SetConfig:input_type -> livepeer.protocol.v1.OperationalConfig
	17, // 19: livepeer.protocol.v1.ProtocolDaemon.SetTranscoder:input_type -> livepeer.protocol.v1.SetTranscoderRequest
	1,  // 20: livepeer.protocol.v1.ProtocolDaemon.ForceTransferBond:input_type -> livepeer.protocol.v1.Empty
	1,  // 21: livepeer.protocol.v1.ProtocolDaemon.ForceWithdrawFees:input_type -> livepeer.protocol.v1.Empty
	18, // 22: livepeer.protocol.v1.ProtocolDaemon.CastVote:input_type -> livepeer.protocol.v1.CastVoteRequest
	19, // 23: livepeer.protocol.v1.ProtocolDaemon.GetTreasuryProposal:input_type -> livepeer.protocol.v1.GetTreasuryProposalRequest
	4,  // 24: livepeer.protocol.v1.ProtocolDaemon.GetRoundStatus:output_type -> livepeer.protocol.v1.RoundStatus
	5,  // 25: livepeer.protocol.v1.ProtocolDaemon.GetRewardStatus:output_type -> livepeer.protocol.v1.RewardStatus
	14, // 26: livepeer.protocol.v1.ProtocolDaemon.ForceInitializeRound:output_type -> livepeer.protocol.v1.ForceOutcome
	14, // 27: livepeer.protocol.v1.ProtocolDaemon.ForceRewardCall:output_type -> livepeer.protocol.v1.ForceOutcome
	6,  // 28: livepeer.protocol.v1.ProtocolDaemon.SetServiceURI:output_type -> livepeer.protocol.v1.TxIntentRef
	6,  // 29: livepeer.protocol.v1.ProtocolDaemon.SetAIServiceURI:output_type -> livepeer.protocol.v1.TxIntentRef
	9,  // 30: livepeer.protocol.v1.ProtocolDaemon.GetOnChainServiceURI:output_type -> livepeer.protocol.v1.OnChainServiceURIStatus
	10, // 31: livepeer.protocol.v1.ProtocolDaemon.GetOnChainAIServiceURI:output_type -> livepeer.protocol.v1.OnChainAIServiceURIStatus
	11, // 32: livepeer.protocol.v1.ProtocolDaemon.IsRegistered:output_type -> livepeer.protocol.v1.RegistrationStatus
	12, // 33: livepeer.protocol.v1.ProtocolDaemon.IsAIRegistered:output_type -> livepeer.protocol.v1.AIRegistrationStatus
	13, // 34: livepeer.protocol.v1.ProtocolDaemon.GetWalletBalance:output_type -> livepeer.protocol.v1.WalletBalanceStatus
	21, // 35: livepeer.protocol.v1.ProtocolDaemon.GetTxIntent:output_type -> livepeer.protocol.v1.TxIntentSnapshot
	3,  // 36: livepeer.protocol.v1.ProtocolDaemon.StreamRoundEvents:output_type -> livepeer.protocol.v1.RoundEvent
	2,  // 37: livepeer.protocol.v1.ProtocolDaemon.Health:output_type -> livepeer.protocol.v1.HealthStatus
	16, // 38: livepeer.protocol.v1.ProtocolDaemon.GetConfig:output_type -> livepeer.protocol.v1.OperationalConfig
	16, // 39: livepeer.protocol.v1.ProtocolDaemon.SetConfig:output_type -> livepeer.protocol.v1.OperationalConfig
	6,  // 40: livepeer.protocol.v1.ProtocolDaemon.SetTranscoder:output_type -> livepeer.protocol.v1.TxIntentRef
	14, // 41: livepeer.protocol.v1.ProtocolDaemon.ForceTransferBond:output_type -> livepeer.protocol.v1.ForceOutcome
	14, // 42: livepeer.protocol.v1.ProtocolDaemon.ForceWithdrawFees:output_type -> livepeer.protocol.v1.ForceOutcome
	6,  // 43: livepeer.protocol.v1.ProtocolDaemon.CastVote:output_type -> livepeer.protocol.v1.TxIntentRef
	20, // 44: livepeer.protocol.v1.ProtocolDaemon.GetTreasuryProposal:output_type -> livepeer.protocol.v1.TreasuryProposal
	24, // [24:45] is the sub-list for method output_type
	3,  // [3:24] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_livepeer_protocol_v1_protocol_proto_init() }
func file_livepeer_protocol_v1_protocol_proto_init() {
	if File_livepeer_protocol_v1_protocol_proto != nil {
		return
	}
	file_livepeer_protocol_v1_protocol_proto_msgTypes[13].OneofWrappers = []any{
		(*ForceOutcome_Submitted)(nil),
		(*ForceOutcome_Skipped)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_livepeer_protocol_v1_protocol_proto_rawDesc), len(file_livepeer_protocol_v1_protocol_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_livepeer_protocol_v1_protocol_proto_goTypes,
		DependencyIndexes: file_livepeer_protocol_v1_protocol_proto_depIdxs,
		EnumInfos:         file_livepeer_protocol_v1_protocol_proto_enumTypes,
		MessageInfos:      file_livepeer_protocol_v1_protocol_proto_msgTypes,
	}.Build()
	File_livepeer_protocol_v1_protocol_proto = out.File
	file_livepeer_protocol_v1_protocol_proto_goTypes = nil
	file_livepeer_protocol_v1_protocol_proto_depIdxs = nil
}
