// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: livepeer/registry/v1/publisher.proto

package registryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EthAddress    string                 `protobuf:"bytes,1,opt,name=eth_address,json=ethAddress,proto3" json:"eth_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityResult) Reset() {
	*x = IdentityResult{}
	mi := &file_livepeer_registry_v1_publisher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityResult) ProtoMessage() {}

func (x *IdentityResult) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_publisher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityResult.ProtoReflect.Descriptor instead.
func (*IdentityResult) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_publisher_proto_rawDescGZIP(), []int{0}
}

func (x *IdentityResult) GetEthAddress() string {
	if x != nil {
		return x.EthAddress
	}
	return ""
}

type BuildManifestRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProposedEthAddress string                 `protobuf:"bytes,1,opt,name=proposed_eth_address,json=proposedEthAddress,proto3" json:"proposed_eth_address,omitempty"`
	ProposedNodes      []*Node                `protobuf:"bytes,2,rep,name=proposed_nodes,json=proposedNodes,proto3" json:"proposed_nodes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BuildManifestRequest) Reset() {
	*x = BuildManifestRequest{}
	mi := &file_livepeer_registry_v1_publisher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildManifestRequest) ProtoMessage() {}

func (x *BuildManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_publisher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildManifestRequest.ProtoReflect.Descriptor instead.
func (*BuildManifestRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_publisher_proto_rawDescGZIP(), []int{1}
}

func (x *BuildManifestRequest) GetProposedEthAddress() string {
	if x != nil {
		return x.ProposedEthAddress
	}
	return ""
}

func (x *BuildManifestRequest) GetProposedNodes() []*Node {
	if x != nil {
		return x.ProposedNodes
	}
	return nil
}

type BuildResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ManifestJson    []byte                 `protobuf:"bytes,1,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	CanonicalBytes  []byte                 `protobuf:"bytes,2,opt,name=canonical_bytes,json=canonicalBytes,proto3" json:"canonical_bytes,omitempty"`
	CanonicalSha256 string                 `protobuf:"bytes,3,opt,name=canonical_sha256,json=canonicalSha256,proto3" json:"canonical_sha256,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BuildResult) Reset() {
	*x = BuildResult{}
	mi := &file_livepeer_registry_v1_publisher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResult) ProtoMessage() {}

func (x *BuildResult) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_publisher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResult.ProtoReflect.Descriptor instead.
func (*BuildResult) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_publisher_proto_rawDescGZIP(), []int{2}
}

func (x *BuildResult) GetManifestJson() []byte {
	if x != nil {
		return x.ManifestJson
	}
	return nil
}

func (x *BuildResult) GetCanonicalBytes() []byte {
	if x != nil {
		return x.CanonicalBytes
	}
	return nil
}

func (x *BuildResult) GetCanonicalSha256() string {
	if x != nil {
		return x.CanonicalSha256
	}
	return ""
}

// BuildAndSignRequest is the operator-facing one-shot path: the daemon
// validates the proposal eth_address against the loaded cold key, builds
// the canonical manifest from `proposed_nodes`, and signs it with the
// loaded keystore in a single round-trip. Driven from the secure orch
// by the livepeer-registry-refresh CLI when capacity changes.
//
// HTTP probe-from-URL discovery is a follow-up — for v1, callers
// supply fully-formed Nodes (operator hand-curates or uses their own
// inventory tooling). See tech-debt: publisher-http-probe-impl.
type BuildAndSignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManifestJson  []byte                 `protobuf:"bytes,1,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildAndSignRequest) Reset() {
	*x = BuildAndSignRequest{}
	mi := &file_livepeer_registry_v1_publisher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildAndSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildAndSignRequest) ProtoMessage() {}

func (x *BuildAndSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_publisher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildAndSignRequest.ProtoReflect.Descriptor instead.
func (*BuildAndSignRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_publisher_proto_rawDescGZIP(), []int{3}
}

func (x *BuildAndSignRequest) GetManifestJson() []byte {
	if x != nil {
		return x.ManifestJson
	}
	return nil
}

type SignManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManifestJson  []byte                 `protobuf:"bytes,1,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignManifestRequest) Reset() {
	*x = SignManifestRequest{}
	mi := &file_livepeer_registry_v1_publisher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignManifestRequest) ProtoMessage() {}

func (x *SignManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_publisher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignManifestRequest.ProtoReflect.Descriptor instead.
func (*SignManifestRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_publisher_proto_rawDescGZIP(), []int{4}
}

func (x *SignManifestRequest) GetManifestJson() []byte {
	if x != nil {
		return x.ManifestJson
	}
	return nil
}

type SignedManifest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ManifestJson   []byte                 `protobuf:"bytes,1,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	SignatureValue string                 `protobuf:"bytes,2,opt,name=signature_value,json=signatureValue,proto3" json:"signature_value,omitempty"` // 0x-prefixed 130-hex
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignedManifest) Reset() {
	*x = SignedManifest{}
	mi := &file_livepeer_registry_v1_publisher_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedManifest) ProtoMessage() {}

func (x *SignedManifest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_publisher_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedManifest.ProtoReflect.Descriptor instead.
func (*SignedManifest) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_publisher_proto_rawDescGZIP(), []int{5}
}

func (x *SignedManifest) GetManifestJson() []byte {
	if x != nil {
		return x.ManifestJson
	}
	return nil
}

func (x *SignedManifest) GetSignatureValue() string {
	if x != nil {
		return x.SignatureValue
	}
	return ""
}

type TxHashResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxHashResult) Reset() {
	*x = TxHashResult{}
	mi := &file_livepeer_registry_v1_publisher_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxHashResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxHashResult) ProtoMessage() {}

func (x *TxHashResult) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_publisher_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxHashResult.ProtoReflect.Descriptor instead.
func (*TxHashResult) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_publisher_proto_rawDescGZIP(), []int{6}
}

func (x *TxHashResult) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type ProbeWorkerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Url            string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProbeWorkerRequest) Reset() {
	*x = ProbeWorkerRequest{}
	mi := &file_livepeer_registry_v1_publisher_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeWorkerRequest) ProtoMessage() {}

func (x *ProbeWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_publisher_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeWorkerRequest.ProtoReflect.Descriptor instead.
func (*ProbeWorkerRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_publisher_proto_rawDescGZIP(), []int{7}
}

func (x *ProbeWorkerRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProbeWorkerRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ProbeResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CapabilitiesJson []byte                 `protobuf:"bytes,1,opt,name=capabilities_json,json=capabilitiesJson,proto3" json:"capabilities_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProbeResult) Reset() {
	*x = ProbeResult{}
	mi := &file_livepeer_registry_v1_publisher_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResult) ProtoMessage() {}

func (x *ProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_publisher_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResult.ProtoReflect.Descriptor instead.
func (*ProbeResult) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_publisher_proto_rawDescGZIP(), []int{8}
}

func (x *ProbeResult) GetCapabilitiesJson() []byte {
	if x != nil {
		return x.CapabilitiesJson
	}
	return nil
}

var File_livepeer_registry_v1_publisher_proto protoreflect.FileDescriptor

const file_livepeer_registry_v1_publisher_proto_rawDesc = "" +
	"\n" +
	"$livepeer/registry/v1/publisher.proto\x12\x14livepeer.registry.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a#livepeer/registry/v1/resolver.proto\x1a livepeer/registry/v1/types.proto\"1\n" +
	"\x0eIdentityResult\x12\x1f\n" +
	"\veth_address\x18\x01 \x01(\tR\n" +
	"ethAddress\"\x8b\x01\n" +
	"\x14BuildManifestRequest\x120\n" +
	"\x14proposed_eth_address\x18\x01 \x01(\tR\x12proposedEthAddress\x12A\n" +
	"\x0eproposed_nodes\x18\x02 \x03(\v2\x1a.livepeer.registry.v1.NodeR\rproposedNodes\"\x86\x01\n" +
	"\vBuildResult\x12#\n" +
	"\rmanifest_json\x18\x01 \x01(\fR\fmanifestJson\x12'\n" +
	"\x0fcanonical_bytes\x18\x02 \x01(\fR\x0ecanonicalBytes\x12)\n" +
	"\x10canonical_sha256\x18\x03 \x01(\tR\x0fcanonicalSha256\":\n" +
	"\x13BuildAndSignRequest\x12#\n" +
	"\rmanifest_json\x18\x01 \x01(\fR\fmanifestJson\":\n" +
	"\x13SignManifestRequest\x12#\n" +
	"\rmanifest_json\x18\x01 \x01(\fR\fmanifestJson\"^\n" +
	"\x0eSignedManifest\x12#\n" +
	"\rmanifest_json\x18\x01 \x01(\fR\fmanifestJson\x12'\n" +
	"\x0fsignature_value\x18\x02 \x01(\tR\x0esignatureValue\"'\n" +
	"\fTxHashResult\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\"O\n" +
	"\x12ProbeWorkerRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\":\n" +
	"\vProbeResult\x12+\n" +
	"\x11capabilities_json\x18\x01 \x01(\fR\x10capabilitiesJson2\x9c\x04\n" +
	"\tPublisher\x12K\n" +
	"\vGetIdentity\x12\x16.google.protobuf.Empty\x1a$.livepeer.registry.v1.IdentityResult\x12^\n" +
	"\rBuildManifest\x12*.livepeer.registry.v1.BuildManifestRequest\x1a!.livepeer.registry.v1.BuildResult\x12_\n" +
	"\fSignManifest\x12).livepeer.registry.v1.SignManifestRequest\x1a$.livepeer.registry.v1.SignedManifest\x12_\n" +
	"\fBuildAndSign\x12).livepeer.registry.v1.BuildAndSignRequest\x1a$.livepeer.registry.v1.SignedManifest\x12Z\n" +
	"\vProbeWorker\x12(.livepeer.registry.v1.ProbeWorkerRequest\x1a!.livepeer.registry.v1.ProbeResult\x12D\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a\".livepeer.registry.v1.HealthResultB_Z]github.com/Cloud-SPE/livepeer-network-rewrite/proto-contracts/livepeer/registry/v1;registryv1b\x06proto3"

var (
	file_livepeer_registry_v1_publisher_proto_rawDescOnce sync.Once
	file_livepeer_registry_v1_publisher_proto_rawDescData []byte
)

func file_livepeer_registry_v1_publisher_proto_rawDescGZIP() []byte {
	file_livepeer_registry_v1_publisher_proto_rawDescOnce.Do(func() {
		file_livepeer_registry_v1_publisher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_livepeer_registry_v1_publisher_proto_rawDesc), len(file_livepeer_registry_v1_publisher_proto_rawDesc)))
	})
	return file_livepeer_registry_v1_publisher_proto_rawDescData
}

var file_livepeer_registry_v1_publisher_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_livepeer_registry_v1_publisher_proto_goTypes = []any{
	(*IdentityResult)(nil),       // 0: livepeer.registry.v1.IdentityResult
	(*BuildManifestRequest)(nil), // 1: livepeer.registry.v1.BuildManifestRequest
	(*BuildResult)(nil),          // 2: livepeer.registry.v1.BuildResult
	(*BuildAndSignRequest)(nil),  // 3: livepeer.registry.v1.BuildAndSignRequest
	(*SignManifestRequest)(nil),  // 4: livepeer.registry.v1.SignManifestRequest
	(*SignedManifest)(nil),       // 5: livepeer.registry.v1.SignedManifest
	(*TxHashResult)(nil),         // 6: livepeer.registry.v1.TxHashResult
	(*ProbeWorkerRequest)(nil),   // 7: livepeer.registry.v1.ProbeWorkerRequest
	(*ProbeResult)(nil),          // 8: livepeer.registry.v1.ProbeResult
	(*Node)(nil),                 // 9: livepeer.registry.v1.Node
	(*emptypb.Empty)(nil),        // 10: google.protobuf.Empty
	(*HealthResult)(nil),         // 11: livepeer.registry.v1.HealthResult
}
var file_livepeer_registry_v1_publisher_proto_depIdxs = []int32{
	9,  // 0: livepeer.registry.v1.BuildManifestRequest.proposed_nodes:type_name -> livepeer.registry.v1.Node
	10, // 1: livepeer.registry.v1.Publisher.GetIdentity:input_type -> google.protobuf.Empty
	1,  // 2: livepeer.registry.v1.Publisher.BuildManifest:input_type -> livepeer.registry.v1.BuildManifestRequest
	4,  // 3: livepeer.registry.v1.Publisher.SignManifest:input_type -> livepeer.registry.v1.SignManifestRequest
	3,  // 4: livepeer.registry.v1.Publisher.BuildAndSign:input_type -> livepeer.registry.v1.BuildAndSignRequest
	7,  // 5: livepeer.registry.v1.Publisher.ProbeWorker:input_type -> livepeer.registry.v1.ProbeWorkerRequest
	10, // 6: livepeer.registry.v1.Publisher.Health:input_type -> google.protobuf.Empty
	0,  // 7: livepeer.registry.v1.Publisher.GetIdentity:output_type -> livepeer.registry.v1.IdentityResult
	2,  // 8: livepeer.registry.v1.Publisher.BuildManifest:output_type -> livepeer.registry.v1.BuildResult
	5,  // 9: livepeer.registry.v1.Publisher.SignManifest:output_type -> livepeer.registry.v1.SignedManifest
	5,  // 10: livepeer.registry.v1.Publisher.BuildAndSign:output_type -> livepeer.registry.v1.SignedManifest
	8,  // 11: livepeer.registry.v1.Publisher.ProbeWorker:output_type -> livepeer.registry.v1.ProbeResult
	11, // 12: livepeer.registry.v1.Publisher.Health:output_type -> livepeer.registry.v1.HealthResult
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_livepeer_registry_v1_publisher_proto_init() }
func file_livepeer_registry_v1_publisher_proto_init() {
	if File_livepeer_registry_v1_publisher_proto != nil {
		return
	}
	file_livepeer_registry_v1_resolver_proto_init()
	file_livepeer_registry_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_livepeer_registry_v1_publisher_proto_rawDesc), len(file_livepeer_registry_v1_publisher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_livepeer_registry_v1_publisher_proto_goTypes,
		DependencyIndexes: file_livepeer_registry_v1_publisher_proto_depIdxs,
		MessageInfos:      file_livepeer_registry_v1_publisher_proto_msgTypes,
	}.Build()
	File_livepeer_registry_v1_publisher_proto = out.File
	file_livepeer_registry_v1_publisher_proto_goTypes = nil
	file_livepeer_registry_v1_publisher_proto_depIdxs = nil
}
