// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: livepeer/registry/v1/publisher.proto

package registryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EthAddress    string                 `protobuf:"bytes,1,opt,name=eth_address,json=ethAddress,proto3" json:"eth_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityResult) Reset() {
	*x = IdentityResult{}
	mi := &file_livepeer_registry_v1_publisher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityResult) ProtoMessage() {}

func (x *IdentityResult) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_publisher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityResult.ProtoReflect.Descriptor instead.
func (*IdentityResult) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_publisher_proto_rawDescGZIP(), []int{0}
}

func (x *IdentityResult) GetEthAddress() string {
	if x != nil {
		return x.EthAddress
	}
	return ""
}

var File_livepeer_registry_v1_publisher_proto protoreflect.FileDescriptor

const file_livepeer_registry_v1_publisher_proto_rawDesc = "" +
	"\n" +
	"$livepeer/registry/v1/publisher.proto\x12\x14livepeer.registry.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a#livepeer/registry/v1/resolver.proto\"1\n" +
	"\x0eIdentityResult\x12\x1f\n" +
	"\veth_address\x18\x01 \x01(\tR\n" +
	"ethAddress2\x9e\x01\n" +
	"\tPublisher\x12K\n" +
	"\vGetIdentity\x12\x16.google.protobuf.Empty\x1a$.livepeer.registry.v1.IdentityResult\x12D\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a\".livepeer.registry.v1.HealthResultB_Z]github.com/Cloud-SPE/livepeer-network-modules/proto-contracts/livepeer/registry/v1;registryv1b\x06proto3"

var (
	file_livepeer_registry_v1_publisher_proto_rawDescOnce sync.Once
	file_livepeer_registry_v1_publisher_proto_rawDescData []byte
)

func file_livepeer_registry_v1_publisher_proto_rawDescGZIP() []byte {
	file_livepeer_registry_v1_publisher_proto_rawDescOnce.Do(func() {
		file_livepeer_registry_v1_publisher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_livepeer_registry_v1_publisher_proto_rawDesc), len(file_livepeer_registry_v1_publisher_proto_rawDesc)))
	})
	return file_livepeer_registry_v1_publisher_proto_rawDescData
}

var file_livepeer_registry_v1_publisher_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_livepeer_registry_v1_publisher_proto_goTypes = []any{
	(*IdentityResult)(nil), // 0: livepeer.registry.v1.IdentityResult
	(*emptypb.Empty)(nil),  // 1: google.protobuf.Empty
	(*HealthResult)(nil),   // 2: livepeer.registry.v1.HealthResult
}
var file_livepeer_registry_v1_publisher_proto_depIdxs = []int32{
	1, // 0: livepeer.registry.v1.Publisher.GetIdentity:input_type -> google.protobuf.Empty
	1, // 1: livepeer.registry.v1.Publisher.Health:input_type -> google.protobuf.Empty
	0, // 2: livepeer.registry.v1.Publisher.GetIdentity:output_type -> livepeer.registry.v1.IdentityResult
	2, // 3: livepeer.registry.v1.Publisher.Health:output_type -> livepeer.registry.v1.HealthResult
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_livepeer_registry_v1_publisher_proto_init() }
func file_livepeer_registry_v1_publisher_proto_init() {
	if File_livepeer_registry_v1_publisher_proto != nil {
		return
	}
	file_livepeer_registry_v1_resolver_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_livepeer_registry_v1_publisher_proto_rawDesc), len(file_livepeer_registry_v1_publisher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_livepeer_registry_v1_publisher_proto_goTypes,
		DependencyIndexes: file_livepeer_registry_v1_publisher_proto_depIdxs,
		MessageInfos:      file_livepeer_registry_v1_publisher_proto_msgTypes,
	}.Build()
	File_livepeer_registry_v1_publisher_proto = out.File
	file_livepeer_registry_v1_publisher_proto_goTypes = nil
	file_livepeer_registry_v1_publisher_proto_depIdxs = nil
}
