// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: livepeer/registry/v1/resolver.proto

package registryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveByAddressRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EthAddress          string                 `protobuf:"bytes,1,opt,name=eth_address,json=ethAddress,proto3" json:"eth_address,omitempty"`
	AllowLegacyFallback bool                   `protobuf:"varint,2,opt,name=allow_legacy_fallback,json=allowLegacyFallback,proto3" json:"allow_legacy_fallback,omitempty"`
	AllowUnsigned       bool                   `protobuf:"varint,3,opt,name=allow_unsigned,json=allowUnsigned,proto3" json:"allow_unsigned,omitempty"`
	ForceRefresh        bool                   `protobuf:"varint,4,opt,name=force_refresh,json=forceRefresh,proto3" json:"force_refresh,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ResolveByAddressRequest) Reset() {
	*x = ResolveByAddressRequest{}
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveByAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveByAddressRequest) ProtoMessage() {}

func (x *ResolveByAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveByAddressRequest.ProtoReflect.Descriptor instead.
func (*ResolveByAddressRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_resolver_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveByAddressRequest) GetEthAddress() string {
	if x != nil {
		return x.EthAddress
	}
	return ""
}

func (x *ResolveByAddressRequest) GetAllowLegacyFallback() bool {
	if x != nil {
		return x.AllowLegacyFallback
	}
	return false
}

func (x *ResolveByAddressRequest) GetAllowUnsigned() bool {
	if x != nil {
		return x.AllowUnsigned
	}
	return false
}

func (x *ResolveByAddressRequest) GetForceRefresh() bool {
	if x != nil {
		return x.ForceRefresh
	}
	return false
}

type ResolveResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EthAddress      string                 `protobuf:"bytes,1,opt,name=eth_address,json=ethAddress,proto3" json:"eth_address,omitempty"`
	ResolvedUri     string                 `protobuf:"bytes,2,opt,name=resolved_uri,json=resolvedUri,proto3" json:"resolved_uri,omitempty"`
	Mode            ResolveMode            `protobuf:"varint,3,opt,name=mode,proto3,enum=livepeer.registry.v1.ResolveMode" json:"mode,omitempty"`
	Nodes           []*Node                `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	FreshnessStatus FreshnessStatus        `protobuf:"varint,5,opt,name=freshness_status,json=freshnessStatus,proto3,enum=livepeer.registry.v1.FreshnessStatus" json:"freshness_status,omitempty"`
	CachedAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=cached_at,json=cachedAt,proto3" json:"cached_at,omitempty"`
	FetchedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"`
	SchemaVersion   string                 `protobuf:"bytes,8,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResolveResult) Reset() {
	*x = ResolveResult{}
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResult) ProtoMessage() {}

func (x *ResolveResult) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResult.ProtoReflect.Descriptor instead.
func (*ResolveResult) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_resolver_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveResult) GetEthAddress() string {
	if x != nil {
		return x.EthAddress
	}
	return ""
}

func (x *ResolveResult) GetResolvedUri() string {
	if x != nil {
		return x.ResolvedUri
	}
	return ""
}

func (x *ResolveResult) GetMode() ResolveMode {
	if x != nil {
		return x.Mode
	}
	return ResolveMode_RESOLVE_MODE_UNSPECIFIED
}

func (x *ResolveResult) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ResolveResult) GetFreshnessStatus() FreshnessStatus {
	if x != nil {
		return x.FreshnessStatus
	}
	return FreshnessStatus_FRESHNESS_STATUS_UNSPECIFIED
}

func (x *ResolveResult) GetCachedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CachedAt
	}
	return nil
}

func (x *ResolveResult) GetFetchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FetchedAt
	}
	return nil
}

func (x *ResolveResult) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

type SelectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	Offering      string                 `protobuf:"bytes,2,opt,name=offering,proto3" json:"offering,omitempty"`
	Tier          string                 `protobuf:"bytes,3,opt,name=tier,proto3" json:"tier,omitempty"`
	MinWeight     int32                  `protobuf:"varint,4,opt,name=min_weight,json=minWeight,proto3" json:"min_weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectRequest) Reset() {
	*x = SelectRequest{}
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectRequest) ProtoMessage() {}

func (x *SelectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectRequest.ProtoReflect.Descriptor instead.
func (*SelectRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_resolver_proto_rawDescGZIP(), []int{2}
}

func (x *SelectRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *SelectRequest) GetOffering() string {
	if x != nil {
		return x.Offering
	}
	return ""
}

func (x *SelectRequest) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *SelectRequest) GetMinWeight() int32 {
	if x != nil {
		return x.MinWeight
	}
	return 0
}

type SelectResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *SelectedRoute         `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectResult) Reset() {
	*x = SelectResult{}
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectResult) ProtoMessage() {}

func (x *SelectResult) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectResult.ProtoReflect.Descriptor instead.
func (*SelectResult) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_resolver_proto_rawDescGZIP(), []int{3}
}

func (x *SelectResult) GetRoute() *SelectedRoute {
	if x != nil {
		return x.Route
	}
	return nil
}

type SelectedRoute struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WorkerUrl           string                 `protobuf:"bytes,1,opt,name=worker_url,json=workerUrl,proto3" json:"worker_url,omitempty"`
	EthAddress          string                 `protobuf:"bytes,2,opt,name=eth_address,json=ethAddress,proto3" json:"eth_address,omitempty"`
	Capability          string                 `protobuf:"bytes,3,opt,name=capability,proto3" json:"capability,omitempty"`
	Offering            string                 `protobuf:"bytes,4,opt,name=offering,proto3" json:"offering,omitempty"`
	PricePerWorkUnitWei string                 `protobuf:"bytes,5,opt,name=price_per_work_unit_wei,json=pricePerWorkUnitWei,proto3" json:"price_per_work_unit_wei,omitempty"`
	WorkUnit            string                 `protobuf:"bytes,6,opt,name=work_unit,json=workUnit,proto3" json:"work_unit,omitempty"`
	ExtraJson           []byte                 `protobuf:"bytes,7,opt,name=extra_json,json=extraJson,proto3" json:"extra_json,omitempty"`
	ConstraintsJson     []byte                 `protobuf:"bytes,8,opt,name=constraints_json,json=constraintsJson,proto3" json:"constraints_json,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SelectedRoute) Reset() {
	*x = SelectedRoute{}
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectedRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectedRoute) ProtoMessage() {}

func (x *SelectedRoute) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectedRoute.ProtoReflect.Descriptor instead.
func (*SelectedRoute) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_resolver_proto_rawDescGZIP(), []int{4}
}

func (x *SelectedRoute) GetWorkerUrl() string {
	if x != nil {
		return x.WorkerUrl
	}
	return ""
}

func (x *SelectedRoute) GetEthAddress() string {
	if x != nil {
		return x.EthAddress
	}
	return ""
}

func (x *SelectedRoute) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *SelectedRoute) GetOffering() string {
	if x != nil {
		return x.Offering
	}
	return ""
}

func (x *SelectedRoute) GetPricePerWorkUnitWei() string {
	if x != nil {
		return x.PricePerWorkUnitWei
	}
	return ""
}

func (x *SelectedRoute) GetWorkUnit() string {
	if x != nil {
		return x.WorkUnit
	}
	return ""
}

func (x *SelectedRoute) GetExtraJson() []byte {
	if x != nil {
		return x.ExtraJson
	}
	return nil
}

func (x *SelectedRoute) GetConstraintsJson() []byte {
	if x != nil {
		return x.ConstraintsJson
	}
	return nil
}

type ListKnownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKnownRequest) Reset() {
	*x = ListKnownRequest{}
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKnownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnownRequest) ProtoMessage() {}

func (x *ListKnownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnownRequest.ProtoReflect.Descriptor instead.
func (*ListKnownRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_resolver_proto_rawDescGZIP(), []int{5}
}

type ListKnownResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*KnownEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKnownResult) Reset() {
	*x = ListKnownResult{}
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKnownResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnownResult) ProtoMessage() {}

func (x *ListKnownResult) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnownResult.ProtoReflect.Descriptor instead.
func (*ListKnownResult) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_resolver_proto_rawDescGZIP(), []int{6}
}

func (x *ListKnownResult) GetEntries() []*KnownEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type KnownEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EthAddress      string                 `protobuf:"bytes,1,opt,name=eth_address,json=ethAddress,proto3" json:"eth_address,omitempty"`
	Mode            ResolveMode            `protobuf:"varint,2,opt,name=mode,proto3,enum=livepeer.registry.v1.ResolveMode" json:"mode,omitempty"`
	FreshnessStatus FreshnessStatus        `protobuf:"varint,3,opt,name=freshness_status,json=freshnessStatus,proto3,enum=livepeer.registry.v1.FreshnessStatus" json:"freshness_status,omitempty"`
	CachedAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=cached_at,json=cachedAt,proto3" json:"cached_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KnownEntry) Reset() {
	*x = KnownEntry{}
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownEntry) ProtoMessage() {}

func (x *KnownEntry) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownEntry.ProtoReflect.Descriptor instead.
func (*KnownEntry) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_resolver_proto_rawDescGZIP(), []int{7}
}

func (x *KnownEntry) GetEthAddress() string {
	if x != nil {
		return x.EthAddress
	}
	return ""
}

func (x *KnownEntry) GetMode() ResolveMode {
	if x != nil {
		return x.Mode
	}
	return ResolveMode_RESOLVE_MODE_UNSPECIFIED
}

func (x *KnownEntry) GetFreshnessStatus() FreshnessStatus {
	if x != nil {
		return x.FreshnessStatus
	}
	return FreshnessStatus_FRESHNESS_STATUS_UNSPECIFIED
}

func (x *KnownEntry) GetCachedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CachedAt
	}
	return nil
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EthAddress    string                 `protobuf:"bytes,1,opt,name=eth_address,json=ethAddress,proto3" json:"eth_address,omitempty"` // "*" means all
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_resolver_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshRequest) GetEthAddress() string {
	if x != nil {
		return x.EthAddress
	}
	return ""
}

func (x *RefreshRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type GetAuditLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EthAddress    string                 `protobuf:"bytes,1,opt,name=eth_address,json=ethAddress,proto3" json:"eth_address,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogRequest) Reset() {
	*x = GetAuditLogRequest{}
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogRequest) ProtoMessage() {}

func (x *GetAuditLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogRequest.ProtoReflect.Descriptor instead.
func (*GetAuditLogRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_resolver_proto_rawDescGZIP(), []int{9}
}

func (x *GetAuditLogRequest) GetEthAddress() string {
	if x != nil {
		return x.EthAddress
	}
	return ""
}

func (x *GetAuditLogRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *GetAuditLogRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AuditLogResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AuditEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogResult) Reset() {
	*x = AuditLogResult{}
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogResult) ProtoMessage() {}

func (x *AuditLogResult) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogResult.ProtoReflect.Descriptor instead.
func (*AuditLogResult) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_resolver_proto_rawDescGZIP(), []int{10}
}

func (x *AuditLogResult) GetEvents() []*AuditEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type AuditEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	At            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	EthAddress    string                 `protobuf:"bytes,2,opt,name=eth_address,json=ethAddress,proto3" json:"eth_address,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Mode          ResolveMode            `protobuf:"varint,4,opt,name=mode,proto3,enum=livepeer.registry.v1.ResolveMode" json:"mode,omitempty"`
	Detail        string                 `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_resolver_proto_rawDescGZIP(), []int{11}
}

func (x *AuditEvent) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *AuditEvent) GetEthAddress() string {
	if x != nil {
		return x.EthAddress
	}
	return ""
}

func (x *AuditEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AuditEvent) GetMode() ResolveMode {
	if x != nil {
		return x.Mode
	}
	return ResolveMode_RESOLVE_MODE_UNSPECIFIED
}

func (x *AuditEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type HealthResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Mode              string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	ChainOk           bool                   `protobuf:"varint,2,opt,name=chain_ok,json=chainOk,proto3" json:"chain_ok,omitempty"`
	ManifestFetcherOk bool                   `protobuf:"varint,3,opt,name=manifest_fetcher_ok,json=manifestFetcherOk,proto3" json:"manifest_fetcher_ok,omitempty"`
	CacheSize         int32                  `protobuf:"varint,4,opt,name=cache_size,json=cacheSize,proto3" json:"cache_size,omitempty"`
	LastChainSuccess  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_chain_success,json=lastChainSuccess,proto3" json:"last_chain_success,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthResult) Reset() {
	*x = HealthResult{}
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResult) ProtoMessage() {}

func (x *HealthResult) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_resolver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResult.ProtoReflect.Descriptor instead.
func (*HealthResult) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_resolver_proto_rawDescGZIP(), []int{12}
}

func (x *HealthResult) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *HealthResult) GetChainOk() bool {
	if x != nil {
		return x.ChainOk
	}
	return false
}

func (x *HealthResult) GetManifestFetcherOk() bool {
	if x != nil {
		return x.ManifestFetcherOk
	}
	return false
}

func (x *HealthResult) GetCacheSize() int32 {
	if x != nil {
		return x.CacheSize
	}
	return 0
}

func (x *HealthResult) GetLastChainSuccess() *timestamppb.Timestamp {
	if x != nil {
		return x.LastChainSuccess
	}
	return nil
}

var File_livepeer_registry_v1_resolver_proto protoreflect.FileDescriptor

const file_livepeer_registry_v1_resolver_proto_rawDesc = "" +
	"\n" +
	"#livepeer/registry/v1/resolver.proto\x12\x14livepeer.registry.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a livepeer/registry/v1/types.proto\"\xba\x01\n" +
	"\x17ResolveByAddressRequest\x12\x1f\n" +
	"\veth_address\x18\x01 \x01(\tR\n" +
	"ethAddress\x122\n" +
	"\x15allow_legacy_fallback\x18\x02 \x01(\bR\x13allowLegacyFallback\x12%\n" +
	"\x0eallow_unsigned\x18\x03 \x01(\bR\rallowUnsigned\x12#\n" +
	"\rforce_refresh\x18\x04 \x01(\bR\fforceRefresh\"\xa9\x03\n" +
	"\rResolveResult\x12\x1f\n" +
	"\veth_address\x18\x01 \x01(\tR\n" +
	"ethAddress\x12!\n" +
	"\fresolved_uri\x18\x02 \x01(\tR\vresolvedUri\x125\n" +
	"\x04mode\x18\x03 \x01(\x0e2!.livepeer.registry.v1.ResolveModeR\x04mode\x120\n" +
	"\x05nodes\x18\x04 \x03(\v2\x1a.livepeer.registry.v1.NodeR\x05nodes\x12P\n" +
	"\x10freshness_status\x18\x05 \x01(\x0e2%.livepeer.registry.v1.FreshnessStatusR\x0ffreshnessStatus\x127\n" +
	"\tcached_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bcachedAt\x129\n" +
	"\n" +
	"fetched_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tfetchedAt\x12%\n" +
	"\x0eschema_version\x18\b \x01(\tR\rschemaVersion\"~\n" +
	"\rSelectRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\x12\x1a\n" +
	"\boffering\x18\x02 \x01(\tR\boffering\x12\x12\n" +
	"\x04tier\x18\x03 \x01(\tR\x04tier\x12\x1d\n" +
	"\n" +
	"min_weight\x18\x04 \x01(\x05R\tminWeight\"I\n" +
	"\fSelectResult\x129\n" +
	"\x05route\x18\x01 \x01(\v2#.livepeer.registry.v1.SelectedRouteR\x05route\"\xa8\x02\n" +
	"\rSelectedRoute\x12\x1d\n" +
	"\n" +
	"worker_url\x18\x01 \x01(\tR\tworkerUrl\x12\x1f\n" +
	"\veth_address\x18\x02 \x01(\tR\n" +
	"ethAddress\x12\x1e\n" +
	"\n" +
	"capability\x18\x03 \x01(\tR\n" +
	"capability\x12\x1a\n" +
	"\boffering\x18\x04 \x01(\tR\boffering\x124\n" +
	"\x17price_per_work_unit_wei\x18\x05 \x01(\tR\x13pricePerWorkUnitWei\x12\x1b\n" +
	"\twork_unit\x18\x06 \x01(\tR\bworkUnit\x12\x1d\n" +
	"\n" +
	"extra_json\x18\a \x01(\fR\textraJson\x12)\n" +
	"\x10constraints_json\x18\b \x01(\fR\x0fconstraintsJson\"\x12\n" +
	"\x10ListKnownRequest\"M\n" +
	"\x0fListKnownResult\x12:\n" +
	"\aentries\x18\x01 \x03(\v2 .livepeer.registry.v1.KnownEntryR\aentries\"\xef\x01\n" +
	"\n" +
	"KnownEntry\x12\x1f\n" +
	"\veth_address\x18\x01 \x01(\tR\n" +
	"ethAddress\x125\n" +
	"\x04mode\x18\x02 \x01(\x0e2!.livepeer.registry.v1.ResolveModeR\x04mode\x12P\n" +
	"\x10freshness_status\x18\x03 \x01(\x0e2%.livepeer.registry.v1.FreshnessStatusR\x0ffreshnessStatus\x127\n" +
	"\tcached_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bcachedAt\"G\n" +
	"\x0eRefreshRequest\x12\x1f\n" +
	"\veth_address\x18\x01 \x01(\tR\n" +
	"ethAddress\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"}\n" +
	"\x12GetAuditLogRequest\x12\x1f\n" +
	"\veth_address\x18\x01 \x01(\tR\n" +
	"ethAddress\x120\n" +
	"\x05since\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"J\n" +
	"\x0eAuditLogResult\x128\n" +
	"\x06events\x18\x01 \x03(\v2 .livepeer.registry.v1.AuditEventR\x06events\"\xbc\x01\n" +
	"\n" +
	"AuditEvent\x12*\n" +
	"\x02at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12\x1f\n" +
	"\veth_address\x18\x02 \x01(\tR\n" +
	"ethAddress\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x125\n" +
	"\x04mode\x18\x04 \x01(\x0e2!.livepeer.registry.v1.ResolveModeR\x04mode\x12\x16\n" +
	"\x06detail\x18\x05 \x01(\tR\x06detail\"\xd6\x01\n" +
	"\fHealthResult\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x19\n" +
	"\bchain_ok\x18\x02 \x01(\bR\achainOk\x12.\n" +
	"\x13manifest_fetcher_ok\x18\x03 \x01(\bR\x11manifestFetcherOk\x12\x1d\n" +
	"\n" +
	"cache_size\x18\x04 \x01(\x05R\tcacheSize\x12H\n" +
	"\x12last_chain_success\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x10lastChainSuccess2\x8f\x04\n" +
	"\bResolver\x12f\n" +
	"\x10ResolveByAddress\x12-.livepeer.registry.v1.ResolveByAddressRequest\x1a#.livepeer.registry.v1.ResolveResult\x12Q\n" +
	"\x06Select\x12#.livepeer.registry.v1.SelectRequest\x1a\".livepeer.registry.v1.SelectResult\x12Z\n" +
	"\tListKnown\x12&.livepeer.registry.v1.ListKnownRequest\x1a%.livepeer.registry.v1.ListKnownResult\x12G\n" +
	"\aRefresh\x12$.livepeer.registry.v1.RefreshRequest\x1a\x16.google.protobuf.Empty\x12]\n" +
	"\vGetAuditLog\x12(.livepeer.registry.v1.GetAuditLogRequest\x1a$.livepeer.registry.v1.AuditLogResult\x12D\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a\".livepeer.registry.v1.HealthResultB_Z]github.com/Cloud-SPE/livepeer-network-rewrite/proto-contracts/livepeer/registry/v1;registryv1b\x06proto3"

var (
	file_livepeer_registry_v1_resolver_proto_rawDescOnce sync.Once
	file_livepeer_registry_v1_resolver_proto_rawDescData []byte
)

func file_livepeer_registry_v1_resolver_proto_rawDescGZIP() []byte {
	file_livepeer_registry_v1_resolver_proto_rawDescOnce.Do(func() {
		file_livepeer_registry_v1_resolver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_livepeer_registry_v1_resolver_proto_rawDesc), len(file_livepeer_registry_v1_resolver_proto_rawDesc)))
	})
	return file_livepeer_registry_v1_resolver_proto_rawDescData
}

var file_livepeer_registry_v1_resolver_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_livepeer_registry_v1_resolver_proto_goTypes = []any{
	(*ResolveByAddressRequest)(nil), // 0: livepeer.registry.v1.ResolveByAddressRequest
	(*ResolveResult)(nil),           // 1: livepeer.registry.v1.ResolveResult
	(*SelectRequest)(nil),           // 2: livepeer.registry.v1.SelectRequest
	(*SelectResult)(nil),            // 3: livepeer.registry.v1.SelectResult
	(*SelectedRoute)(nil),           // 4: livepeer.registry.v1.SelectedRoute
	(*ListKnownRequest)(nil),        // 5: livepeer.registry.v1.ListKnownRequest
	(*ListKnownResult)(nil),         // 6: livepeer.registry.v1.ListKnownResult
	(*KnownEntry)(nil),              // 7: livepeer.registry.v1.KnownEntry
	(*RefreshRequest)(nil),          // 8: livepeer.registry.v1.RefreshRequest
	(*GetAuditLogRequest)(nil),      // 9: livepeer.registry.v1.GetAuditLogRequest
	(*AuditLogResult)(nil),          // 10: livepeer.registry.v1.AuditLogResult
	(*AuditEvent)(nil),              // 11: livepeer.registry.v1.AuditEvent
	(*HealthResult)(nil),            // 12: livepeer.registry.v1.HealthResult
	(ResolveMode)(0),                // 13: livepeer.registry.v1.ResolveMode
	(*Node)(nil),                    // 14: livepeer.registry.v1.Node
	(FreshnessStatus)(0),            // 15: livepeer.registry.v1.FreshnessStatus
	(*timestamppb.Timestamp)(nil),   // 16: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 17: google.protobuf.Empty
}
var file_livepeer_registry_v1_resolver_proto_depIdxs = []int32{
	13, // 0: livepeer.registry.v1.ResolveResult.mode:type_name -> livepeer.registry.v1.ResolveMode
	14, // 1: livepeer.registry.v1.ResolveResult.nodes:type_name -> livepeer.registry.v1.Node
	15, // 2: livepeer.registry.v1.ResolveResult.freshness_status:type_name -> livepeer.registry.v1.FreshnessStatus
	16, // 3: livepeer.registry.v1.ResolveResult.cached_at:type_name -> google.protobuf.Timestamp
	16, // 4: livepeer.registry.v1.ResolveResult.fetched_at:type_name -> google.protobuf.Timestamp
	4,  // 5: livepeer.registry.v1.SelectResult.route:type_name -> livepeer.registry.v1.SelectedRoute
	7,  // 6: livepeer.registry.v1.ListKnownResult.entries:type_name -> livepeer.registry.v1.KnownEntry
	13, // 7: livepeer.registry.v1.KnownEntry.mode:type_name -> livepeer.registry.v1.ResolveMode
	15, // 8: livepeer.registry.v1.KnownEntry.freshness_status:type_name -> livepeer.registry.v1.FreshnessStatus
	16, // 9: livepeer.registry.v1.KnownEntry.cached_at:type_name -> google.protobuf.Timestamp
	16, // 10: livepeer.registry.v1.GetAuditLogRequest.since:type_name -> google.protobuf.Timestamp
	11, // 11: livepeer.registry.v1.AuditLogResult.events:type_name -> livepeer.registry.v1.AuditEvent
	16, // 12: livepeer.registry.v1.AuditEvent.at:type_name -> google.protobuf.Timestamp
	13, // 13: livepeer.registry.v1.AuditEvent.mode:type_name -> livepeer.registry.v1.ResolveMode
	16, // 14: livepeer.registry.v1.HealthResult.last_chain_success:type_name -> google.protobuf.Timestamp
	0,  // 15: livepeer.registry.v1.Resolver.ResolveByAddress:input_type -> livepeer.registry.v1.ResolveByAddressRequest
	2,  // 16: livepeer.registry.v1.Resolver.Select:input_type -> livepeer.registry.v1.SelectRequest
	5,  // 17: livepeer.registry.v1.Resolver.ListKnown:input_type -> livepeer.registry.v1.ListKnownRequest
	8,  // 18: livepeer.registry.v1.Resolver.Refresh:input_type -> livepeer.registry.v1.RefreshRequest
	9,  // 19: livepeer.registry.v1.Resolver.GetAuditLog:input_type -> livepeer.registry.v1.GetAuditLogRequest
	17, // 20: livepeer.registry.v1.Resolver.Health:input_type -> google.protobuf.Empty
	1,  // 21: livepeer.registry.v1.Resolver.ResolveByAddress:output_type -> livepeer.registry.v1.ResolveResult
	3,  // 22: livepeer.registry.v1.Resolver.Select:output_type -> livepeer.registry.v1.SelectResult
	6,  // 23: livepeer.registry.v1.Resolver.ListKnown:output_type -> livepeer.registry.v1.ListKnownResult
	17, // 24: livepeer.registry.v1.Resolver.Refresh:output_type -> google.protobuf.Empty
	10, // 25: livepeer.registry.v1.Resolver.GetAuditLog:output_type -> livepeer.registry.v1.AuditLogResult
	12, // 26: livepeer.registry.v1.Resolver.Health:output_type -> livepeer.registry.v1.HealthResult
	21, // [21:27] is the sub-list for method output_type
	15, // [15:21] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_livepeer_registry_v1_resolver_proto_init() }
func file_livepeer_registry_v1_resolver_proto_init() {
	if File_livepeer_registry_v1_resolver_proto != nil {
		return
	}
	file_livepeer_registry_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_livepeer_registry_v1_resolver_proto_rawDesc), len(file_livepeer_registry_v1_resolver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_livepeer_registry_v1_resolver_proto_goTypes,
		DependencyIndexes: file_livepeer_registry_v1_resolver_proto_depIdxs,
		MessageInfos:      file_livepeer_registry_v1_resolver_proto_msgTypes,
	}.Build()
	File_livepeer_registry_v1_resolver_proto = out.File
	file_livepeer_registry_v1_resolver_proto_goTypes = nil
	file_livepeer_registry_v1_resolver_proto_depIdxs = nil
}
