// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: livepeer/registry/v1/types.proto

package registryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResolveMode mirrors types.ResolveMode in the Go layer. Frozen v1.
type ResolveMode int32

const (
	ResolveMode_RESOLVE_MODE_UNSPECIFIED ResolveMode = 0
	ResolveMode_RESOLVE_MODE_WELL_KNOWN  ResolveMode = 1
	ResolveMode_RESOLVE_MODE_CSV         ResolveMode = 2
	ResolveMode_RESOLVE_MODE_LEGACY      ResolveMode = 3
)

// Enum value maps for ResolveMode.
var (
	ResolveMode_name = map[int32]string{
		0: "RESOLVE_MODE_UNSPECIFIED",
		1: "RESOLVE_MODE_WELL_KNOWN",
		2: "RESOLVE_MODE_CSV",
		3: "RESOLVE_MODE_LEGACY",
	}
	ResolveMode_value = map[string]int32{
		"RESOLVE_MODE_UNSPECIFIED": 0,
		"RESOLVE_MODE_WELL_KNOWN":  1,
		"RESOLVE_MODE_CSV":         2,
		"RESOLVE_MODE_LEGACY":      3,
	}
)

func (x ResolveMode) Enum() *ResolveMode {
	p := new(ResolveMode)
	*p = x
	return p
}

func (x ResolveMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResolveMode) Descriptor() protoreflect.EnumDescriptor {
	return file_livepeer_registry_v1_types_proto_enumTypes[0].Descriptor()
}

func (ResolveMode) Type() protoreflect.EnumType {
	return &file_livepeer_registry_v1_types_proto_enumTypes[0]
}

func (x ResolveMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResolveMode.Descriptor instead.
func (ResolveMode) EnumDescriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_types_proto_rawDescGZIP(), []int{0}
}

// SignatureStatus mirrors types.SignatureStatus.
type SignatureStatus int32

const (
	SignatureStatus_SIGNATURE_STATUS_UNSPECIFIED SignatureStatus = 0
	SignatureStatus_SIGNATURE_STATUS_VERIFIED    SignatureStatus = 1
	SignatureStatus_SIGNATURE_STATUS_UNSIGNED    SignatureStatus = 2
	SignatureStatus_SIGNATURE_STATUS_LEGACY      SignatureStatus = 3
)

// Enum value maps for SignatureStatus.
var (
	SignatureStatus_name = map[int32]string{
		0: "SIGNATURE_STATUS_UNSPECIFIED",
		1: "SIGNATURE_STATUS_VERIFIED",
		2: "SIGNATURE_STATUS_UNSIGNED",
		3: "SIGNATURE_STATUS_LEGACY",
	}
	SignatureStatus_value = map[string]int32{
		"SIGNATURE_STATUS_UNSPECIFIED": 0,
		"SIGNATURE_STATUS_VERIFIED":    1,
		"SIGNATURE_STATUS_UNSIGNED":    2,
		"SIGNATURE_STATUS_LEGACY":      3,
	}
)

func (x SignatureStatus) Enum() *SignatureStatus {
	p := new(SignatureStatus)
	*p = x
	return p
}

func (x SignatureStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignatureStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_livepeer_registry_v1_types_proto_enumTypes[1].Descriptor()
}

func (SignatureStatus) Type() protoreflect.EnumType {
	return &file_livepeer_registry_v1_types_proto_enumTypes[1]
}

func (x SignatureStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignatureStatus.Descriptor instead.
func (SignatureStatus) EnumDescriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_types_proto_rawDescGZIP(), []int{1}
}

// FreshnessStatus mirrors types.FreshnessStatus.
type FreshnessStatus int32

const (
	FreshnessStatus_FRESHNESS_STATUS_UNSPECIFIED       FreshnessStatus = 0
	FreshnessStatus_FRESHNESS_STATUS_FRESH             FreshnessStatus = 1
	FreshnessStatus_FRESHNESS_STATUS_STALE_RECOVERABLE FreshnessStatus = 2
	FreshnessStatus_FRESHNESS_STATUS_STALE_FAILING     FreshnessStatus = 3
)

// Enum value maps for FreshnessStatus.
var (
	FreshnessStatus_name = map[int32]string{
		0: "FRESHNESS_STATUS_UNSPECIFIED",
		1: "FRESHNESS_STATUS_FRESH",
		2: "FRESHNESS_STATUS_STALE_RECOVERABLE",
		3: "FRESHNESS_STATUS_STALE_FAILING",
	}
	FreshnessStatus_value = map[string]int32{
		"FRESHNESS_STATUS_UNSPECIFIED":       0,
		"FRESHNESS_STATUS_FRESH":             1,
		"FRESHNESS_STATUS_STALE_RECOVERABLE": 2,
		"FRESHNESS_STATUS_STALE_FAILING":     3,
	}
)

func (x FreshnessStatus) Enum() *FreshnessStatus {
	p := new(FreshnessStatus)
	*p = x
	return p
}

func (x FreshnessStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FreshnessStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_livepeer_registry_v1_types_proto_enumTypes[2].Descriptor()
}

func (FreshnessStatus) Type() protoreflect.EnumType {
	return &file_livepeer_registry_v1_types_proto_enumTypes[2]
}

func (x FreshnessStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FreshnessStatus.Descriptor instead.
func (FreshnessStatus) EnumDescriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_types_proto_rawDescGZIP(), []int{2}
}

// Source mirrors types.Source.
type Source int32

const (
	Source_SOURCE_UNSPECIFIED    Source = 0
	Source_SOURCE_MANIFEST       Source = 1
	Source_SOURCE_LEGACY         Source = 2
	Source_SOURCE_STATIC_OVERLAY Source = 3
	Source_SOURCE_CSV_FALLBACK   Source = 4
)

// Enum value maps for Source.
var (
	Source_name = map[int32]string{
		0: "SOURCE_UNSPECIFIED",
		1: "SOURCE_MANIFEST",
		2: "SOURCE_LEGACY",
		3: "SOURCE_STATIC_OVERLAY",
		4: "SOURCE_CSV_FALLBACK",
	}
	Source_value = map[string]int32{
		"SOURCE_UNSPECIFIED":    0,
		"SOURCE_MANIFEST":       1,
		"SOURCE_LEGACY":         2,
		"SOURCE_STATIC_OVERLAY": 3,
		"SOURCE_CSV_FALLBACK":   4,
	}
)

func (x Source) Enum() *Source {
	p := new(Source)
	*p = x
	return p
}

func (x Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Source) Descriptor() protoreflect.EnumDescriptor {
	return file_livepeer_registry_v1_types_proto_enumTypes[3].Descriptor()
}

func (Source) Type() protoreflect.EnumType {
	return &file_livepeer_registry_v1_types_proto_enumTypes[3]
}

func (x Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Source.Descriptor instead.
func (Source) EnumDescriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_types_proto_rawDescGZIP(), []int{3}
}

// Capability is one named operation a node advertises. The name is
// opaque to the registry; consumers interpret it.
type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	WorkUnit      string                 `protobuf:"bytes,2,opt,name=work_unit,json=workUnit,proto3" json:"work_unit,omitempty"`
	Offerings     []*Offering            `protobuf:"bytes,3,rep,name=offerings,proto3" json:"offerings,omitempty"`
	ExtraJson     []byte                 `protobuf:"bytes,4,opt,name=extra_json,json=extraJson,proto3" json:"extra_json,omitempty"` // arbitrary JSON, opaque
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_livepeer_registry_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Capability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Capability) GetWorkUnit() string {
	if x != nil {
		return x.WorkUnit
	}
	return ""
}

func (x *Capability) GetOfferings() []*Offering {
	if x != nil {
		return x.Offerings
	}
	return nil
}

func (x *Capability) GetExtraJson() []byte {
	if x != nil {
		return x.ExtraJson
	}
	return nil
}

// Offering is a priced tier under a capability. The id is opaque to the
// registry — for AI workloads it's typically the model name (e.g.
// "gpt-oss-20b"); for video transcoding it's a preset id (e.g.
// "h264-1080p"); for streaming sessions a resolution/fps tier (e.g.
// "vtuber-1080p30"). Pricing is the per-work-unit wholesale rate the
// orchestrator advertises; consumers (gateways/bridges) read it as the
// wholesale-side input to their routing decision.
type Offering struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PricePerWorkUnitWei string                 `protobuf:"bytes,2,opt,name=price_per_work_unit_wei,json=pricePerWorkUnitWei,proto3" json:"price_per_work_unit_wei,omitempty"` // decimal big-int as string
	ConstraintsJson     []byte                 `protobuf:"bytes,3,opt,name=constraints_json,json=constraintsJson,proto3" json:"constraints_json,omitempty"`                   // arbitrary JSON object, opaque
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Offering) Reset() {
	*x = Offering{}
	mi := &file_livepeer_registry_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offering) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offering) ProtoMessage() {}

func (x *Offering) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offering.ProtoReflect.Descriptor instead.
func (*Offering) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *Offering) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Offering) GetPricePerWorkUnitWei() string {
	if x != nil {
		return x.PricePerWorkUnitWei
	}
	return ""
}

func (x *Offering) GetConstraintsJson() []byte {
	if x != nil {
		return x.ConstraintsJson
	}
	return nil
}

// Node is one orchestrator endpoint with resolver-attached metadata.
type Node struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url              string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	WorkerEthAddress string                 `protobuf:"bytes,3,opt,name=worker_eth_address,json=workerEthAddress,proto3" json:"worker_eth_address,omitempty"`
	ExtraJson        []byte                 `protobuf:"bytes,4,opt,name=extra_json,json=extraJson,proto3" json:"extra_json,omitempty"` // arbitrary JSON object, opaque
	Capabilities     []*Capability          `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Source           Source                 `protobuf:"varint,6,opt,name=source,proto3,enum=livepeer.registry.v1.Source" json:"source,omitempty"`
	SignatureStatus  SignatureStatus        `protobuf:"varint,7,opt,name=signature_status,json=signatureStatus,proto3,enum=livepeer.registry.v1.SignatureStatus" json:"signature_status,omitempty"`
	OperatorAddress  string                 `protobuf:"bytes,8,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"` // 0x-prefixed lower-case
	Enabled          bool                   `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	TierAllowed      []string               `protobuf:"bytes,10,rep,name=tier_allowed,json=tierAllowed,proto3" json:"tier_allowed,omitempty"`
	Weight           int32                  `protobuf:"varint,11,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_livepeer_registry_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_registry_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_livepeer_registry_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Node) GetWorkerEthAddress() string {
	if x != nil {
		return x.WorkerEthAddress
	}
	return ""
}

func (x *Node) GetExtraJson() []byte {
	if x != nil {
		return x.ExtraJson
	}
	return nil
}

func (x *Node) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Node) GetSource() Source {
	if x != nil {
		return x.Source
	}
	return Source_SOURCE_UNSPECIFIED
}

func (x *Node) GetSignatureStatus() SignatureStatus {
	if x != nil {
		return x.SignatureStatus
	}
	return SignatureStatus_SIGNATURE_STATUS_UNSPECIFIED
}

func (x *Node) GetOperatorAddress() string {
	if x != nil {
		return x.OperatorAddress
	}
	return ""
}

func (x *Node) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Node) GetTierAllowed() []string {
	if x != nil {
		return x.TierAllowed
	}
	return nil
}

func (x *Node) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

var File_livepeer_registry_v1_types_proto protoreflect.FileDescriptor

const file_livepeer_registry_v1_types_proto_rawDesc = "" +
	"\n" +
	" livepeer/registry/v1/types.proto\x12\x14livepeer.registry.v1\"\x9a\x01\n" +
	"\n" +
	"Capability\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\twork_unit\x18\x02 \x01(\tR\bworkUnit\x12<\n" +
	"\tofferings\x18\x03 \x03(\v2\x1e.livepeer.registry.v1.OfferingR\tofferings\x12\x1d\n" +
	"\n" +
	"extra_json\x18\x04 \x01(\fR\textraJson\"{\n" +
	"\bOffering\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\x17price_per_work_unit_wei\x18\x02 \x01(\tR\x13pricePerWorkUnitWei\x12)\n" +
	"\x10constraints_json\x18\x03 \x01(\fR\x0fconstraintsJson\"\xc3\x03\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12,\n" +
	"\x12worker_eth_address\x18\x03 \x01(\tR\x10workerEthAddress\x12\x1d\n" +
	"\n" +
	"extra_json\x18\x04 \x01(\fR\textraJson\x12D\n" +
	"\fcapabilities\x18\x05 \x03(\v2 .livepeer.registry.v1.CapabilityR\fcapabilities\x124\n" +
	"\x06source\x18\x06 \x01(\x0e2\x1c.livepeer.registry.v1.SourceR\x06source\x12P\n" +
	"\x10signature_status\x18\a \x01(\x0e2%.livepeer.registry.v1.SignatureStatusR\x0fsignatureStatus\x12)\n" +
	"\x10operator_address\x18\b \x01(\tR\x0foperatorAddress\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabled\x12!\n" +
	"\ftier_allowed\x18\n" +
	" \x03(\tR\vtierAllowed\x12\x16\n" +
	"\x06weight\x18\v \x01(\x05R\x06weight*w\n" +
	"\vResolveMode\x12\x1c\n" +
	"\x18RESOLVE_MODE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17RESOLVE_MODE_WELL_KNOWN\x10\x01\x12\x14\n" +
	"\x10RESOLVE_MODE_CSV\x10\x02\x12\x17\n" +
	"\x13RESOLVE_MODE_LEGACY\x10\x03*\x8e\x01\n" +
	"\x0fSignatureStatus\x12 \n" +
	"\x1cSIGNATURE_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19SIGNATURE_STATUS_VERIFIED\x10\x01\x12\x1d\n" +
	"\x19SIGNATURE_STATUS_UNSIGNED\x10\x02\x12\x1b\n" +
	"\x17SIGNATURE_STATUS_LEGACY\x10\x03*\x9b\x01\n" +
	"\x0fFreshnessStatus\x12 \n" +
	"\x1cFRESHNESS_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FRESHNESS_STATUS_FRESH\x10\x01\x12&\n" +
	"\"FRESHNESS_STATUS_STALE_RECOVERABLE\x10\x02\x12\"\n" +
	"\x1eFRESHNESS_STATUS_STALE_FAILING\x10\x03*|\n" +
	"\x06Source\x12\x16\n" +
	"\x12SOURCE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSOURCE_MANIFEST\x10\x01\x12\x11\n" +
	"\rSOURCE_LEGACY\x10\x02\x12\x19\n" +
	"\x15SOURCE_STATIC_OVERLAY\x10\x03\x12\x17\n" +
	"\x13SOURCE_CSV_FALLBACK\x10\x04B_Z]github.com/Cloud-SPE/livepeer-network-rewrite/proto-contracts/livepeer/registry/v1;registryv1b\x06proto3"

var (
	file_livepeer_registry_v1_types_proto_rawDescOnce sync.Once
	file_livepeer_registry_v1_types_proto_rawDescData []byte
)

func file_livepeer_registry_v1_types_proto_rawDescGZIP() []byte {
	file_livepeer_registry_v1_types_proto_rawDescOnce.Do(func() {
		file_livepeer_registry_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_livepeer_registry_v1_types_proto_rawDesc), len(file_livepeer_registry_v1_types_proto_rawDesc)))
	})
	return file_livepeer_registry_v1_types_proto_rawDescData
}

var file_livepeer_registry_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_livepeer_registry_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_livepeer_registry_v1_types_proto_goTypes = []any{
	(ResolveMode)(0),     // 0: livepeer.registry.v1.ResolveMode
	(SignatureStatus)(0), // 1: livepeer.registry.v1.SignatureStatus
	(FreshnessStatus)(0), // 2: livepeer.registry.v1.FreshnessStatus
	(Source)(0),          // 3: livepeer.registry.v1.Source
	(*Capability)(nil),   // 4: livepeer.registry.v1.Capability
	(*Offering)(nil),     // 5: livepeer.registry.v1.Offering
	(*Node)(nil),         // 6: livepeer.registry.v1.Node
}
var file_livepeer_registry_v1_types_proto_depIdxs = []int32{
	5, // 0: livepeer.registry.v1.Capability.offerings:type_name -> livepeer.registry.v1.Offering
	4, // 1: livepeer.registry.v1.Node.capabilities:type_name -> livepeer.registry.v1.Capability
	3, // 2: livepeer.registry.v1.Node.source:type_name -> livepeer.registry.v1.Source
	1, // 3: livepeer.registry.v1.Node.signature_status:type_name -> livepeer.registry.v1.SignatureStatus
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_livepeer_registry_v1_types_proto_init() }
func file_livepeer_registry_v1_types_proto_init() {
	if File_livepeer_registry_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_livepeer_registry_v1_types_proto_rawDesc), len(file_livepeer_registry_v1_types_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_livepeer_registry_v1_types_proto_goTypes,
		DependencyIndexes: file_livepeer_registry_v1_types_proto_depIdxs,
		EnumInfos:         file_livepeer_registry_v1_types_proto_enumTypes,
		MessageInfos:      file_livepeer_registry_v1_types_proto_msgTypes,
	}.Build()
	File_livepeer_registry_v1_types_proto = out.File
	file_livepeer_registry_v1_types_proto_goTypes = nil
	file_livepeer_registry_v1_types_proto_depIdxs = nil
}
