// Code generated by protoc-gen-go. DO NOT EDIT.
// source: livepeer/sessionrunner/v1/control.proto

package sessionrunnerv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthRequest) Reset()         { *m = HealthRequest{} }
func (m *HealthRequest) String() string { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()    {}
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_13ba1938e97c1173, []int{0}
}

func (m *HealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthRequest.Unmarshal(m, b)
}
func (m *HealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthRequest.Marshal(b, m, deterministic)
}
func (m *HealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthRequest.Merge(m, src)
}
func (m *HealthRequest) XXX_Size() int {
	return xxx_messageInfo_HealthRequest.Size(m)
}
func (m *HealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthRequest proto.InternalMessageInfo

type HealthResponse struct {
	// Status is one of "ready" | "starting" | "draining". The broker
	// gates session-open on "ready".
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthResponse) Reset()         { *m = HealthResponse{} }
func (m *HealthResponse) String() string { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()    {}
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13ba1938e97c1173, []int{1}
}

func (m *HealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthResponse.Unmarshal(m, b)
}
func (m *HealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthResponse.Marshal(b, m, deterministic)
}
func (m *HealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthResponse.Merge(m, src)
}
func (m *HealthResponse) XXX_Size() int {
	return xxx_messageInfo_HealthResponse.Size(m)
}
func (m *HealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthResponse proto.InternalMessageInfo

func (m *HealthResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// ControlEnvelope is the per-frame wrapper. Mirror of the broker's
// JSON ControlEnvelope; carried inline as bytes so the runner doesn't
// need a workload-aware proto schema.
type ControlEnvelope struct {
	// Type is the envelope type. Reserved prefixes:
	//   - "session.*" — broker-emitted lifecycle envelopes
	//   - "runner.*"  — broker→runner notifications (control_disconnected,
	//     control_reconnected)
	//   - "media.*"   — SDP/ICE plumbing for the WebRTC relay
	//
	// Anything else is workload-defined and relayed verbatim.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Seq is the sender-monotonic sequence number.
	Seq uint64 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// Body is the capability-defined payload, JSON-encoded. Opaque to
	// the broker.
	Body                 []byte   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControlEnvelope) Reset()         { *m = ControlEnvelope{} }
func (m *ControlEnvelope) String() string { return proto.CompactTextString(m) }
func (*ControlEnvelope) ProtoMessage()    {}
func (*ControlEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_13ba1938e97c1173, []int{2}
}

func (m *ControlEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlEnvelope.Unmarshal(m, b)
}
func (m *ControlEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlEnvelope.Marshal(b, m, deterministic)
}
func (m *ControlEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlEnvelope.Merge(m, src)
}
func (m *ControlEnvelope) XXX_Size() int {
	return xxx_messageInfo_ControlEnvelope.Size(m)
}
func (m *ControlEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_ControlEnvelope proto.InternalMessageInfo

func (m *ControlEnvelope) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ControlEnvelope) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *ControlEnvelope) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type WorkUnitReport struct {
	// Delta is the monotonic-positive number of new work units the
	// runner emitted since the previous report. Negative or zero
	// values are protocol errors; the broker discards the report.
	Delta                uint64   `protobuf:"varint,1,opt,name=delta,proto3" json:"delta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkUnitReport) Reset()         { *m = WorkUnitReport{} }
func (m *WorkUnitReport) String() string { return proto.CompactTextString(m) }
func (*WorkUnitReport) ProtoMessage()    {}
func (*WorkUnitReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_13ba1938e97c1173, []int{3}
}

func (m *WorkUnitReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkUnitReport.Unmarshal(m, b)
}
func (m *WorkUnitReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkUnitReport.Marshal(b, m, deterministic)
}
func (m *WorkUnitReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkUnitReport.Merge(m, src)
}
func (m *WorkUnitReport) XXX_Size() int {
	return xxx_messageInfo_WorkUnitReport.Size(m)
}
func (m *WorkUnitReport) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkUnitReport.DiscardUnknown(m)
}

var xxx_messageInfo_WorkUnitReport proto.InternalMessageInfo

func (m *WorkUnitReport) GetDelta() uint64 {
	if m != nil {
		return m.Delta
	}
	return 0
}

type WorkUnitAck struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkUnitAck) Reset()         { *m = WorkUnitAck{} }
func (m *WorkUnitAck) String() string { return proto.CompactTextString(m) }
func (*WorkUnitAck) ProtoMessage()    {}
func (*WorkUnitAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_13ba1938e97c1173, []int{4}
}

func (m *WorkUnitAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkUnitAck.Unmarshal(m, b)
}
func (m *WorkUnitAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkUnitAck.Marshal(b, m, deterministic)
}
func (m *WorkUnitAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkUnitAck.Merge(m, src)
}
func (m *WorkUnitAck) XXX_Size() int {
	return xxx_messageInfo_WorkUnitAck.Size(m)
}
func (m *WorkUnitAck) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkUnitAck.DiscardUnknown(m)
}

var xxx_messageInfo_WorkUnitAck proto.InternalMessageInfo

type ShutdownRequest struct {
	// Graceful indicates whether the runner should drain in-flight
	// work or abort immediately.
	Graceful             bool     `protobuf:"varint,1,opt,name=graceful,proto3" json:"graceful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownRequest) Reset()         { *m = ShutdownRequest{} }
func (m *ShutdownRequest) String() string { return proto.CompactTextString(m) }
func (*ShutdownRequest) ProtoMessage()    {}
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_13ba1938e97c1173, []int{5}
}

func (m *ShutdownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownRequest.Unmarshal(m, b)
}
func (m *ShutdownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownRequest.Marshal(b, m, deterministic)
}
func (m *ShutdownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownRequest.Merge(m, src)
}
func (m *ShutdownRequest) XXX_Size() int {
	return xxx_messageInfo_ShutdownRequest.Size(m)
}
func (m *ShutdownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownRequest proto.InternalMessageInfo

func (m *ShutdownRequest) GetGraceful() bool {
	if m != nil {
		return m.Graceful
	}
	return false
}

type ShutdownResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownResponse) Reset()         { *m = ShutdownResponse{} }
func (m *ShutdownResponse) String() string { return proto.CompactTextString(m) }
func (*ShutdownResponse) ProtoMessage()    {}
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13ba1938e97c1173, []int{6}
}

func (m *ShutdownResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownResponse.Unmarshal(m, b)
}
func (m *ShutdownResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownResponse.Marshal(b, m, deterministic)
}
func (m *ShutdownResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownResponse.Merge(m, src)
}
func (m *ShutdownResponse) XXX_Size() int {
	return xxx_messageInfo_ShutdownResponse.Size(m)
}
func (m *ShutdownResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*HealthRequest)(nil), "livepeer.sessionrunner.v1.HealthRequest")
	proto.RegisterType((*HealthResponse)(nil), "livepeer.sessionrunner.v1.HealthResponse")
	proto.RegisterType((*ControlEnvelope)(nil), "livepeer.sessionrunner.v1.ControlEnvelope")
	proto.RegisterType((*WorkUnitReport)(nil), "livepeer.sessionrunner.v1.WorkUnitReport")
	proto.RegisterType((*WorkUnitAck)(nil), "livepeer.sessionrunner.v1.WorkUnitAck")
	proto.RegisterType((*ShutdownRequest)(nil), "livepeer.sessionrunner.v1.ShutdownRequest")
	proto.RegisterType((*ShutdownResponse)(nil), "livepeer.sessionrunner.v1.ShutdownResponse")
}

func init() {
	proto.RegisterFile("livepeer/sessionrunner/v1/control.proto", fileDescriptor_13ba1938e97c1173)
}

var fileDescriptor_13ba1938e97c1173 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0x89, 0xad, 0xa5, 0xfb, 0x74, 0x37, 0xcb, 0xb0, 0x48, 0xcd, 0xa9, 0xe4, 0xb0, 0x46,
	0x25, 0x89, 0xd5, 0xa3, 0xa7, 0x75, 0x59, 0x10, 0xbc, 0xc8, 0x14, 0x11, 0x04, 0x0f, 0x69, 0xf2,
	0x36, 0x0d, 0x19, 0xe7, 0x65, 0x67, 0x26, 0x29, 0x2b, 0x7e, 0x23, 0xbf, 0xa4, 0x74, 0x92, 0x28,
	0xa9, 0xb4, 0x74, 0x6f, 0xef, 0x4d, 0x7e, 0x6f, 0x32, 0xff, 0xdf, 0x30, 0xf0, 0x42, 0x14, 0x0d,
	0x56, 0x88, 0x2a, 0xd6, 0xa8, 0x75, 0x41, 0x52, 0xd5, 0x52, 0xa2, 0x8a, 0x9b, 0x45, 0x9c, 0x92,
	0x34, 0x8a, 0x44, 0x54, 0x29, 0x32, 0xc4, 0x9e, 0xf7, 0x60, 0x34, 0x00, 0xa3, 0x66, 0xe1, 0xbb,
	0x70, 0xfa, 0x11, 0x13, 0x61, 0xd6, 0x1c, 0xef, 0x6a, 0xd4, 0xc6, 0x0f, 0xe0, 0xac, 0x5f, 0xd0,
	0x15, 0x49, 0x8d, 0xec, 0x19, 0x4c, 0xb4, 0x49, 0x4c, 0xad, 0x67, 0xce, 0xdc, 0x09, 0x4e, 0x78,
	0xd7, 0xf9, 0x9f, 0xc0, 0xbd, 0x6e, 0x7f, 0x73, 0x23, 0x1b, 0x14, 0x54, 0x21, 0x63, 0x30, 0x36,
	0xf7, 0x15, 0x76, 0xa0, 0xad, 0xd9, 0x39, 0x8c, 0x34, 0xde, 0xcd, 0x1e, 0xcd, 0x9d, 0x60, 0xcc,
	0xb7, 0xe5, 0x96, 0x5a, 0x51, 0x76, 0x3f, 0x1b, 0xcd, 0x9d, 0xe0, 0x29, 0xb7, 0xb5, 0x7f, 0x09,
	0x67, 0x5f, 0x49, 0x95, 0x5f, 0x64, 0x61, 0x38, 0x56, 0xa4, 0x0c, 0xbb, 0x80, 0xc7, 0x19, 0x0a,
	0x93, 0xd8, 0xcd, 0xc6, 0xbc, 0x6d, 0xfc, 0x53, 0x78, 0xd2, 0x73, 0x57, 0x69, 0xe9, 0x87, 0xe0,
	0x2e, 0xd7, 0xb5, 0xc9, 0x68, 0x23, 0xbb, 0x00, 0xcc, 0x83, 0x69, 0xae, 0x92, 0x14, 0x6f, 0x6b,
	0x61, 0x47, 0xa7, 0xfc, 0x6f, 0xef, 0x33, 0x38, 0xff, 0x87, 0xb7, 0xf1, 0xde, 0xfe, 0x1e, 0xc1,
	0xc5, 0xb2, 0xd5, 0xc2, 0xad, 0x96, 0x2e, 0x14, 0xfb, 0x0e, 0x93, 0xd6, 0x04, 0x0b, 0xa2, 0xbd,
	0x02, 0xa3, 0x81, 0x3d, 0xef, 0xe5, 0x11, 0x64, 0xa7, 0x35, 0x87, 0x93, 0xde, 0x9b, 0x66, 0xaf,
	0x0e, 0xcc, 0xed, 0x48, 0xf6, 0x1e, 0xc0, 0x06, 0xce, 0x1b, 0x87, 0xdd, 0x82, 0xdb, 0x2a, 0xed,
	0xc5, 0x69, 0x76, 0xe8, 0x98, 0xc3, 0x6b, 0xf0, 0x2e, 0x8f, 0x40, 0xaf, 0xd2, 0x32, 0x70, 0x58,
	0x0a, 0xd3, 0x5e, 0xee, 0xc1, 0x3c, 0x3b, 0x17, 0xe6, 0xbd, 0x3e, 0x8a, 0x6d, 0xad, 0x7d, 0xf8,
	0xf5, 0xed, 0x67, 0x5e, 0x98, 0x75, 0xbd, 0x8a, 0x52, 0xfa, 0x11, 0x5f, 0x0b, 0xaa, 0xb3, 0x70,
	0xf9, 0xf9, 0x26, 0xee, 0xb7, 0x08, 0x25, 0x9a, 0x0d, 0xa9, 0x32, 0x54, 0xb8, 0x51, 0x85, 0xc1,
	0xff, 0x3f, 0xd8, 0x27, 0x91, 0x92, 0x88, 0x6d, 0x11, 0xe6, 0x14, 0xef, 0x7d, 0x46, 0xef, 0x07,
	0x0b, 0xcd, 0x62, 0x35, 0xb1, 0x33, 0xef, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x88, 0xb6, 0x1d,
	0x0e, 0x7a, 0x03, 0x00, 0x00,
}
