// Livepeer SessionRunner v1 — media-plane IPC.
//
// Raw RTP packets flow between broker and runner over a bidirectional
// gRPC stream. The broker stays codec-opaque — workloads that prefer
// decoded frames decode in the runner.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: livepeer/sessionrunner/v1/media.proto

package sessionrunnerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_DIRECTION_INGRESS     Direction = 1
	Direction_DIRECTION_EGRESS      Direction = 2
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_INGRESS",
		2: "DIRECTION_EGRESS",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_INGRESS":     1,
		"DIRECTION_EGRESS":      2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_livepeer_sessionrunner_v1_media_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_livepeer_sessionrunner_v1_media_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_livepeer_sessionrunner_v1_media_proto_rawDescGZIP(), []int{0}
}

type MediaFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Direction labels which leg this frame belongs to.
	Direction Direction `protobuf:"varint,1,opt,name=direction,proto3,enum=livepeer.sessionrunner.v1.Direction" json:"direction,omitempty"`
	// TrackId disambiguates within a leg (e.g., one audio + one video).
	TrackId string `protobuf:"bytes,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	// PayloadType is the RTP payload type the relay observed.
	PayloadType uint32 `protobuf:"varint,3,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	// Rtp is the raw RTP packet bytes.
	Rtp           []byte `protobuf:"bytes,4,opt,name=rtp,proto3" json:"rtp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaFrame) Reset() {
	*x = MediaFrame{}
	mi := &file_livepeer_sessionrunner_v1_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaFrame) ProtoMessage() {}

func (x *MediaFrame) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_sessionrunner_v1_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaFrame.ProtoReflect.Descriptor instead.
func (*MediaFrame) Descriptor() ([]byte, []int) {
	return file_livepeer_sessionrunner_v1_media_proto_rawDescGZIP(), []int{0}
}

func (x *MediaFrame) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *MediaFrame) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *MediaFrame) GetPayloadType() uint32 {
	if x != nil {
		return x.PayloadType
	}
	return 0
}

func (x *MediaFrame) GetRtp() []byte {
	if x != nil {
		return x.Rtp
	}
	return nil
}

var File_livepeer_sessionrunner_v1_media_proto protoreflect.FileDescriptor

const file_livepeer_sessionrunner_v1_media_proto_rawDesc = "" +
	"\n" +
	"%livepeer/sessionrunner/v1/media.proto\x12\x19livepeer.sessionrunner.v1\"\xa0\x01\n" +
	"\n" +
	"MediaFrame\x12B\n" +
	"\tdirection\x18\x01 \x01(\x0e2$.livepeer.sessionrunner.v1.DirectionR\tdirection\x12\x19\n" +
	"\btrack_id\x18\x02 \x01(\tR\atrackId\x12!\n" +
	"\fpayload_type\x18\x03 \x01(\rR\vpayloadType\x12\x10\n" +
	"\x03rtp\x18\x04 \x01(\fR\x03rtp*S\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DIRECTION_INGRESS\x10\x01\x12\x14\n" +
	"\x10DIRECTION_EGRESS\x10\x022p\n" +
	"\x12SessionRunnerMedia\x12Z\n" +
	"\x06Frames\x12%.livepeer.sessionrunner.v1.MediaFrame\x1a%.livepeer.sessionrunner.v1.MediaFrame(\x010\x01B|Zzgithub.com/Cloud-SPE/livepeer-network-modules/livepeer-network-protocol/proto-go/livepeer/sessionrunner/v1;sessionrunnerv1b\x06proto3"

var (
	file_livepeer_sessionrunner_v1_media_proto_rawDescOnce sync.Once
	file_livepeer_sessionrunner_v1_media_proto_rawDescData []byte
)

func file_livepeer_sessionrunner_v1_media_proto_rawDescGZIP() []byte {
	file_livepeer_sessionrunner_v1_media_proto_rawDescOnce.Do(func() {
		file_livepeer_sessionrunner_v1_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_livepeer_sessionrunner_v1_media_proto_rawDesc), len(file_livepeer_sessionrunner_v1_media_proto_rawDesc)))
	})
	return file_livepeer_sessionrunner_v1_media_proto_rawDescData
}

var file_livepeer_sessionrunner_v1_media_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_livepeer_sessionrunner_v1_media_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_livepeer_sessionrunner_v1_media_proto_goTypes = []any{
	(Direction)(0),     // 0: livepeer.sessionrunner.v1.Direction
	(*MediaFrame)(nil), // 1: livepeer.sessionrunner.v1.MediaFrame
}
var file_livepeer_sessionrunner_v1_media_proto_depIdxs = []int32{
	0, // 0: livepeer.sessionrunner.v1.MediaFrame.direction:type_name -> livepeer.sessionrunner.v1.Direction
	1, // 1: livepeer.sessionrunner.v1.SessionRunnerMedia.Frames:input_type -> livepeer.sessionrunner.v1.MediaFrame
	1, // 2: livepeer.sessionrunner.v1.SessionRunnerMedia.Frames:output_type -> livepeer.sessionrunner.v1.MediaFrame
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_livepeer_sessionrunner_v1_media_proto_init() }
func file_livepeer_sessionrunner_v1_media_proto_init() {
	if File_livepeer_sessionrunner_v1_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_livepeer_sessionrunner_v1_media_proto_rawDesc), len(file_livepeer_sessionrunner_v1_media_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_livepeer_sessionrunner_v1_media_proto_goTypes,
		DependencyIndexes: file_livepeer_sessionrunner_v1_media_proto_depIdxs,
		EnumInfos:         file_livepeer_sessionrunner_v1_media_proto_enumTypes,
		MessageInfos:      file_livepeer_sessionrunner_v1_media_proto_msgTypes,
	}.Build()
	File_livepeer_sessionrunner_v1_media_proto = out.File
	file_livepeer_sessionrunner_v1_media_proto_goTypes = nil
	file_livepeer_sessionrunner_v1_media_proto_depIdxs = nil
}
